import type { DemoPack } from "../types";

/**
 * 校园生活：唐悦的摄影与记忆展线 + 佳欣的智理杯组队线。
 *
 * 两条线通过几个真实感的桥相连：佳欣与校媒王晨同上新闻采写课、
 * 梓涵与蒋博是程设课联调搭档、嘉豪与周宁合作学生节物料、子轩在创业
 * 分享会认识谢扬。两个同名王晨保留，用于演示身份消歧。
 */
export const campusPack: DemoPack = {
  id: "campus",
  group: "life",
  name: "校园生活",
  description: "同学、社团、展览与两位同名人物",
  example: "看看唐悦如何连接摄影社与校园记忆展",
  universe: "一所综合性大学（模拟），2026 年秋，主角圈是大四与研二学生。",
  collections: [
    {
      name: "大学同学",
      members: [
        "tangyue",
        "zhouning",
        "wangchen-media",
        "lizhe",
        "mengxin",
        "jiangbo",
        "qinyue",
        "xieyang",
        "yufei",
        "wangchen-music",
        "jiaxin",
        "zihan",
        "jiahao",
      ],
    },
    {
      name: "校园摄影社",
      members: ["yeqing", "chengnuo", "qiaomu", "duanxing", "mixue", "gaoyuan", "fanyu", "yaotao"],
    },
    { name: "课外项目组", members: ["jiaxin", "zihan", "jiahao", "zixuan"] },
  ],
  people: [
    {
      key: "tangyue",
      name: "唐悦",
      profile: {
        gender: "女",
        relation: "大学摄影社搭档",
        title: "活动摄影师",
        likes: ["摄影与短视频", "活动摄影"],
        projects: ["校园记忆展（模拟）"],
        contact: "demo-tangyue@example.invalid",
        closeness: 5,
        birthday: "04-19",
        metAt: "大学摄影社招新",
        identities: [
          {
            platform: "大学摄影社（模拟）",
            account: "photo-tang-demo",
            alias: "糖糖",
            validFrom: "2022-09",
            validTo: "2024-06",
          },
          { platform: "当前称呼", alias: "唐悦", validFrom: "2024-07" },
        ],
      },
      note: "合成角色：大学摄影社搭档，负责校园记忆展开幕影像；档期需提前确认。",
      touched: true,
    },
    {
      key: "zhouning",
      name: "周宁",
      profile: {
        gender: "女",
        relation: "大学室友",
        title: "品牌设计师",
        likes: ["海报与视觉设计"],
        projects: ["校园记忆展（模拟）"],
        contact: "demo-zhouning@example.invalid",
        closeness: 5,
        birthday: "12-03",
        metAt: "新生报到分到同一间宿舍",
      },
    },
    {
      key: "wangchen-media",
      name: "王晨",
      profile: {
        gender: "男",
        relation: "学生会同事",
        title: "校园媒体编辑",
        likes: ["文案宣传", "新闻采写"],
        contact: "demo-wangchen1@example.invalid",
        closeness: 4,
        birthday: "06-15",
        metAt: "校园媒体中心纳新",
        identities: [{ platform: "校园媒体中心（模拟）", account: "wc-editor", alias: "晨晨" }],
      },
      note: "合成角色：校媒编辑，与音乐社的王晨同名，靠平台账号区分。",
    },
    {
      key: "lizhe",
      name: "李哲",
      profile: {
        gender: "男",
        relation: "辩论队队友",
        title: "法学院学生",
        likes: ["主持与表达"],
        contact: "demo-lizhe@example.invalid",
        closeness: 4,
        birthday: "09-27",
        metAt: "院际辩论赛选拔",
      },
    },
    {
      key: "mengxin",
      name: "孟欣",
      profile: {
        gender: "女",
        relation: "志愿活动搭档",
        title: "社团负责人",
        likes: ["活动组织"],
        contact: "demo-mengxin@example.invalid",
        closeness: 3,
        birthday: "03-08",
        metAt: "迎新志愿服务",
      },
    },
    {
      key: "jiangbo",
      name: "蒋博",
      profile: {
        gender: "男",
        relation: "课程队友",
        title: "后端工程师",
        likes: ["接口开发"],
        contact: "demo-jiangbo@example.invalid",
        closeness: 3,
        birthday: "11-11",
        metAt: "软件工程课程分组",
      },
    },
    {
      key: "qinyue",
      name: "秦月",
      profile: {
        gender: "女",
        relation: "校报记者",
        title: "新闻摄影记者",
        likes: ["采访摄影", "纪实摄影"],
        contact: "demo-qinyue@example.invalid",
        closeness: 5,
        birthday: "07-22",
        metAt: "校报摄影组例会",
      },
    },
    {
      key: "xieyang",
      name: "谢扬",
      profile: {
        gender: "男",
        relation: "创业赛队友",
        title: "创业者",
        likes: ["赞助洽谈"],
        contact: "demo-xieyang@example.invalid",
        closeness: 3,
        birthday: "01-30",
        metAt: "校级创业赛组队",
      },
    },
    {
      key: "yufei",
      name: "于菲",
      profile: {
        gender: "女",
        relation: "前室友",
        title: "用户研究员",
        likes: ["访谈研究"],
        contact: "demo-yufei@example.invalid",
        closeness: 4,
        birthday: "05-06",
        metAt: "大一同宿舍，后交换宿舍",
      },
    },
    {
      key: "wangchen-music",
      name: "王晨",
      profile: {
        gender: "男",
        relation: "同名校友",
        title: "音乐社成员",
        likes: ["现场音响"],
        contact: "demo-wangchen2@example.invalid",
        closeness: 2,
        birthday: "08-09",
        metAt: "校园音乐节后台",
        identities: [{ platform: "音乐社（模拟）", account: "wc-sound", alias: "小王" }],
      },
      note: "合成角色：与校媒的王晨同名，用于演示同名消歧。",
    },
    {
      key: "jiaxin",
      name: "佳欣",
      profile: {
        gender: "女",
        relation: "写沟课同学",
        title: "社会学系学生",
        likes: ["需求梳理", "访谈与田野"],
        projects: ["访谈项目（模拟）"],
        contact: "demo-jiaxin@example.invalid",
        closeness: 4,
        birthday: "04-12",
        metAt: "写作与沟通课程同组",
      },
      note: "合成角色：写沟课同学，做过十几场访谈、跑过田野调查，擅长把想法梳理成需求。",
    },
    {
      key: "zihan",
      name: "梓涵",
      profile: {
        gender: "女",
        relation: "程设队友",
        title: "计算机系学生",
        likes: ["界面设计", "接口联调"],
        projects: ["程设大作业（模拟）"],
        contact: "demo-zihan@example.invalid",
        closeness: 4,
        birthday: "10-24",
        metAt: "程序设计课大作业组队",
      },
      note: "合成角色：程设队友，大作业负责界面与接口联调，合作记录很好。",
    },
    {
      key: "jiahao",
      name: "嘉豪",
      profile: {
        gender: "男",
        relation: "学生节合作认识",
        title: "数字媒体艺术学生",
        likes: ["海报设计", "宣传短片"],
        contact: undefined,
        closeness: 3,
        birthday: "02-14",
        metAt: "学生节宣传物料合作",
      },
      note: "合成角色：学生节合作认识，擅长视觉表达；联系方式还没要到，档案里先留空待补。",
    },
    {
      key: "zixuan",
      name: "子轩",
      profile: {
        gender: "男",
        relation: "佳欣介绍认识",
        title: "计算机系学生",
        likes: ["Agent 搭建", "志愿服务"],
        contact: "demo-zixuan@example.invalid",
        closeness: 3,
        birthday: "12-28",
        metAt: "佳欣介绍认识",
      },
      note: "合成角色：佳欣介绍认识，做过「清小搭」志愿者，懂 Agent 搭建。",
    },
    {
      key: "yeqing",
      name: "叶青",
      profile: {
        gender: "女",
        relation: "摄影社社长",
        title: "人像摄影师",
        likes: ["人像摄影"],
        projects: ["校园记忆展（模拟）"],
        contact: "demo-yeqing@example.invalid",
        closeness: 5,
        birthday: "11-02",
        metAt: "摄影社招新面试",
      },
    },
    {
      key: "chengnuo",
      name: "程诺",
      profile: {
        gender: "男",
        relation: "后期搭档",
        title: "视频剪辑师",
        likes: ["剪辑调色"],
        projects: ["校园记忆展（模拟）"],
        contact: "demo-chengnuo@example.invalid",
        closeness: 4,
        birthday: "08-31",
        metAt: "摄影社短片项目",
      },
    },
    {
      key: "qiaomu",
      name: "乔木",
      profile: {
        gender: "男",
        relation: "器材管理员",
        title: "器材租赁顾问",
        likes: ["相机灯光"],
        contact: "demo-qiaomu@example.invalid",
        closeness: 3,
        birthday: "05-19",
        metAt: "摄影社器材组",
      },
    },
    {
      key: "duanxing",
      name: "段星",
      profile: {
        gender: "男",
        relation: "活动搭档",
        title: "无人机飞手",
        likes: ["航拍"],
        contact: undefined,
        closeness: 3,
        birthday: "09-09",
        metAt: "校园航拍项目",
      },
    },
    {
      key: "mixue",
      name: "米雪",
      profile: {
        gender: "女",
        relation: "模特朋友",
        title: "造型师",
        likes: ["妆造搭配"],
        contact: "demo-mixue@example.invalid",
        closeness: 3,
        birthday: "06-06",
        metAt: "人像创作拍摄",
      },
    },
    {
      key: "gaoyuan",
      name: "高远",
      profile: {
        gender: "男",
        relation: "社团指导老师",
        title: "艺术教师",
        likes: ["视觉策划"],
        contact: "demo-gaoyuan@example.invalid",
        closeness: 3,
        birthday: "10-03",
        metAt: "摄影社指导环节",
      },
    },
    {
      key: "fanyu",
      name: "范雨",
      profile: {
        gender: "女",
        relation: "展览搭档",
        title: "策展助理",
        likes: ["展览执行"],
        projects: ["校园记忆展（模拟）"],
        contact: "demo-fanyu@example.invalid",
        closeness: 3,
        birthday: "01-16",
        metAt: "年度展览筹备",
      },
    },
    {
      key: "yaotao",
      name: "姚桃",
      profile: {
        gender: "女",
        relation: "短片搭档",
        title: "编剧",
        likes: ["故事策划"],
        contact: undefined,
        closeness: 3,
        birthday: "07-07",
        metAt: "社团招新短片",
      },
    },
  ],
  relations: [
    // 唐悦线：同学、室友与共同项目。
    {
      from: "tangyue",
      to: "zhouning",
      predicate: "roommate_of",
      label: "前室友",
      note: "大二至毕业前住在同一间宿舍，后各自实习合租",
      qualifiers: { temporalStatus: "former", validFrom: "2022-09", validTo: "2025-06" },
      validity: { status: "ended", validFrom: "2022-09", validTo: "2025-06" },
    },
    {
      from: "tangyue",
      to: "wangchen-media",
      predicate: "classmate_of",
      label: "大学同学",
      note: "同修新闻摄影课程",
    },
    {
      from: "tangyue",
      to: "lizhe",
      predicate: "classmate_of",
      label: "大学同学",
      note: "同属 2022 级公共选修班",
    },
    {
      from: "tangyue",
      to: "mengxin",
      predicate: "collaborates_with",
      label: "志愿活动搭档",
      note: "共同组织迎新志愿活动",
    },
    {
      from: "zhouning",
      to: "wangchen-media",
      predicate: "classmate_of",
      label: "大学同学",
      note: "同修品牌传播课程",
    },
    {
      from: "zhouning",
      to: "jiangbo",
      predicate: "collaborates_with",
      label: "课程项目搭档",
      note: "共同完成校园导览小程序",
    },
    {
      from: "wangchen-media",
      to: "qinyue",
      predicate: "colleague_of",
      label: "校媒同事",
      note: "共同参与校报选题和采编",
    },
    {
      from: "lizhe",
      to: "mengxin",
      predicate: "friend_of",
      label: "辩论赛朋友",
      note: "在校级辩论赛中相识并保持联系",
    },
    {
      from: "mengxin",
      to: "xieyang",
      predicate: "collaborates_with",
      label: "活动组织搭档",
      note: "共同负责毕业季活动",
    },
    {
      from: "jiangbo",
      to: "zihan",
      predicate: "collaborates_with",
      label: "程设课联调搭档",
      note: "梓涵负责界面、蒋博负责后端接口，联调顺畅",
    },
    {
      from: "qinyue",
      to: "yufei",
      predicate: "friend_of",
      label: "采访搭档",
      note: "共同完成校友口述史采访",
    },
    {
      from: "xieyang",
      to: "yufei",
      predicate: "collaborates_with",
      label: "创业赛队友",
      note: "共同参加大学生创业赛",
    },
    {
      from: "xieyang",
      to: "wangchen-music",
      predicate: "knows",
      label: "音乐节认识",
      note: "在校园音乐节后台相识",
    },
    {
      from: "tangyue",
      to: "wangchen-music",
      predicate: "classmate_of",
      label: "摄影选修课同学",
      note: "用于演示两个同名王晨的消歧",
    },
    // 摄影社协作网。
    {
      from: "yeqing",
      to: "qiaomu",
      predicate: "manages",
      label: "社长与器材管理员",
      note: "叶青负责摄影社，乔木管理器材",
    },
    {
      from: "chengnuo",
      to: "yeqing",
      predicate: "collaborates_with",
      label: "后期搭档",
      note: "长期合作完成社团活动视频",
    },
    {
      from: "duanxing",
      to: "yeqing",
      predicate: "collaborates_with",
      label: "航拍搭档",
      note: "共同完成校园航拍项目",
    },
    {
      from: "mixue",
      to: "yeqing",
      predicate: "friend_of",
      label: "模特朋友",
      note: "在人像创作中相识并保持联系",
    },
    {
      from: "gaoyuan",
      to: "yeqing",
      predicate: "collaborates_with",
      label: "社团指导搭档",
      note: "共同策划摄影社年度展览",
    },
    {
      from: "yaotao",
      to: "chengnuo",
      predicate: "collaborates_with",
      label: "短片搭档",
      note: "共同完成社团招新短片",
    },
    {
      from: "qiaomu",
      to: "fanyu",
      predicate: "collaborates_with",
      label: "布展搭档",
      note: "共同负责展览器材和布展",
    },
    {
      from: "yeqing",
      to: "duanxing",
      predicate: "collaborates_with",
      label: "外拍搭档",
      note: "共同负责外景拍摄机位",
    },
    // 记忆展把两拨人连起来。
    {
      from: "tangyue",
      to: "yeqing",
      predicate: "collaborates_with",
      label: "校园记忆展搭档",
      note: "唐悦与叶青共同负责主视觉摄影",
    },
    {
      from: "tangyue",
      to: "chengnuo",
      predicate: "collaborates_with",
      label: "影像制作搭档",
      note: "唐悦负责拍摄，程诺负责剪辑",
    },
    {
      from: "tangyue",
      to: "fanyu",
      predicate: "collaborates_with",
      label: "展览执行搭档",
      note: "共同完成校园记忆展布展",
    },
    {
      from: "zhouning",
      to: "fanyu",
      predicate: "collaborates_with",
      label: "展板设计搭档",
      note: "周宁与范雨共同设计展板",
    },
    // 佳欣线：智理杯组队与它的桥。
    {
      from: "jiaxin",
      to: "zixuan",
      predicate: "knows",
      label: "介绍认识",
      note: "佳欣介绍认识子轩",
      confidence: 0.93,
    },
    {
      from: "jiaxin",
      to: "wangchen-media",
      predicate: "classmate_of",
      label: "新闻采写课同学",
      note: "佳欣与校媒王晨同修新闻采写课",
    },
    {
      from: "jiahao",
      to: "zhouning",
      predicate: "collaborates_with",
      label: "学生节宣传搭档",
      note: "周宁负责主视觉海报，嘉豪完成宣传短片",
    },
    {
      from: "zixuan",
      to: "xieyang",
      predicate: "knows",
      label: "创业分享会认识",
      note: "子轩在创业分享会上认识谢扬",
    },
    {
      from: "jiaxin",
      to: "qinyue",
      predicate: "knows",
      label: "可能合作过",
      note: "两人在校媒选题会名单中同框，尚未人工确认",
      pending: true,
    },
  ],
  events: [
    // 佳欣线：最近两周最活跃，用于演示新鲜度排序。
    {
      date: "2026-09-16",
      title: "与佳欣聊智理杯选题",
      kind: "其它",
      people: ["jiaxin"],
      place: "系馆咖啡馆",
      detail: "聊组队方向、访谈方法和下一步分工。",
    },
    {
      date: "2026-09-15",
      title: "写沟课小组讨论：访谈提纲",
      kind: "其它",
      people: ["jiaxin"],
      detail: "与佳欣同组，讨论田野访谈提纲。",
    },
    {
      date: "2026-09-08",
      title: "写沟课小组讨论：选题方向",
      kind: "其它",
      people: ["jiaxin"],
      detail: "第一次同组讨论，确定智理杯相关选题。",
    },
    {
      date: "2026-08-30",
      title: "与子轩通电话聊志愿经历",
      kind: "通话",
      people: ["zixuan"],
      detail: "听他讲「清小搭」志愿者经历和 Agent 搭建经验。",
    },
    {
      date: "2026-08-24",
      title: "学生节宣传短片杀青",
      kind: "帮忙",
      people: ["jiahao", "zhouning"],
      detail: "周宁完成主视觉海报，嘉豪交付宣传短片。",
    },
    // 记忆展线。
    {
      date: "2026-09-12",
      title: "校园记忆展开幕",
      kind: "聚会",
      people: ["tangyue", "yeqing", "chengnuo", "zhouning", "fanyu", "gaoyuan"],
      place: "大学生活动中心",
      detail: "开幕当天完成导览与现场影像记录。",
    },
    {
      date: "2026-09-05",
      title: "摄影社纳新培训",
      kind: "聚会",
      people: ["yeqing", "chengnuo", "qiaomu"],
      place: "学生活动中心",
      detail: "给纳新社员讲解器材使用和外拍流程。",
    },
    {
      date: "2026-08-27",
      title: "最终布展",
      kind: "帮忙",
      people: ["tangyue", "zhouning", "yeqing", "chengnuo", "qiaomu", "fanyu"],
      detail: "完成展板、投影、灯光和播放设备安装。",
    },
    {
      date: "2026-08-21",
      title: "音乐节影像复盘",
      kind: "聚会",
      people: ["chengnuo", "duanxing", "yaotao", "yeqing"],
      detail: "复盘航拍、现场机位与后期交付。",
    },
    {
      date: "2026-08-13",
      title: "完成人物肖像试拍",
      kind: "帮忙",
      people: ["tangyue", "yeqing", "mixue"],
      detail: "完成三组光线方案并选定正式拍摄风格。",
    },
    {
      date: "2026-08-07",
      title: "展览场地踩点",
      kind: "帮忙",
      people: ["tangyue", "yeqing", "qiaomu", "duanxing"],
      place: "大学生活动中心",
      detail: "确认机位、灯光、电源和器材动线。",
    },
    {
      date: "2026-08-05",
      title: "校园记忆展第一次策划会",
      kind: "聚会",
      people: ["tangyue", "zhouning", "yeqing", "fanyu"],
      detail: "确定人物采访、摄影和展板分工。",
    },
    {
      date: "2026-06-20",
      title: "程设大作业结题演示",
      kind: "其它",
      people: ["zihan", "jiangbo"],
      detail: "梓涵负责界面与接口联调，演示顺利通过。",
    },
    {
      date: "2026-05-14",
      title: "校媒专题采访",
      kind: "其它",
      people: ["wangchen-media", "qinyue", "jiaxin"],
      detail: "校媒报道佳欣的田野访谈项目。",
    },
    {
      date: "2026-04-19",
      title: "创业分享会",
      kind: "聚会",
      people: ["xieyang", "zixuan"],
      place: "创业中心",
      detail: "谢扬分享创业赛经验，子轩现场提问。",
    },
    {
      date: "2025-10-04",
      title: "摄影社秋季外拍",
      kind: "聚会",
      people: ["yeqing", "chengnuo", "qiaomu", "duanxing", "mixue"],
      place: "滨江公园",
      detail: "社团新人第一次集体外拍。",
    },
    {
      date: "2025-09-01",
      precision: "month",
      title: "加入大学摄影社",
      kind: "其它",
      people: ["tangyue", "yeqing"],
      detail: "唐悦在招新季认识叶青。",
    },
    {
      date: "2025-06-13",
      title: "学年合影",
      kind: "聚会",
      people: ["tangyue", "zhouning", "wangchen-media", "lizhe", "mengxin"],
      place: "教学楼前",
      detail: "期末季在教学楼前拍下学年合影。",
    },
    {
      date: "2025-06-01",
      precision: "month",
      title: "宿舍换租",
      kind: "其它",
      people: ["tangyue", "zhouning"],
      detail: "两人先后搬出宿舍开始实习合租，具体日期未记录。",
    },
    {
      date: "2024-07-15",
      dateEnd: "2024-08-20",
      precision: "range",
      title: "暑期社区志愿服务",
      kind: "帮忙",
      people: ["mengxin", "yufei"],
      detail: "持续一个多月的社区暑期志愿服务。",
    },
    {
      date: "2023-11-08",
      title: "创业赛决赛",
      kind: "其它",
      people: ["xieyang", "yufei"],
      detail: "共同完成路演并获得校级奖项。",
    },
    {
      date: "2022-09-01",
      precision: "month",
      title: "成为大学室友",
      kind: "其它",
      people: ["tangyue", "zhouning"],
      detail: "新生报到月开始合住。",
    },
  ],
  reminders: [
    { title: "给佳欣发访谈提纲", due: "2026-09-20", people: ["jiaxin"], kind: "custom" },
    {
      title: "给唐悦确认记忆展后续拍摄档期",
      due: "2026-09-25",
      people: ["tangyue"],
      kind: "custom",
    },
    { title: "归还摄影社外拍镜头", due: "2026-09-22", people: ["qiaomu"], kind: "custom" },
  ],
};
