import type { DemoPack } from "../types";

/**
 * 家庭往来：一张三代亲属网，喂给亲属投影、称谓推导与路径演示。
 * 外婆周秀兰与已故外公林望舒补上 grandparent 链与 ended 配偶实例，
 * 陆鸣/许兰提供 uncle_aunt 实例。关系全部走亲属谓词，保证关系图
 * 的「自动布局」在纯亲属数据上仍能切回家族树画法。
 */
export const familyPack: DemoPack = {
  id: "family",
  group: "life",
  name: "家庭往来",
  description: "家人、亲戚、生日与亲属关系推导",
  example: "从苏琴、林慧和陆鸣看清一张家庭关系网",
  universe: "一个江南城市的三代之家（模拟），逢年过节常在外婆家聚会。",
  collections: [
    {
      name: "家人",
      members: ["linhui", "chenan", "xulan", "zhaoyu", "suqin", "zhouxiulan", "linwangshu"],
    },
    { name: "亲戚", members: ["guchuan", "shenfang", "luming", "hejing"] },
  ],
  people: [
    {
      key: "linhui",
      name: "林慧",
      profile: {
        gender: "女",
        relation: "姐姐",
        title: "中学教师",
        likes: ["语文写作"],
        contact: "demo-linhui@example.invalid",
        closeness: 5,
        birthday: "09-14",
        metAt: "一起长大",
      },
    },
    {
      key: "chenan",
      name: "陈安",
      profile: {
        gender: "男",
        relation: "表哥",
        title: "律师",
        likes: ["合同审阅"],
        contact: "demo-chenan@example.invalid",
        closeness: 4,
        birthday: "03-21",
        metAt: "家族聚会",
      },
    },
    {
      key: "xulan",
      name: "许兰",
      profile: {
        gender: "女",
        relation: "小姨",
        title: "社区医生",
        likes: ["健康咨询"],
        contact: "demo-xulan@example.invalid",
        closeness: 4,
        birthday: "07-19",
        metAt: "从小认识",
      },
    },
    {
      key: "zhaoyu",
      name: "赵宇",
      profile: {
        gender: "男",
        relation: "堂弟",
        title: "前端工程师",
        likes: ["网站开发"],
        contact: "demo-zhaoyu@example.invalid",
        closeness: 4,
        birthday: "11-08",
        metAt: "家族聚会",
      },
    },
    {
      key: "suqin",
      name: "苏琴",
      profile: {
        gender: "女",
        relation: "母亲",
        title: "退休会计",
        likes: ["预算管理"],
        contact: "demo-suqin@example.invalid",
        closeness: 5,
        birthday: "09-16",
        metAt: "家人",
      },
    },
    {
      key: "guchuan",
      name: "顾川",
      profile: {
        gender: "男",
        relation: "表弟",
        title: "研究生",
        likes: ["数据分析"],
        contact: "demo-guchuan@example.invalid",
        closeness: 3,
        birthday: "05-25",
        metAt: "舅舅家聚会",
      },
    },
    {
      key: "shenfang",
      name: "沈芳",
      profile: {
        gender: "女",
        relation: "舅妈",
        title: "烘焙店主",
        likes: ["活动茶歇"],
        contact: "demo-shenfang@example.invalid",
        closeness: 3,
        birthday: "01-09",
        metAt: "舅舅婚礼",
      },
    },
    {
      key: "luming",
      name: "陆鸣",
      profile: {
        gender: "男",
        relation: "舅舅",
        title: "建筑师",
        likes: ["空间设计"],
        contact: "demo-luming@example.invalid",
        closeness: 3,
        birthday: "04-07",
        metAt: "家人",
      },
    },
    {
      key: "hejing",
      name: "何静",
      profile: {
        gender: "女",
        relation: "表姐",
        title: "人力资源经理",
        likes: ["招聘面试"],
        contact: "demo-hejing@example.invalid",
        closeness: 4,
        birthday: "08-23",
        metAt: "姨妈家聚会",
      },
    },
    {
      key: "zhouxiulan",
      name: "周秀兰",
      profile: {
        gender: "女",
        relation: "外婆",
        title: "退休纺织厂工人",
        likes: ["家宴操办", "种花"],
        contact: undefined,
        closeness: 5,
        birthday: "10-11",
        metAt: "家人",
        identities: [{ platform: "家族微信群（模拟）", alias: "秀兰外婆" }],
      },
      note: "合成角色：外婆，家宴的组织者；联系方式由妈妈代管，档案里先留空。",
    },
    {
      key: "linwangshu",
      name: "林望舒",
      profile: {
        gender: "男",
        relation: "外公",
        title: "退休中学教师",
        likes: ["书法", "盆景"],
        contact: undefined,
        closeness: 4,
        birthday: "06-20",
        metAt: "家人",
      },
      note: "合成角色：外婆周秀兰的丈夫，母亲与小姨的父亲，已故；档案保留用于家谱与祭扫提醒。",
    },
  ],
  relations: [
    {
      from: "suqin",
      to: "linhui",
      predicate: "parent_of",
      label: "母女",
      note: "苏琴是林慧的母亲",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "suqin",
      to: "luming",
      predicate: "sibling_of",
      label: "姐弟",
      note: "苏琴与陆鸣是姐弟",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "luming",
      to: "shenfang",
      predicate: "spouse_of",
      label: "夫妻",
      note: "陆鸣与沈芳是夫妻",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
    },
    {
      from: "luming",
      to: "guchuan",
      predicate: "parent_of",
      label: "父子",
      note: "陆鸣是顾川的父亲",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "shenfang",
      to: "guchuan",
      predicate: "parent_of",
      label: "母子",
      note: "沈芳是顾川的母亲",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "suqin",
      to: "xulan",
      predicate: "sibling_of",
      label: "姐妹",
      note: "苏琴与许兰是姐妹",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "xulan",
      to: "hejing",
      predicate: "parent_of",
      label: "母女",
      note: "许兰是何静的母亲",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "zhouxiulan",
      to: "suqin",
      predicate: "parent_of",
      label: "母女",
      note: "周秀兰是苏琴的母亲",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "zhouxiulan",
      to: "xulan",
      predicate: "parent_of",
      label: "母女",
      note: "周秀兰是许兰的母亲",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "zhouxiulan",
      to: "linhui",
      predicate: "grandparent_of",
      label: "外婆与外孙女",
      note: "周秀兰是林慧的外婆",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "zhouxiulan",
      to: "hejing",
      predicate: "grandparent_of",
      label: "外婆与外孙女",
      note: "周秀兰是何静的外婆",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "luming",
      to: "linhui",
      predicate: "uncle_aunt_of",
      label: "舅舅与外甥女",
      note: "陆鸣是林慧的舅舅",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "xulan",
      to: "linhui",
      predicate: "uncle_aunt_of",
      label: "姨妈与外甥女",
      note: "许兰是林慧的小姨",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "linhui",
      to: "guchuan",
      predicate: "cousin_of",
      label: "表姐弟",
      note: "林慧与顾川是表姐弟",
      qualifiers: {
        cousinBranch: "maternal_uncle",
        inverseCousinBranch: "paternal_aunt",
        lineage: "blood",
      },
    },
    {
      from: "linhui",
      to: "hejing",
      predicate: "cousin_of",
      label: "表姐妹",
      note: "林慧与何静是表姐妹",
      qualifiers: {
        cousinBranch: "maternal_aunt",
        inverseCousinBranch: "maternal_aunt",
        lineage: "blood",
      },
    },
    {
      from: "linhui",
      to: "chenan",
      predicate: "cousin_of",
      label: "表兄妹",
      note: "林慧与陈安是表兄妹",
      qualifiers: {
        cousinBranch: "unspecified",
        inverseCousinBranch: "unspecified",
        lineage: "blood",
      },
    },
    {
      from: "linhui",
      to: "zhaoyu",
      predicate: "cousin_of",
      label: "堂姐弟",
      note: "林慧与赵宇是堂姐弟",
      qualifiers: {
        cousinBranch: "paternal_uncle",
        inverseCousinBranch: "paternal_uncle",
        lineage: "blood",
      },
    },
    {
      from: "chenan",
      to: "zhaoyu",
      predicate: "cousin_of",
      label: "远房堂亲（待核实）",
      note: "族谱记载两家是远房堂亲，尚未核实",
      qualifiers: {
        cousinBranch: "unspecified",
        inverseCousinBranch: "unspecified",
        lineage: "blood",
      },
      pending: true,
    },
    {
      from: "shenfang",
      to: "hejing",
      predicate: "in_law_of",
      label: "舅妈与外甥女",
      note: "沈芳是陆鸣之妻，何静的舅妈",
      qualifiers: { lineage: "marriage", inLawRole: "unspecified" },
    },
    {
      from: "linwangshu",
      to: "zhouxiulan",
      predicate: "spouse_of",
      label: "夫妻",
      note: "林望舒已故，与周秀兰的婚姻随其离世结束",
      qualifiers: { partnerRole: "husband", lineage: "marriage", temporalStatus: "former" },
      validity: { status: "ended" },
    },
    {
      from: "linwangshu",
      to: "suqin",
      predicate: "parent_of",
      label: "父女",
      note: "林望舒是苏琴的父亲",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "linwangshu",
      to: "xulan",
      predicate: "parent_of",
      label: "父女",
      note: "林望舒是许兰的父亲",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "linwangshu",
      to: "linhui",
      predicate: "grandparent_of",
      label: "外公与外孙女",
      note: "林望舒是林慧的外公",
      qualifiers: { lineage: "blood" },
    },
  ],
  events: [
    {
      date: "2026-09-12",
      title: "家庭生日聚餐",
      kind: "聚会",
      people: ["linhui", "xulan", "suqin", "zhouxiulan"],
      place: "家中",
      detail: "为苏琴提前庆祝生日。",
    },
    {
      date: "2026-05-02",
      title: "五一小聚",
      kind: "聚会",
      people: ["linhui", "zhaoyu", "chenan"],
      place: "城郊公园",
      detail: "表兄妹带娃春游，顺便聊近况。",
    },
    {
      date: "2026-02-17",
      dateText: "大年初一",
      title: "春节家族聚会",
      kind: "聚会",
      people: [
        "linhui",
        "chenan",
        "xulan",
        "zhaoyu",
        "suqin",
        "guchuan",
        "shenfang",
        "luming",
        "hejing",
        "zhouxiulan",
      ],
      place: "外婆家",
      detail: "全家在外婆家吃年夜饭，沈芳带了自制点心。",
    },
    {
      date: "2025-10-11",
      title: "外婆生日家宴",
      kind: "聚会",
      people: ["linhui", "suqin", "xulan", "luming", "hejing", "zhouxiulan"],
      place: "外婆家",
      detail: "三代人给周秀兰过生日。",
    },
    {
      date: "2026-04-05",
      title: "清明祭扫外公",
      kind: "其它",
      people: ["linhui", "suqin", "xulan", "zhouxiulan"],
      place: "城郊",
      detail: "清明陪外婆祭扫外公，顺路吃了顿午饭。",
    },
  ],
  reminders: [
    { title: "给外婆订生日家宴餐厅", due: "2026-10-11", people: ["zhouxiulan"], kind: "birthday" },
    { title: "给外婆捎一罐秋茶", due: "2026-09-28", people: ["zhouxiulan"], kind: "gift" },
  ],
};
