import type { DemoPack } from "../types";

/**
 * 小企业协作：校友社群里找合作伙伴。包内自带 pending 与 ended 实例，
 * 不再复用其他场景的人物，可独立载入。
 */
export const smallBusinessPack: DemoPack = {
  id: "small_business",
  group: "life",
  name: "小企业协作",
  description: "创业、市场、招聘、技术与内容交付",
  example: "在有限团队之外找到可靠的合作伙伴",
  universe: "围绕校友会的一支松散合作网络（模拟），成员来自不同公司与自由职业。",
  collections: [
    {
      name: "校友社群",
      members: ["yuanye", "fengfan", "maoxin", "tanya", "gongming", "xueqi", "liaoxing", "kongjia"],
    },
  ],
  people: [
    {
      key: "yuanye",
      name: "袁野",
      profile: {
        gender: "男",
        relation: "校友会负责人",
        title: "社群运营",
        org: "校友会（模拟）",
        likes: ["校友活动"],
        contact: "demo-yuanye@example.invalid",
        closeness: 4,
        birthday: "01-22",
        metAt: "校友会志愿工作",
      },
    },
    {
      key: "fengfan",
      name: "冯帆",
      profile: {
        gender: "男",
        relation: "公益活动搭档",
        title: "公益项目经理",
        org: "公益基金会（模拟）",
        likes: ["志愿者协调"],
        contact: "demo-fengfan@example.invalid",
        closeness: 3,
        birthday: "07-14",
        metAt: "校友公益日",
      },
    },
    {
      key: "maoxin",
      name: "毛欣",
      profile: {
        gender: "女",
        relation: "创业营同学",
        title: "市场经理",
        org: "消费品牌（模拟）",
        likes: ["品牌传播"],
        contact: "demo-maoxin@example.invalid",
        closeness: 3,
        birthday: "10-09",
        metAt: "创业营分组",
      },
    },
    {
      key: "tanya",
      name: "谭雅",
      profile: {
        gender: "女",
        relation: "读书会朋友",
        title: "出版编辑",
        org: "出版社（模拟）",
        likes: ["内容策划"],
        contact: "demo-tanya@example.invalid",
        closeness: 3,
        birthday: "04-28",
        metAt: "校友读书会",
      },
    },
    {
      key: "gongming",
      name: "龚明",
      profile: {
        gender: "男",
        relation: "技术沙龙认识",
        title: "云平台工程师",
        org: "云服务公司（模拟）",
        likes: ["现场技术保障"],
        contact: undefined,
        closeness: 2,
        birthday: "08-01",
        metAt: "校友技术沙龙",
      },
    },
    {
      key: "xueqi",
      name: "薛琪",
      profile: {
        gender: "女",
        relation: "招聘会认识",
        title: "校园招聘经理",
        org: "科技公司（模拟）",
        likes: ["招聘资源"],
        contact: "demo-xueqi@example.invalid",
        closeness: 3,
        birthday: "12-06",
        metAt: "校友招聘会",
      },
    },
    {
      key: "liaoxing",
      name: "廖星",
      profile: {
        gender: "男",
        relation: "主持人朋友",
        title: "播客主播",
        org: "独立播客（模拟）",
        likes: ["主持采访"],
        contact: "demo-liaoxing@example.invalid",
        closeness: 3,
        birthday: "05-30",
        metAt: "校友论坛主持",
        identities: [{ platform: "播客平台（模拟）", account: "liao-xing", alias: "星哥" }],
      },
    },
    {
      key: "kongjia",
      name: "孔嘉",
      profile: {
        gender: "男",
        relation: "长期志愿者",
        title: "摄影志愿者",
        org: "自由职业（模拟）",
        likes: ["纪实摄影"],
        contact: "demo-kongjia@example.invalid",
        closeness: 3,
        birthday: "02-08",
        metAt: "公益影像项目",
      },
    },
  ],
  relations: [
    {
      from: "yuanye",
      to: "fengfan",
      predicate: "collaborates_with",
      label: "公益活动搭档",
      note: "共同组织校友公益日",
    },
    {
      from: "yuanye",
      to: "maoxin",
      predicate: "collaborates_with",
      label: "校友传播搭档",
      note: "共同负责校友活动宣传",
    },
    {
      from: "yuanye",
      to: "tanya",
      predicate: "friend_of",
      label: "读书会朋友",
      note: "校友读书会固定成员",
    },
    {
      from: "yuanye",
      to: "gongming",
      predicate: "collaborates_with",
      label: "技术沙龙搭档",
      note: "共同组织校友技术沙龙",
    },
    {
      from: "fengfan",
      to: "kongjia",
      predicate: "collaborates_with",
      label: "志愿活动搭档",
      note: "长期参加同一公益影像项目",
    },
    {
      from: "maoxin",
      to: "xueqi",
      predicate: "collaborates_with",
      label: "招聘传播搭档",
      note: "共同筹办校友招聘会",
    },
    {
      from: "tanya",
      to: "liaoxing",
      predicate: "collaborates_with",
      label: "读书会主持搭档",
      note: "共同策划读书会访谈",
    },
    {
      from: "gongming",
      to: "xueqi",
      predicate: "collaborates_with",
      label: "招聘会技术搭档",
      note: "共同保障线上招聘会",
    },
    {
      from: "xueqi",
      to: "liaoxing",
      predicate: "friend_of",
      label: "主持人朋友",
      note: "在校友论坛主持工作中相识",
    },
    {
      from: "liaoxing",
      to: "kongjia",
      predicate: "collaborates_with",
      label: "播客摄影搭档",
      note: "共同录制校友人物播客",
    },
    {
      from: "fengfan",
      to: "maoxin",
      predicate: "collaborates_with",
      label: "前项目搭档",
      note: "曾合作校友市集项目，结束后不再搭档",
      qualifiers: { temporalStatus: "former", validFrom: "2024-11", validTo: "2025-06" },
      validity: { status: "ended", validFrom: "2024-11", validTo: "2025-06" },
    },
    {
      from: "xueqi",
      to: "kongjia",
      predicate: "knows",
      label: "可能认识",
      note: "两人在同一份公益影像志愿者名单中同框，尚未人工确认",
      pending: true,
    },
  ],
  events: [
    {
      date: "2026-09-03",
      title: "校友会秋季筹备会",
      kind: "聚会",
      people: ["yuanye", "maoxin", "xueqi"],
      place: "校友之家",
      detail: "敲定秋季活动排期与分工。",
    },
    {
      date: "2026-08-30",
      title: "播客录制",
      kind: "其它",
      people: ["liaoxing", "kongjia", "tanya"],
      place: "线上",
      detail: "录制校友职业转型专题。",
    },
    {
      date: "2026-08-23",
      title: "读书会人物访谈",
      kind: "其它",
      people: ["yuanye", "tanya", "liaoxing"],
      detail: "围绕校友职业转型录制一期播客。",
    },
    {
      date: "2026-05-01",
      precision: "month",
      title: "公益影像项目启动",
      kind: "聚会",
      people: ["fengfan", "kongjia"],
      detail: "五月启动，具体日期未记录。",
    },
  ],
  reminders: [
    { title: "联系袁野确认校友邀请名单", due: "2026-09-26", people: ["yuanye"], kind: "custom" },
    { title: "给薛琪发招聘会物料清单", due: "2026-10-08", people: ["xueqi"], kind: "custom" },
  ],
};
