import type { DemoPack } from "../types";

/**
 * 职场协作：知行实验室的科研合作网。温言是低置信人物（演示「未核验」），
 * 严可的 ended 关系演示时间性。
 */
export const workplacePack: DemoPack = {
  id: "workplace",
  group: "life",
  name: "职场协作",
  description: "同事、项目、会议与专业能力",
  example: "围绕知行实验室准备会议与项目协作",
  universe: "一所大学的研究机构「知行实验室」（模拟），主角是科研秘书视角。",
  collections: [
    {
      name: "知行实验室",
      members: [
        "jianghe",
        "xujia",
        "weilan",
        "qiuran",
        "songqing",
        "duheng",
        "yanke",
        "fangying",
        "wenyan",
        "zhangchi",
      ],
    },
  ],
  people: [
    {
      key: "jianghe",
      name: "江禾",
      profile: {
        gender: "男",
        relation: "实验室同门",
        title: "博士生",
        org: "知行实验室（模拟）",
        likes: ["机器学习"],
        contact: "demo-jianghe@example.invalid",
        closeness: 4,
        birthday: "02-27",
        metAt: "入学同导师",
        identities: [{ platform: "开源社区（模拟）", account: "jianghe-ml", alias: "禾叔" }],
      },
    },
    {
      key: "xujia",
      name: "徐嘉",
      profile: {
        gender: "女",
        relation: "课题组同门",
        title: "数据工程师",
        org: "知行实验室（模拟）",
        likes: ["数据清洗"],
        contact: "demo-xujia@example.invalid",
        closeness: 4,
        birthday: "06-30",
        metAt: "数据组例会",
      },
    },
    {
      key: "weilan",
      name: "魏岚",
      profile: {
        gender: "女",
        relation: "合作课题成员",
        title: "统计师",
        org: "知行实验室（模拟）",
        likes: ["统计分析"],
        contact: "demo-weilan@example.invalid",
        closeness: 3,
        birthday: "12-12",
        metAt: "课题立项会",
      },
    },
    {
      key: "qiuran",
      name: "邱然",
      profile: {
        gender: "男",
        relation: "导师助理",
        title: "科研秘书",
        org: "知行实验室（模拟）",
        likes: ["会议协调"],
        contact: "demo-qiuran@example.invalid",
        closeness: 3,
        birthday: "08-05",
        metAt: "入职交接",
      },
    },
    {
      key: "songqing",
      name: "宋清",
      profile: {
        gender: "女",
        relation: "论文合作者",
        title: "英文编辑",
        org: "知行实验室（模拟）",
        likes: ["学术写作"],
        contact: "demo-songqing@example.invalid",
        closeness: 4,
        birthday: "04-03",
        metAt: "论文互审",
      },
    },
    {
      key: "duheng",
      name: "杜衡",
      profile: {
        gender: "男",
        relation: "开源项目搭档",
        title: "算法工程师",
        org: "知行实验室（模拟）",
        likes: ["模型评测"],
        contact: "demo-duheng@example.invalid",
        closeness: 3,
        birthday: "10-18",
        metAt: "开源仓库协作",
      },
    },
    {
      key: "yanke",
      name: "严可",
      profile: {
        gender: "男",
        relation: "访学认识",
        title: "交互研究员",
        org: "知行实验室（模拟）",
        likes: ["可用性测试"],
        contact: "demo-yanke@example.invalid",
        closeness: 3,
        birthday: "05-15",
        metAt: "访学期间同组",
      },
    },
    {
      key: "fangying",
      name: "方莹",
      profile: {
        gender: "女",
        relation: "会议志愿者",
        title: "会务负责人",
        org: "知行实验室（模拟）",
        likes: ["学术活动组织"],
        contact: "demo-fangying@example.invalid",
        closeness: 3,
        birthday: "09-21",
        metAt: "学术会议筹备",
      },
    },
    {
      key: "wenyan",
      name: "温言",
      profile: {
        gender: "女",
        relation: "校友导师",
        title: "投资经理",
        org: "校友基金（模拟）",
        likes: ["创业辅导"],
        contact: undefined,
        closeness: 2,
        birthday: "03-03",
        metAt: "创业课程对接",
      },
      lowConfidence: true,
    },
    {
      key: "zhangchi",
      name: "章驰",
      profile: {
        gender: "男",
        relation: "课程助教",
        title: "讲师",
        org: "知行实验室（模拟）",
        likes: ["技术教学"],
        contact: "demo-zhangchi@example.invalid",
        closeness: 3,
        birthday: "11-26",
        metAt: "助教工作交接",
      },
    },
  ],
  relations: [
    {
      from: "jianghe",
      to: "xujia",
      predicate: "colleague_of",
      label: "实验室同门",
      note: "同属知行实验室数据组",
    },
    {
      from: "jianghe",
      to: "weilan",
      predicate: "collaborates_with",
      label: "论文合作者",
      note: "共同完成关系推荐评测",
    },
    {
      from: "xujia",
      to: "qiuran",
      predicate: "colleague_of",
      label: "课题组同事",
      note: "共同维护课题数据与会议安排",
    },
    {
      from: "weilan",
      to: "songqing",
      predicate: "collaborates_with",
      label: "论文合作者",
      note: "负责统计分析与英文修订",
    },
    {
      from: "qiuran",
      to: "zhangchi",
      predicate: "reports_to",
      label: "项目汇报",
      note: "邱然负责向课程讲师章驰汇报项目进度",
    },
    {
      from: "songqing",
      to: "duheng",
      predicate: "collaborates_with",
      label: "开源项目搭档",
      note: "共同维护模型评测工具",
    },
    {
      from: "duheng",
      to: "yanke",
      predicate: "collaborates_with",
      label: "用户研究搭档",
      note: "共同开展原型可用性测试",
    },
    {
      from: "yanke",
      to: "fangying",
      predicate: "knows",
      label: "学术会议认识",
      note: "在交互设计年会上相识",
    },
    {
      from: "fangying",
      to: "wenyan",
      predicate: "collaborates_with",
      label: "创业辅导搭档",
      note: "共同组织科研成果路演",
    },
    {
      from: "wenyan",
      to: "zhangchi",
      predicate: "knows",
      label: "校友导师与助教",
      note: "在创业课程中相识",
    },
    {
      from: "jianghe",
      to: "duheng",
      predicate: "collaborates_with",
      label: "算法评测搭档",
      note: "共同设计离线评测集",
    },
    {
      from: "xujia",
      to: "songqing",
      predicate: "collaborates_with",
      label: "数据写作搭档",
      note: "共同整理实验数据和论文附录",
    },
    {
      from: "yanke",
      to: "jianghe",
      predicate: "colleague_of",
      label: "前课题组同事",
      note: "曾在同一课题组，严可转组后仍保持合作",
      qualifiers: { temporalStatus: "former", validFrom: "2024-03", validTo: "2025-06" },
      validity: { status: "ended", validFrom: "2024-03", validTo: "2025-06" },
    },
    {
      from: "songqing",
      to: "wenyan",
      predicate: "knows",
      label: "可能认识",
      note: "两人在同一份基金申报名单中同框，尚未人工确认",
      pending: true,
    },
  ],
  events: [
    {
      date: "2026-09-10",
      title: "秋季课题组立项会",
      kind: "聚会",
      people: ["jianghe", "xujia", "weilan", "qiuran", "zhangchi"],
      place: "知行实验室",
      detail: "确定新学期课题分工与设备采购。",
    },
    {
      date: "2026-06-01",
      precision: "month",
      dateText: "期末季结束后",
      title: "学期末课题组聚餐",
      kind: "聚会",
      people: ["jianghe", "xujia", "qiuran", "duheng", "yanke", "fangying"],
      place: "校附近餐馆",
      detail: "学期收尾，聊了下半年安排。",
    },
    {
      date: "2026-03-18",
      title: "论文数据复核",
      kind: "帮忙",
      people: ["jianghe", "xujia", "weilan", "songqing"],
      detail: "共同复核数据清洗和统计口径。",
    },
  ],
  reminders: [
    { title: "给章驰提交助教课表", due: "2026-09-30", people: ["zhangchi"], kind: "custom" },
    { title: "回复温言关于路演的邮件", due: "2026-09-24", people: ["wenyan"], kind: "custom" },
  ],
};
