import type { DemoPack } from "../types";

/**
 * 矿石病都市（世界剧场）：以「博士」为原点的干员协作网。
 *
 * 圈层按组织划分：罗德岛本部、临光家、龙门近卫局、企鹅物流、喀兰贸易，
 * 外加一条整合运动旧档。关系的 note 标注依据（主线剧情 / 干员档案），
 * 宁少勿错。泰拉纪年映射为假想公历年（1097→2024，逐年平移），
 * 原文时间说法保留在 dateText。设计说明见 doc/research/demo-packs/arknights.md。
 */
export const arknightsPack: DemoPack = {
  id: "arknights",
  group: "world",
  name: "矿石病都市",
  description: "干员、阵营与跨阵营合作",
  example: "突发聚集感染，该找谁处理？",
  universe: "泰拉大陆（模拟）：矿石病蔓延，罗德岛制药公司穿行于各大城市之间，治病，也救人。",
  egoKey: "doctor",
  collections: [
    {
      name: "罗德岛本部",
      members: [
        "doctor",
        "amiya",
        "kaltsit",
        "blaze",
        "eyjafjalla",
        "ptilopsis",
        "silence",
        "w",
        "lappland",
        "skadi",
        "shining",
        "nightingale",
      ],
    },
    { name: "卡西米尔·临光家", members: ["nearl", "blemishine", "mlynar"] },
    { name: "龙门近卫局", members: ["chen", "hoshiguma", "swire"] },
    { name: "企鹅物流", members: ["exusiai", "texas", "mostima"] },
    { name: "喀兰贸易·谢拉格", members: ["silverash", "pramanix", "cliffheart", "matterhorn"] },
    { name: "整合运动旧档", members: ["talulah"] },
  ],
  people: [
    {
      key: "doctor",
      name: "博士",
      profile: {
        relation: "罗德岛作战指挥",
        title: "作战指挥",
        org: "罗德岛",
        metAt: "切尔诺伯格撤离时被阿米娅唤醒",
      },
      note: "失忆后仍在任的作战指挥；这份档案由凯尔希与阿米娅补录。",
    },
    {
      key: "amiya",
      name: "阿米娅",
      profile: {
        gender: "女",
        relation: "罗德岛领袖",
        title: "罗德岛公开领袖",
        org: "罗德岛",
        likes: ["作战会议记录"],
        contact: "demo-amiya@example.invalid",
        closeness: 5,
        birthday: "12-23",
        metAt: "切尔诺伯格撤离行动",
      },
    },
    {
      key: "kaltsit",
      name: "凯尔希",
      profile: {
        gender: "女",
        relation: "医疗部负责人",
        title: "罗德岛医疗部负责人",
        org: "罗德岛",
        likes: ["临床医学", "档案管理"],
        contact: "demo-kaltsit@example.invalid",
        closeness: 4,
        metAt: "巴别塔时期旧识（博士失忆前）",
      },
      note: "官方档案未公开生日，档案里留空。",
    },
    {
      key: "blaze",
      name: "煌",
      profile: {
        gender: "女",
        relation: "精英干员",
        title: "精英干员",
        org: "罗德岛",
        likes: ["攻坚作战", "张罗聚餐"],
        contact: "demo-blaze@example.invalid",
        closeness: 4,
        metAt: "切尔诺伯格撤离行动",
      },
      note: "官方档案未公开生日，档案里留空。",
    },
    {
      key: "eyjafjalla",
      name: "艾雅法拉",
      profile: {
        gender: "女",
        relation: "术师干员",
        title: "天灾研究者",
        org: "罗德岛",
        likes: ["火山与天灾观测"],
        contact: "demo-eyjafjalla@example.invalid",
        closeness: 3,
        birthday: "10-18",
        metAt: "天灾研究合作项目",
      },
    },
    {
      key: "ptilopsis",
      name: "白面鸮",
      profile: {
        gender: "女",
        relation: "医疗干员",
        title: "医疗数据维护",
        org: "罗德岛",
        likes: ["数据归档"],
        contact: "demo-ptilopsis@example.invalid",
        closeness: 3,
        birthday: "10-06",
        metAt: "医疗部报到",
      },
      note: "前莱茵生命职员，现属罗德岛医疗部。",
    },
    {
      key: "silence",
      name: "赫默",
      profile: {
        gender: "女",
        relation: "医疗干员",
        title: "源石病研究员",
        org: "罗德岛（莱茵生命研究员）",
        likes: ["临床研究"],
        contact: "demo-silence@example.invalid",
        closeness: 3,
        birthday: "05-18",
        metAt: "罗德岛医疗合作项目",
        identities: [
          { platform: "莱茵生命研究档案（模拟）", alias: "赫默", validFrom: "2022" },
          { platform: "另一条时间线上的作战记录（模拟）", alias: "寂静赫默" },
        ],
      },
    },
    {
      key: "w",
      name: "W",
      profile: {
        gender: "女",
        relation: "战略合作干员",
        title: "爆破干员",
        org: "罗德岛（战略合作）",
        likes: ["爆破物设计"],
        contact: "demo-w@example.invalid",
        closeness: 2,
        metAt: "战略合作条款签署",
        identities: [
          {
            platform: "整合运动时期（模拟）",
            alias: "W",
            validFrom: "2023",
            validTo: "2025",
          },
          { platform: "罗德岛作战记录（模拟）", alias: "W", validFrom: "2025" },
        ],
      },
      note: "档案记载生日时本人表示遗忘，档案里留空。",
    },
    {
      key: "lappland",
      name: "拉普兰德",
      profile: {
        gender: "女",
        relation: "特别行动干员",
        title: "近卫干员",
        org: "罗德岛",
        likes: ["独自行动"],
        contact: "demo-lappland@example.invalid",
        closeness: 2,
        birthday: "11-11",
        metAt: "干员入列",
      },
      note: "出身叙拉古；对德克萨斯的执念是罗德岛茶余饭后的话题。",
    },
    {
      key: "skadi",
      name: "斯卡蒂",
      profile: {
        gender: "女",
        relation: "攻坚小队干员",
        title: "赏金猎人（罗德岛雇佣）",
        org: "罗德岛",
        likes: ["深海情报"],
        contact: "demo-skadi@example.invalid",
        closeness: 3,
        birthday: "03-07",
        metAt: "攻坚小队雇佣",
        identities: [
          { platform: "罗德岛作战记录（模拟）", alias: "斯卡蒂", validFrom: "2024" },
          { platform: "另一条时间线上的作战记录（模拟）", alias: "浊心斯卡蒂" },
        ],
      },
    },
    {
      key: "shining",
      name: "闪灵",
      profile: {
        gender: "女",
        relation: "医疗干员",
        title: "医师",
        org: "罗德岛",
        likes: ["疑难病例"],
        contact: "demo-shining@example.invalid",
        closeness: 3,
        birthday: "10-07",
        metAt: "「使徒」一同加入罗德岛",
      },
      note: "出身卡兹戴尔的萨卡兹医师，「使徒」成员。",
    },
    {
      key: "nightingale",
      name: "夜莺",
      profile: {
        gender: "女",
        relation: "医疗干员",
        title: "医师",
        org: "罗德岛",
        likes: ["查房"],
        contact: undefined,
        closeness: 2,
        birthday: "05-04",
        metAt: "「使徒」一同加入罗德岛",
      },
      note: "「使徒」成员，在罗德岛接受治疗并提供医疗支援；联系方式由闪灵代为转达。",
    },
    {
      key: "nearl",
      name: "临光",
      profile: {
        gender: "女",
        relation: "重装干员",
        title: "重装干员",
        org: "罗德岛",
        likes: ["骑士长枪"],
        contact: "demo-nearl@example.invalid",
        closeness: 3,
        birthday: "04-23",
        metAt: "「使徒」一同加入罗德岛",
        identities: [
          {
            platform: "卡西米尔骑士竞技（模拟）",
            alias: "耀骑士",
            validFrom: "2021",
            validTo: "2023",
          },
          { platform: "罗德岛作战记录（模拟）", alias: "临光", validFrom: "2023" },
        ],
      },
      note: "全名玛嘉烈·临光：早年是卡西米尔的「耀骑士」，离开竞技场后随「使徒」加入罗德岛。",
    },
    {
      key: "blemishine",
      name: "瑕光",
      profile: {
        gender: "女",
        relation: "重装干员",
        title: "重装干员",
        org: "罗德岛",
        likes: ["机车改装"],
        contact: "demo-blemishine@example.invalid",
        closeness: 2,
        birthday: "07-15",
        metAt: "干员入列",
      },
      note: "全名玛莉娅·临光，临光的妹妹；为与姐姐共同行动加入罗德岛。",
    },
    {
      key: "mlynar",
      name: "玛恩纳",
      profile: {
        gender: "男",
        relation: "近卫干员",
        title: "近卫干员",
        org: "罗德岛",
        likes: ["账目核对"],
        contact: undefined,
        closeness: 2,
        birthday: "12-03",
        metAt: "干员入列",
      },
      note: "全名玛恩纳·临光，临光家前家主，玛嘉烈与玛莉娅的叔叔；不常用通讯终端，有事留言。",
    },
    {
      key: "chen",
      name: "陈",
      profile: {
        gender: "女",
        relation: "近卫局督察",
        title: "高级警司·特别督察组组长",
        org: "龙门近卫局",
        likes: ["案卷整理"],
        contact: "demo-chen@example.invalid",
        closeness: 3,
        birthday: "07-07",
        metAt: "龙门事件并肩行动",
      },
    },
    {
      key: "hoshiguma",
      name: "星熊",
      profile: {
        gender: "女",
        relation: "近卫局精英干员",
        title: "特别任务组精英干员",
        org: "龙门近卫局",
        likes: ["盾具保养"],
        contact: "demo-hoshiguma@example.invalid",
        closeness: 3,
        birthday: "01-20",
        metAt: "龙门事件协作",
      },
    },
    {
      key: "swire",
      name: "诗怀雅",
      profile: {
        gender: "女",
        relation: "近卫局高级警司",
        title: "高级警司",
        org: "龙门近卫局",
        likes: ["训练课程设计"],
        contact: "demo-swire@example.invalid",
        closeness: 2,
        birthday: "07-01",
        metAt: "受聘罗德岛训练顾问",
      },
      note: "兼任罗德岛特别合作人员与训练顾问。",
    },
    {
      key: "exusiai",
      name: "能天使",
      profile: {
        gender: "女",
        relation: "物流联络",
        title: "信使",
        org: "企鹅物流",
        likes: ["苹果派", "铳械保养"],
        contact: "demo-exusiai@example.invalid",
        closeness: 4,
        birthday: "12-24",
        metAt: "企鹅物流上门取件",
      },
    },
    {
      key: "texas",
      name: "德克萨斯",
      profile: {
        gender: "女",
        relation: "物流联络",
        title: "信使",
        org: "企鹅物流",
        likes: ["安静"],
        contact: "demo-texas@example.invalid",
        closeness: 3,
        birthday: "06-01",
        metAt: "驻罗德岛联络期间",
      },
      note: "兼任企鹅物流驻罗德岛联络人员。",
    },
    {
      key: "mostima",
      name: "莫斯提马",
      profile: {
        gender: "女",
        relation: "资深信使",
        title: "资深信使",
        org: "企鹅物流",
        likes: ["钟表"],
        contact: undefined,
        closeness: 2,
        birthday: "12-12",
        metAt: "捎口信时认识",
      },
      note: "总是单独行动，联系方式没留，有事靠同事捎口信。",
    },
    {
      key: "silverash",
      name: "银灰",
      profile: {
        gender: "男",
        relation: "战略合作伙伴",
        title: "喀兰贸易董事长",
        org: "喀兰贸易",
        likes: ["商务谈判", "雪山徒步"],
        contact: "demo-silverash@example.invalid",
        closeness: 3,
        birthday: "02-15",
        metAt: "战略合作谈判",
      },
      note: "本名恩希欧迪斯，谢拉格希瓦艾什家族族长。",
    },
    {
      key: "pramanix",
      name: "初雪",
      profile: {
        gender: "女",
        relation: "谢拉格圣女",
        title: "喀兰圣女",
        org: "谢拉格蔓珠院",
        likes: ["经文抄写"],
        contact: "demo-pramanix@example.invalid",
        closeness: 2,
        birthday: "02-13",
        metAt: "谢拉格公务往来",
      },
      note: "银灰的妹妹；因就任圣女一事与兄长疏远。",
    },
    {
      key: "cliffheart",
      name: "崖心",
      profile: {
        gender: "女",
        relation: "行动干员",
        title: "登山与攀岩专家",
        org: "罗德岛",
        likes: ["登山"],
        contact: "demo-cliffheart@example.invalid",
        closeness: 3,
        birthday: "11-28",
        metAt: "干员入列",
      },
      note: "本名恩希亚，希瓦艾什家三兄妹的小妹；在罗德岛行动，也替兄长传话。",
    },
    {
      key: "matterhorn",
      name: "角峰",
      profile: {
        gender: "男",
        relation: "喀兰贸易卫士",
        title: "卫士（外派罗德岛）",
        org: "喀兰贸易",
        likes: ["护卫勤务"],
        contact: "demo-matterhorn@example.invalid",
        closeness: 2,
        birthday: "05-19",
        metAt: "外派罗德岛报到",
      },
      note: "自银灰少年时便担任希瓦艾什家侍卫，称他「老爷」。",
    },
    {
      key: "talulah",
      name: "塔露拉",
      profile: {
        gender: "女",
        relation: "整合运动前领袖",
        title: "整合运动前领袖",
        org: "整合运动（已解体）",
        contact: undefined,
        closeness: 1,
        birthday: "01-09",
        metAt: "主线剧情中的对手",
      },
      note: "主线剧情第八章后移交罗德岛看护，档案由医疗部保管；生日来自官方档案序列。",
    },
  ],
  relations: [
    // 罗德岛核心：决策层与医疗部。
    {
      from: "doctor",
      to: "amiya",
      predicate: "colleague_of",
      label: "罗德岛核心",
      note: "主线剧情：切尔诺伯格撤离时阿米娅唤醒失忆的博士，此后共同指挥作战",
    },
    {
      from: "amiya",
      to: "doctor",
      predicate: "admires",
      label: "信赖的指挥",
      note: "主线剧情：作战会议上阿米娅习惯听取博士的意见后再做决定",
    },
    {
      from: "doctor",
      to: "kaltsit",
      predicate: "colleague_of",
      label: "决策层老同事",
      note: "巴别塔时期旧识；凯尔希交代任务时话不多，但都很关键",
    },
    {
      from: "amiya",
      to: "kaltsit",
      predicate: "colleague_of",
      label: "罗德岛决策层",
      note: "主线剧情：两人共同主持罗德岛的日常决策",
    },
    {
      from: "silence",
      to: "kaltsit",
      predicate: "reports_to",
      label: "医疗部汇报线",
      note: "凯尔希负责罗德岛医疗部，赫默向她汇报战场医疗安排",
    },
    {
      from: "ptilopsis",
      to: "kaltsit",
      predicate: "reports_to",
      label: "医疗部汇报线",
      note: "白面鸮在医疗数据维护上向凯尔希汇报",
    },
    {
      from: "silence",
      to: "ptilopsis",
      predicate: "colleague_of",
      label: "莱茵生命老同事",
      note: "两人同出自莱茵生命，到罗德岛后继续搭档",
    },
    {
      from: "kaltsit",
      to: "blaze",
      predicate: "colleague_of",
      label: "巴别塔老班底",
      note: "煌自巴别塔时期起跟随凯尔希执行任务",
    },
    {
      from: "amiya",
      to: "blaze",
      predicate: "colleague_of",
      label: "攻坚战术核心",
      note: "档案：煌是攻坚战战术核心之一，由阿米娅带领",
    },
    {
      from: "eyjafjalla",
      to: "doctor",
      predicate: "knows",
      label: "天灾研究对接",
      note: "艾雅法拉定期向博士提交天灾观测简报",
    },
    {
      from: "skadi",
      to: "doctor",
      predicate: "colleague_of",
      label: "攻坚小队雇佣",
      note: "档案：斯卡蒂现为罗德岛雇佣，在攻坚小队供职",
    },
    {
      from: "w",
      to: "kaltsit",
      predicate: "knows",
      label: "战略合作条款",
      note: "档案：经凯尔希亲自交涉，W 与罗德岛签订战略合作条款",
    },
    {
      from: "w",
      to: "doctor",
      predicate: "colleague_of",
      label: "合作干员",
      note: "W 以战略合作身份参与罗德岛行动；意见很多，活也干得漂亮",
    },
    {
      from: "lappland",
      to: "doctor",
      predicate: "colleague_of",
      label: "特别行动干员",
      note: "档案：拉普兰德作为近卫干员提供特别行动服务",
    },
    {
      from: "lappland",
      to: "texas",
      predicate: "knows",
      label: "追寻行踪",
      note: "据罗德岛内部传闻，拉普兰德一直在追查德克萨斯的下落，德克萨斯刻意回避；未经确认",
      pending: true,
    },
    {
      from: "shining",
      to: "nearl",
      predicate: "colleague_of",
      label: "「使徒」同伴",
      note: "档案：临光与闪灵、夜莺结伴成立感染者援助团体「使徒」，后一同加入罗德岛",
    },
    {
      from: "nightingale",
      to: "nearl",
      predicate: "colleague_of",
      label: "「使徒」同伴",
      note: "档案：夜莺与临光、闪灵同属「使徒」，三人一同抵达罗德岛",
    },
    {
      from: "shining",
      to: "nightingale",
      predicate: "colleague_of",
      label: "医疗搭档",
      note: "档案：闪灵把夜莺带到罗德岛接受治疗，两人长期搭档",
    },
    {
      from: "shining",
      to: "silence",
      predicate: "colleague_of",
      label: "医疗部同事",
      note: "两人同在罗德岛医疗部门工作，病例讨论会上常见",
    },
    {
      from: "w",
      to: "talulah",
      predicate: "collaborates_with",
      label: "整合运动旧合作",
      note: "档案：W 曾接受塔露拉邀请加入整合运动，后单方面撕毁合作，已脱离整合运动",
      qualifiers: { temporalStatus: "former", validFrom: "2023", validTo: "2025" },
      validity: { status: "ended", validFrom: "2023", validTo: "2025" },
    },
    {
      from: "talulah",
      to: "amiya",
      predicate: "knows",
      label: "主线对手",
      note: "主线剧情：整合运动与罗德岛对峙期间，两人多次交锋",
    },
    // 临光家：卡西米尔的三代人。
    {
      from: "nearl",
      to: "blemishine",
      predicate: "sibling_of",
      label: "姐妹",
      note: "档案：玛嘉烈与玛莉娅是临光家姐妹",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "mlynar",
      to: "nearl",
      predicate: "uncle_aunt_of",
      label: "叔叔与侄女",
      note: "档案：玛恩纳·临光是临光家前家主，玛嘉烈的叔叔",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "mlynar",
      to: "blemishine",
      predicate: "uncle_aunt_of",
      label: "叔叔与侄女",
      note: "档案：叔叔照看两位侄女，也照看祖父西里尔",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "blemishine",
      to: "nearl",
      predicate: "admires",
      label: "仰慕姐姐",
      note: "档案：玛莉娅一直把「耀骑士」当作目标",
    },
    {
      from: "nearl",
      to: "doctor",
      predicate: "colleague_of",
      label: "罗德岛干员",
      note: "临光随「使徒」加入罗德岛，多次执行重装掩护任务",
    },
    {
      from: "blemishine",
      to: "doctor",
      predicate: "colleague_of",
      label: "罗德岛干员",
      note: "档案：玛莉娅为与姐姐共同行动加入罗德岛",
    },
    {
      from: "mlynar",
      to: "doctor",
      predicate: "knows",
      label: "公事往来",
      note: "玛恩纳在罗德岛近卫干员任上与博士有过几次公事往来",
    },
    // 龙门近卫局。
    {
      from: "chen",
      to: "amiya",
      predicate: "collaborates_with",
      label: "龙门事件战友",
      note: "主线剧情：陈与阿米娅在龙门事件中并肩行动",
    },
    {
      from: "chen",
      to: "doctor",
      predicate: "collaborates_with",
      label: "龙门之后的联络",
      note: "主线剧情后期起陈借调罗德岛，与博士保持公事联络",
    },
    {
      from: "chen",
      to: "hoshiguma",
      predicate: "manages",
      label: "特别督察组上司",
      note: "档案：陈是星熊的上司，两人共事已久",
    },
    {
      from: "chen",
      to: "swire",
      predicate: "colleague_of",
      label: "互相较劲的同僚",
      note: "档案：诗怀雅想接管近卫局，陈平时用严厉的眼神瞪她",
    },
    {
      from: "hoshiguma",
      to: "swire",
      predicate: "friend_of",
      label: "休班约饭的朋友",
      note: "档案：星熊与休班的诗怀雅开玩笑、一起吃饭",
    },
    {
      from: "swire",
      to: "doctor",
      predicate: "colleague_of",
      label: "训练顾问",
      note: "档案：诗怀雅作为特别合作人员受聘于罗德岛担任训练顾问",
    },
    {
      from: "hoshiguma",
      to: "doctor",
      predicate: "collaborates_with",
      label: "龙门事件协作",
      note: "主线剧情：近卫局与罗德岛在龙门事件中协作",
    },
    // 企鹅物流。
    {
      from: "exusiai",
      to: "texas",
      predicate: "colleague_of",
      label: "押运搭档",
      note: "档案：两人同属企鹅物流，常搭档执行押运",
    },
    {
      from: "mostima",
      to: "exusiai",
      predicate: "colleague_of",
      label: "拉特兰旧识",
      note: "档案：两人同出拉特兰，如今同在企鹅物流",
    },
    {
      from: "mostima",
      to: "texas",
      predicate: "colleague_of",
      label: "同事",
      note: "同在企鹅物流，日常交集不多",
    },
    {
      from: "exusiai",
      to: "doctor",
      predicate: "knows",
      label: "上门对接",
      note: "企鹅物流与罗德岛的业务多由能天使上门对接，顺路带苹果派",
    },
    {
      from: "texas",
      to: "doctor",
      predicate: "knows",
      label: "驻罗德岛联络员",
      note: "档案：德克萨斯兼任企鹅物流驻罗德岛联络人员",
    },
    {
      from: "mostima",
      to: "doctor",
      predicate: "knows",
      label: "口信联络",
      note: "莫斯提马很少露面，偶尔托同事捎来口信",
    },
    {
      from: "chen",
      to: "texas",
      predicate: "knows",
      label: "龙门物资线",
      note: "主线剧情：龙门事件期间，近卫局与企鹅物流协作转运物资",
    },
    // 喀兰贸易与谢拉格。
    {
      from: "silverash",
      to: "doctor",
      predicate: "collaborates_with",
      label: "战略合作伙伴",
      note: "风雪过境事件后，喀兰贸易与罗德岛保持战略合作",
    },
    {
      from: "silverash",
      to: "pramanix",
      predicate: "sibling_of",
      label: "疏远的兄妹",
      note: "档案：初雪因就任圣女一事与兄长决裂，如今除公开场合几乎不交流",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "silverash",
      to: "cliffheart",
      predicate: "sibling_of",
      label: "兄妹",
      note: "档案：银灰、初雪、崖心（恩希亚）是希瓦艾什家三兄妹",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "pramanix",
      to: "cliffheart",
      predicate: "sibling_of",
      label: "姐妹",
      note: "档案：三兄妹因初雪就任圣女而往来变少",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "cliffheart",
      to: "doctor",
      predicate: "colleague_of",
      label: "罗德岛行动干员",
      note: "崖心在罗德岛执行行动任务，也替兄长传话",
    },
    {
      from: "silverash",
      to: "matterhorn",
      predicate: "manages",
      label: "东家与侍卫",
      note: "档案：角峰自银灰少年时便担任其侍卫，称他「老爷」",
    },
    {
      from: "matterhorn",
      to: "cliffheart",
      predicate: "knows",
      label: "受托照应",
      note: "档案：银灰派角峰照应二小姐恩希亚，尽管她并不乖乖受保护",
    },
    {
      from: "matterhorn",
      to: "doctor",
      predicate: "colleague_of",
      label: "外派干员",
      note: "档案：角峰作为喀兰贸易外派人员参与罗德岛任务，行使铁卫职责",
    },
    {
      from: "silverash",
      to: "kaltsit",
      predicate: "knows",
      label: "业务往来",
      note: "喀兰贸易与罗德岛医疗部有药品贸易往来",
    },
  ],
  events: [
    {
      date: "2024-03-01",
      dateEnd: "2024-03-10",
      precision: "range",
      dateText: "切尔诺伯格事件（泰拉历1097年）",
      title: "切尔诺伯格撤离",
      kind: "其它",
      place: "切尔诺伯格",
      people: ["doctor", "amiya", "kaltsit", "blaze", "w"],
      detail: "罗德岛从骚乱中的切尔诺伯格撤出人员与物资；W 当时站在整合运动一边。",
    },
    {
      date: "2024-06-01",
      precision: "month",
      dateText: "龙门事件（泰拉历1097年）",
      title: "龙门危机",
      kind: "其它",
      place: "龙门",
      people: ["doctor", "amiya", "chen", "hoshiguma", "swire"],
      detail: "近卫局与罗德岛并肩处置城内危机；事后陈开始借调罗德岛。",
    },
    {
      date: "2025-06-01",
      precision: "year",
      dateText: "沃伦姆德事件（泰拉历1098年）",
      title: "沃伦姆德的薄暮",
      kind: "其它",
      people: ["doctor"],
      detail: "罗德岛在沃伦姆德的行动与善后记录，细节归档在医疗部。",
    },
    {
      date: "2025-09-01",
      precision: "month",
      dateText: "盐风城事件（泰拉历1098年）",
      title: "盐风城之行",
      kind: "其它",
      people: ["skadi"],
      detail: "斯卡蒂独自去盐风城调查深海威胁，带回的情报被凯尔希加了密。",
    },
    {
      date: "2025-04-01",
      precision: "month",
      dateText: "泰拉历1098年",
      title: "W 的合作谈判",
      kind: "其它",
      people: ["w", "kaltsit", "doctor"],
      detail: "凯尔希亲自交涉，W 与罗德岛签订战略合作条款。",
    },
    {
      date: "2023-07-01",
      precision: "year",
      dateText: "耀骑士最后一场骑士竞技（泰拉历1096年）",
      title: "耀骑士告别赛",
      kind: "其它",
      place: "卡西米尔",
      people: ["nearl", "blemishine", "mlynar"],
      detail: "玛嘉烈离开卡西米尔前的最后一场比赛，玛莉娅在看台上。",
    },
    {
      date: "2026-03-01",
      precision: "month",
      dateText: "卡西米尔骑士竞技（泰拉历1099年）",
      title: "玛莉娅的初阵",
      kind: "其它",
      place: "卡西米尔",
      people: ["blemishine", "mlynar"],
      detail: "玛莉娅代表临光家出战；数月后的长夜临光上，玛嘉烈重返赛场。",
    },
    {
      date: "2026-01-01",
      precision: "month",
      dateText: "谢拉格风波（泰拉历1099年冬）",
      title: "风雪过境",
      kind: "其它",
      place: "谢拉格",
      people: ["doctor", "silverash", "pramanix", "cliffheart"],
      detail: "谢拉格政局动荡；风波过后，喀兰贸易与罗德岛的合作更稳了。",
    },
    {
      date: "2020-05-01",
      precision: "year",
      dateText: "初雪就任喀兰圣女（泰拉历约1093年）",
      title: "初雪就任圣女",
      kind: "其它",
      place: "谢拉格蔓珠院",
      people: ["pramanix", "silverash", "cliffheart"],
      detail: "就任之后，三兄妹的往来就少了。",
    },
    {
      date: "2026-09-07",
      dateEnd: "2026-09-11",
      precision: "range",
      title: "干员体检周",
      kind: "帮忙",
      place: "罗德岛医疗部",
      people: ["doctor", "kaltsit", "silence", "ptilopsis", "shining", "nightingale"],
      detail: "博士帮忙核对名单，白面鸮整理数据；复查安排在月底。",
    },
    {
      date: "2026-09-12",
      title: "罗德岛甲板聚餐",
      kind: "聚会",
      place: "罗德岛甲板",
      people: ["amiya", "blaze", "exusiai", "texas", "eyjafjalla", "skadi", "lappland"],
      detail: "能天使带来两打苹果派；拉普兰德到场，德克萨斯提前离席去押运。",
    },
    {
      date: "2026-09-10",
      title: "与银灰的续约通话",
      kind: "通话",
      people: ["silverash", "doctor"],
      detail: "电话里敲定药材续约条款，约好年底在谢拉格再谈。",
    },
    {
      date: "2026-09-03",
      title: "天灾观测归档",
      kind: "帮忙",
      people: ["eyjafjalla", "doctor"],
      detail: "把上月的天灾观测数据整理成简报，交给作战会议传阅。",
    },
    {
      date: "2026-08-20",
      title: "医疗物资押运",
      kind: "帮忙",
      people: ["texas", "exusiai", "doctor"],
      detail: "企鹅物流为罗德岛承运一批医疗物资，博士随车清点。",
    },
    {
      date: "2026-08-05",
      title: "药材采购会谈",
      kind: "其它",
      place: "喀兰贸易办事处",
      people: ["silverash", "kaltsit", "doctor"],
      detail: "续签药材采购意向，银灰照例把条款谈得很细。",
    },
    {
      date: "2026-08-01",
      precision: "month",
      title: "食堂门口的等候",
      kind: "其它",
      place: "罗德岛食堂",
      people: ["lappland", "texas"],
      detail: "拉普兰德在食堂门口等到了德克萨斯；具体哪天记不清了。",
    },
    {
      date: "2026-07-30",
      title: "近卫局联席演练",
      kind: "其它",
      place: "龙门",
      people: ["chen", "hoshiguma", "swire", "doctor"],
      detail: "罗德岛与近卫局的联合演练，教官环节由诗怀雅负责。",
    },
  ],
  reminders: [
    {
      title: "给阿米娅提交本季度行动简报",
      due: "2026-09-22",
      people: ["amiya"],
      kind: "custom",
    },
    {
      title: "请德克萨斯确认下一批医疗物资的押运时间",
      due: "2026-09-26",
      people: ["texas"],
      kind: "custom",
    },
    {
      title: "与凯尔希核对体检周复查名单",
      due: "2026-09-30",
      people: ["kaltsit"],
      kind: "custom",
    },
    {
      title: "为艾雅法拉准备生日贺卡",
      due: "2026-10-12",
      people: ["eyjafjalla"],
      kind: "birthday",
    },
  ],
};
