import type { DemoPack } from "../types";

/**
 * 世界剧场·元素大陆：一位旅行者走遍四国后沉淀下来的关系网。
 *
 * 取材自一部开放世界冒险作品的人物设定（库内显示名「元素大陆」，
 * 界面文案不使用商标词）。人物、组织与亲缘一律按原作设定收录，
 * 依据写进每条关系的 note；同人向与推测向关系不写，或降级为 pending。
 * 剧情日期映射到 2020-2023 假想公历年排序，2026-09 的两条为演示续写。
 * 设计说明见 doc/research/demo-packs/genshin.md。
 */
export const genshinPack: DemoPack = {
  id: "genshin",
  group: "world",
  name: "元素大陆",
  description: "七国城邦与跨城协作",
  example: "要在璃月办一场灯会，找谁统筹？",
  universe: "一位走遍七国的旅行者，把蒙德、璃月、稻妻与须弥的故人都记进了这本档案。",
  egoKey: "traveler",
  collections: [
    { name: "旅途同行", members: ["traveler", "paimon"] },
    { name: "蒙德旧识", members: ["venti", "diluc", "mona"] },
    { name: "西风骑士团", members: ["jean", "lisa", "amber", "kaeya", "albedo", "klee"] },
    {
      name: "璃月港",
      members: [
        "zhongli",
        "hutao",
        "ningguang",
        "keqing",
        "beidou",
        "xiangling",
        "xingqiu",
        "chongyun",
      ],
    },
    {
      name: "稻妻",
      members: ["raiden", "yaemiko", "ayaka", "ayato", "kazuha", "yoimiya", "guyou"],
    },
    { name: "八重堂", members: ["yaemiko", "kuroda", "xingqiu"] },
    {
      name: "教令院与须弥城",
      members: ["nahida", "alhaitham", "kaveh", "nilou", "tighnari", "cyno"],
    },
  ],
  people: [
    {
      key: "traveler",
      name: "旅行者",
      profile: {
        relation: "我自己",
        title: "异世旅人",
        likes: ["记录见闻", "下厨"],
      },
      note: "主角：来自异世界的旅行者，与同胞失散后周游七国，一路把各地故人记进档案。",
    },
    {
      key: "paimon",
      name: "派蒙",
      profile: {
        relation: "同行向导",
        title: "旅伴",
        likes: ["美食巡访"],
        contact: "demo-paimon@example.invalid",
        closeness: 5,
        birthday: "06-01",
        metAt: "初到异世的那片湖畔",
      },
      note: "自旅行者初入这个世界起一路同行，是所有见闻的第一证人。",
    },
    {
      key: "jean",
      name: "琴",
      profile: {
        gender: "女",
        relation: "蒙德的旧识",
        title: "西风骑士团代理团长",
        org: "西风骑士团",
        likes: ["蒙德城巡逻"],
        contact: "demo-jean@example.invalid",
        closeness: 4,
        birthday: "03-14",
        metAt: "风魔龙危机期间的骑士团总部",
      },
    },
    {
      key: "lisa",
      name: "丽莎",
      profile: {
        gender: "女",
        relation: "骑士团图书馆的管理员",
        title: "西风骑士团图书管理员",
        org: "西风骑士团",
        likes: ["古书修复"],
        contact: "demo-lisa@example.invalid",
        closeness: 3,
        birthday: "06-09",
        metAt: "骑士团图书馆的还书窗口",
      },
    },
    {
      key: "amber",
      name: "安柏",
      profile: {
        gender: "女",
        relation: "在蒙德结识的第一位骑士",
        title: "西风骑士团侦察骑士",
        org: "西风骑士团",
        likes: ["飞行执照考核"],
        contact: "demo-amber@example.invalid",
        closeness: 4,
        birthday: "08-10",
        metAt: "初入蒙德城时的城门口",
      },
    },
    {
      key: "kaeya",
      name: "凯亚",
      profile: {
        gender: "男",
        relation: "骑兵队长",
        title: "西风骑士团骑兵队长",
        org: "西风骑士团",
        likes: ["马术"],
        contact: "demo-kaeya@example.invalid",
        closeness: 3,
        birthday: "11-30",
        metAt: "风魔龙危机期间的骑士团总部",
      },
    },
    {
      key: "albedo",
      name: "阿贝多",
      profile: {
        gender: "男",
        relation: "雪山调查的搭档",
        title: "西风骑士团调查小队队长",
        org: "西风骑士团",
        likes: ["炼金写生"],
        contact: "demo-albedo@example.invalid",
        closeness: 3,
        birthday: "09-13",
        metAt: "龙脊雪山的调查营地",
      },
    },
    {
      key: "klee",
      name: "可莉",
      profile: {
        gender: "女",
        relation: "常拉人看实验的小骑士",
        title: "西风骑士团火花骑士",
        org: "西风骑士团",
        likes: ["蹦蹦炸弹"],
        contact: "demo-klee@example.invalid",
        closeness: 4,
        birthday: "07-27",
        metAt: "蒙德城的街头",
      },
    },
    {
      key: "venti",
      name: "温迪",
      profile: {
        gender: "男",
        relation: "风花节的诗人",
        title: "吟游诗人",
        likes: ["蒲公英酒"],
        closeness: 4,
        birthday: "06-16",
        metAt: "蒙德城广场的吟游表演",
      },
      note: "居无定所的诗人，联系方式常常找不到人；档案里先留空。",
    },
    {
      key: "diluc",
      name: "迪卢克",
      profile: {
        gender: "男",
        relation: "晨曦酒庄庄主",
        title: "晨曦酒庄庄主",
        org: "晨曦酒庄",
        likes: ["夜巡"],
        contact: "demo-diluc@example.invalid",
        closeness: 3,
        birthday: "04-30",
        metAt: "风魔龙危机期间的晨曦酒庄",
      },
    },
    {
      key: "mona",
      name: "莫娜",
      profile: {
        gender: "女",
        relation: "蒙德的占星术士",
        title: "占星术士",
        likes: ["星象观测"],
        contact: "demo-mona@example.invalid",
        closeness: 2,
        birthday: "08-31",
        metAt: "蒙德城的占星委托",
      },
    },
    {
      key: "zhongli",
      name: "钟离",
      profile: {
        gender: "男",
        relation: "璃月同行的引路人",
        title: "往生堂客卿",
        org: "往生堂",
        likes: ["璃月古玩"],
        contact: "demo-zhongli@example.invalid",
        closeness: 5,
        birthday: "12-31",
        metAt: "送仙典仪筹备期间的往生堂",
        identities: [
          {
            platform: "尘世闲游（模拟）",
            alias: "岩王帝君",
            validFrom: "远古",
            validTo: "退隐之日",
          },
          { platform: "往生堂（模拟）", alias: "客卿", validFrom: "退隐之日" },
        ],
      },
      note: "璃月篇起以客卿身份同行筹备送仙诸事；不同时期以不同身份示人，是档案里身份史最完整的一位。",
      touched: true,
    },
    {
      key: "hutao",
      name: "胡桃",
      profile: {
        gender: "女",
        relation: "往生堂堂主",
        title: "往生堂第七十七代堂主",
        org: "往生堂",
        likes: ["打油诗"],
        contact: "demo-hutao@example.invalid",
        closeness: 4,
        birthday: "07-15",
        metAt: "璃月港的街角搭话",
        identities: [{ platform: "往生堂（模拟）", alias: "堂主" }],
      },
    },
    {
      key: "ningguang",
      name: "凝光",
      profile: {
        gender: "女",
        relation: "璃月七星·天权",
        title: "天权",
        org: "璃月七星",
        likes: ["群玉阁文书"],
        contact: "demo-ningguang@example.invalid",
        closeness: 4,
        birthday: "08-26",
        metAt: "璃月港危机应对期间",
      },
    },
    {
      key: "keqing",
      name: "刻晴",
      profile: {
        gender: "女",
        relation: "璃月七星·玉衡",
        title: "玉衡",
        org: "璃月七星",
        likes: ["实地巡查"],
        contact: "demo-keqing@example.invalid",
        closeness: 3,
        birthday: "11-20",
        metAt: "璃月港危机应对期间",
      },
    },
    {
      key: "beidou",
      name: "北斗",
      profile: {
        gender: "女",
        relation: "南十字船队船长",
        title: "南十字船队船长",
        org: "南十字船队",
        likes: ["远航"],
        contact: "demo-beidou@example.invalid",
        closeness: 4,
        birthday: "02-14",
        metAt: "死兆星号的甲板",
      },
      touched: true,
    },
    {
      key: "xiangling",
      name: "香菱",
      profile: {
        gender: "女",
        relation: "万民堂的厨师",
        title: "万民堂大厨",
        org: "万民堂",
        likes: ["新食材试菜"],
        contact: "demo-xiangling@example.invalid",
        closeness: 4,
        birthday: "11-09",
        metAt: "万民堂的灶台边",
      },
    },
    {
      key: "xingqiu",
      name: "行秋",
      profile: {
        gender: "男",
        relation: "飞云商会的二少爷",
        title: "飞云商会二少爷",
        org: "飞云商会",
        likes: ["武侠话本"],
        contact: "demo-xingqiu@example.invalid",
        closeness: 4,
        birthday: "09-09",
        metAt: "璃月的行事途中",
        identities: [{ platform: "八重堂（模拟）", alias: "枕玉" }],
      },
      note: "私下以笔名「枕玉」向八重堂投过稿，圈里只有编辑在追这位神秘作者。",
    },
    {
      key: "chongyun",
      name: "重云",
      profile: {
        gender: "男",
        relation: "驱邪方士",
        title: "驱邪方士",
        likes: ["冰饮"],
        contact: "demo-chongyun@example.invalid",
        closeness: 3,
        birthday: "09-07",
        metAt: "璃月的驱邪行事中",
      },
    },
    {
      key: "raiden",
      name: "雷电将军",
      profile: {
        gender: "女",
        relation: "稻妻的将军",
        title: "雷电将军",
        org: "幕府",
        likes: ["甜点心"],
        closeness: 3,
        birthday: "06-26",
        metAt: "稻妻天守阁的门外",
      },
      note: "眼狩令期间曾正面冲突，废除眼狩令后和解；没有留下日常联系方式。",
    },
    {
      key: "yaemiko",
      name: "八重神子",
      profile: {
        gender: "女",
        relation: "鸣神大社的宫司",
        title: "鸣神大社宫司·八重堂总编辑",
        org: "鸣神大社",
        likes: ["轻小说"],
        contact: "demo-yaemiko@example.invalid",
        closeness: 3,
        birthday: "06-27",
        metAt: "鸣神大社的参道",
      },
    },
    {
      key: "ayaka",
      name: "神里绫华",
      profile: {
        gender: "女",
        relation: "神里家的大小姐",
        title: "神里家大小姐",
        org: "社奉行",
        likes: ["剑道与茶道"],
        contact: "demo-ayaka@example.invalid",
        closeness: 5,
        birthday: "09-28",
        metAt: "神里家的宅邸",
      },
    },
    {
      key: "ayato",
      name: "神里绫人",
      profile: {
        gender: "男",
        relation: "神里家的家主",
        title: "社奉行·神里家家主",
        org: "社奉行",
        likes: ["茶艺"],
        contact: "demo-ayato@example.invalid",
        closeness: 3,
        birthday: "03-26",
        metAt: "社奉行的公务场合",
      },
    },
    {
      key: "kazuha",
      name: "枫原万叶",
      profile: {
        gender: "男",
        relation: "同船的浪人武士",
        title: "南十字船队船员",
        org: "南十字船队",
        likes: ["诗歌"],
        closeness: 4,
        birthday: "10-29",
        metAt: "死兆星号的甲板",
      },
      note: "稻妻出身的浪人，眼狩令后随船远行；档案里留着他与故友的一条旧关系。",
    },
    {
      key: "yoimiya",
      name: "宵宫",
      profile: {
        gender: "女",
        relation: "烟花店的店主",
        title: "长野原烟花店店主",
        org: "长野原烟花店",
        likes: ["新配方试验"],
        contact: "demo-yoimiya@example.invalid",
        closeness: 4,
        birthday: "06-21",
        metAt: "花见坂的烟花铺",
      },
    },
    {
      key: "kuroda",
      name: "黑田",
      profile: {
        gender: "男",
        relation: "八重堂的编辑",
        title: "八重堂编辑",
        org: "八重堂",
        likes: ["追稿"],
        contact: "demo-kuroda@example.invalid",
        closeness: 2,
        metAt: "花见坂的八重堂门口",
      },
      note: "常驻花见坂的编辑，多年来一直想约到匿名作者「枕玉」的新稿。",
    },
    {
      key: "nahida",
      name: "纳西妲",
      profile: {
        gender: "女",
        relation: "须弥的草神",
        title: "小吉祥草王",
        likes: ["梦境见闻"],
        contact: "demo-nahida@example.invalid",
        closeness: 5,
        birthday: "10-27",
        metAt: "花神诞祭的梦境对谈",
      },
    },
    {
      key: "alhaitham",
      name: "艾尔海森",
      profile: {
        gender: "男",
        relation: "教令院的书记官",
        title: "教令院书记官",
        org: "教令院",
        likes: ["读书"],
        contact: "demo-alhaitham@example.invalid",
        closeness: 3,
        birthday: "02-11",
        metAt: "须弥城的咖啡馆",
      },
    },
    {
      key: "kaveh",
      name: "卡维",
      profile: {
        gender: "男",
        relation: "借住朋友家的建筑师",
        title: "建筑设计师",
        likes: ["建筑设计"],
        contact: "demo-kaveh@example.invalid",
        closeness: 2,
        birthday: "07-09",
        metAt: "艾尔海森家的客厅",
      },
      note: "须弥有名的建筑师，因修缮旧宅背了债，如今借住在艾尔海森家里。",
    },
    {
      key: "nilou",
      name: "妮露",
      profile: {
        gender: "女",
        relation: "祖拜尔剧场的舞者",
        title: "祖拜尔剧场舞者",
        org: "祖拜尔剧场",
        likes: ["舞蹈"],
        contact: "demo-nilou@example.invalid",
        closeness: 3,
        birthday: "12-03",
        metAt: "祖拜尔剧场的后台",
      },
    },
    {
      key: "tighnari",
      name: "提纳里",
      profile: {
        gender: "男",
        relation: "道成林的巡林官",
        title: "道成林巡林官队长",
        org: "巡林队",
        likes: ["植物图鉴"],
        contact: "demo-tighnari@example.invalid",
        closeness: 4,
        birthday: "12-29",
        metAt: "化城郭的巡林官小屋",
      },
    },
    {
      key: "cyno",
      name: "赛诺",
      profile: {
        gender: "男",
        relation: "教令院的大风纪官",
        title: "大风纪官",
        org: "教令院",
        likes: ["七圣牌局"],
        contact: "demo-cyno@example.invalid",
        closeness: 3,
        birthday: "06-23",
        metAt: "喀万驿的路口",
      },
    },
    {
      key: "guyou",
      name: "万叶的故友",
      profile: {
        gender: "男",
        relation: "万叶的已故友人",
        title: "浪人武士",
      },
      lowConfidence: true,
      note: "取材自枫原万叶的角色故事：眼狩令期间向「无想的一刀」挑战身故的友人，姓名未能传世；档案依万叶的讲述整理。",
    },
  ],
  relations: [
    // 旅行者直接相连的各国故人。
    {
      from: "traveler",
      to: "paimon",
      predicate: "friend_of",
      label: "同行向导",
      note: "魔神任务·序章：旅行者自湖中钓起派蒙，此后一路同行",
    },
    {
      from: "traveler",
      to: "jean",
      predicate: "collaborates_with",
      label: "风魔龙危机的协作",
      note: "魔神任务·序章：与代理团长共同应对风魔龙危机",
    },
    {
      from: "traveler",
      to: "lisa",
      predicate: "knows",
      label: "图书馆的熟人",
      note: "魔神任务·序章：在骑士团图书馆查阅资料时得到丽莎协助",
    },
    {
      from: "traveler",
      to: "amber",
      predicate: "friend_of",
      label: "蒙德的向导",
      note: "魔神任务·序章：安柏是旅行者初到蒙德时结识的骑士，协助办理飞行执照",
    },
    {
      from: "traveler",
      to: "kaeya",
      predicate: "collaborates_with",
      label: "危机中的同僚",
      note: "魔神任务·序章：凯亚协助追查深渊教团的动向",
    },
    {
      from: "traveler",
      to: "albedo",
      predicate: "collaborates_with",
      label: "雪山调查搭档",
      note: "龙脊雪山事件「白垩与黑龙」：协助阿贝多完成炼金调查",
    },
    {
      from: "traveler",
      to: "klee",
      predicate: "friend_of",
      label: "一起玩闹的伙伴",
      note: "可莉语音「关于旅行者」：把旅行者当作一起看火花实验的伙伴",
    },
    {
      from: "traveler",
      to: "venti",
      predicate: "friend_of",
      label: "同行的诗人",
      note: "魔神任务·序章：温迪与旅行者协力平息风魔龙事件",
    },
    {
      from: "traveler",
      to: "diluc",
      predicate: "collaborates_with",
      label: "危机中的支援者",
      note: "魔神任务·序章：迪卢克在骑士团之外暗中支援风魔龙危机的解决",
    },
    {
      from: "traveler",
      to: "mona",
      predicate: "knows",
      label: "占星委托认识",
      note: "莫娜的传说任务中，因一桩占星委托与她相识",
    },
    {
      from: "traveler",
      to: "zhongli",
      predicate: "friend_of",
      label: "璃月的引路人",
      note: "魔神任务·璃月篇，钟离以客卿身份陪伴旅行者筹备送仙典仪",
    },
    {
      from: "traveler",
      to: "hutao",
      predicate: "friend_of",
      label: "往生堂的熟人",
      note: "胡桃传说任务「引蝶之章」：受邀了解往生堂的送行之道",
    },
    {
      from: "traveler",
      to: "ningguang",
      predicate: "collaborates_with",
      label: "群玉阁之战的协作",
      note: "魔神任务·璃月篇：凝光坐镇群玉阁指挥阻击漩涡之魔神",
    },
    {
      from: "traveler",
      to: "keqing",
      predicate: "collaborates_with",
      label: "七星的协作",
      note: "魔神任务·璃月篇：与七星协力应对帝君「身故」后的璃月乱局",
    },
    {
      from: "traveler",
      to: "beidou",
      predicate: "friend_of",
      label: "渡海的船主",
      note: "魔神任务·稻妻篇启程：南十字船队载旅行者渡海前往稻妻",
    },
    {
      from: "traveler",
      to: "xiangling",
      predicate: "friend_of",
      label: "灶台边的朋友",
      note: "香菱传说任务「长杓之章」：结伴寻访料理食材",
    },
    {
      from: "traveler",
      to: "xingqiu",
      predicate: "friend_of",
      label: "璃月的笔友",
      note: "容彩祭前后同行，行秋常以话本情节打趣旅途见闻",
    },
    {
      from: "traveler",
      to: "chongyun",
      predicate: "friend_of",
      label: "驱邪同行的朋友",
      note: "璃月的驱邪行事中结识，曾一同试胆除邪",
    },
    {
      from: "traveler",
      to: "raiden",
      predicate: "knows",
      label: "天守阁内外",
      note: "眼狩令期间正面冲突，眼狩令废除后和解（魔神任务·稻妻篇）",
    },
    {
      from: "traveler",
      to: "yaemiko",
      predicate: "collaborates_with",
      label: "稻妻篇的引线",
      note: "魔神任务·稻妻篇：八重神子引导旅行者介入眼狩令的纷争",
    },
    {
      from: "traveler",
      to: "ayaka",
      predicate: "friend_of",
      label: "雪鹤般的挚友",
      note: "神里绫华语音「关于旅行者」：在社奉行的公务与私下往来中都视旅行者为挚友",
    },
    {
      from: "traveler",
      to: "ayato",
      predicate: "knows",
      label: "社奉行的公务往来",
      note: "魔神任务·稻妻篇与容彩祭：神里绫人委托旅行者协助处理祭典事宜",
    },
    {
      from: "traveler",
      to: "kazuha",
      predicate: "friend_of",
      label: "同船的剑客",
      note: "同乘南十字船队渡海，在反抗眼狩令的战事中并肩",
    },
    {
      from: "traveler",
      to: "yoimiya",
      predicate: "friend_of",
      label: "烟花铺的朋友",
      note: "宵宫传说任务「琉金之章」：协助烟花店筹备祭典",
    },
    {
      from: "traveler",
      to: "nahida",
      predicate: "friend_of",
      label: "梦境中的对谈者",
      note: "魔神任务·须弥篇：与纳西妲协力粉碎贤者的造神计划",
    },
    {
      from: "traveler",
      to: "alhaitham",
      predicate: "collaborates_with",
      label: "解救行动的策划者",
      note: "魔神任务·须弥篇：与艾尔海森等人策划并执行解救小吉祥草王的行动",
    },
    {
      from: "traveler",
      to: "kaveh",
      predicate: "knows",
      label: "艾尔海森家的客人",
      note: "在艾尔海森家中相识，卡维常抱怨同住的种种",
    },
    {
      from: "traveler",
      to: "nilou",
      predicate: "knows",
      label: "剧场后台的熟人",
      note: "花神诞祭的循环梦境中结识，此后保持往来",
    },
    {
      from: "traveler",
      to: "tighnari",
      predicate: "friend_of",
      label: "化城郭的东道主",
      note: "魔神任务·须弥篇：初入须弥时在化城郭受到提纳里照料",
    },
    {
      from: "traveler",
      to: "cyno",
      predicate: "collaborates_with",
      label: "归队的大风纪官",
      note: "魔神任务·须弥篇：赛诺回归教令院后共同行动",
    },
    // 西风骑士团的组织结构与蒙德人际。
    {
      from: "lisa",
      to: "jean",
      predicate: "reports_to",
      label: "汇报给代理团长",
      note: "西风骑士团编制：图书管理员丽莎向代理团长琴汇报",
    },
    {
      from: "amber",
      to: "jean",
      predicate: "reports_to",
      label: "汇报给代理团长",
      note: "西风骑士团编制：侦察骑士安柏向代理团长琴汇报",
    },
    {
      from: "kaeya",
      to: "jean",
      predicate: "reports_to",
      label: "汇报给代理团长",
      note: "西风骑士团编制：骑兵队长凯亚向代理团长琴汇报",
    },
    {
      from: "albedo",
      to: "jean",
      predicate: "reports_to",
      label: "汇报给代理团长",
      note: "西风骑士团编制：调查小队队长阿贝多向代理团长琴汇报",
    },
    {
      from: "jean",
      to: "klee",
      predicate: "manages",
      label: "照看与管教",
      note: "琴语音「关于可莉」：可莉闯祸后由琴负责管教与善后",
    },
    {
      from: "albedo",
      to: "klee",
      predicate: "knows",
      label: "照看可莉的师兄",
      note: "角色故事：可莉之母爱丽丝将其托付给骑士团，阿贝多负责照看",
    },
    {
      from: "kaeya",
      to: "diluc",
      predicate: "sibling_of",
      label: "义兄弟",
      note: "角色故事：凯亚幼年被迪卢克之父克利普斯收养，两人以兄弟相称",
      qualifiers: { lineage: "unknown" },
    },
    {
      from: "diluc",
      to: "jean",
      predicate: "colleague_of",
      label: "前骑士团同僚",
      note: "角色故事：迪卢克曾任西风骑士团骑兵队长，父亲离世后退出骑士团",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended" },
    },
    {
      from: "venti",
      to: "zhongli",
      predicate: "knows",
      label: "魔神战争的旧识",
      note: "双方角色语音互有提及：两位旧神在魔神战争年代即相识",
    },
    // 璃月港。
    {
      from: "zhongli",
      to: "hutao",
      predicate: "colleague_of",
      label: "客卿与堂主",
      note: "魔神任务·璃月篇：堂主胡桃聘请钟离担任往生堂客卿",
    },
    {
      from: "ningguang",
      to: "keqing",
      predicate: "colleague_of",
      label: "七星同僚",
      note: "璃月七星编制：天权凝光与玉衡刻晴同殿议事",
    },
    {
      from: "ningguang",
      to: "beidou",
      predicate: "collaborates_with",
      label: "群玉阁之战的协作",
      note: "魔神任务·璃月篇：南十字船队应七星之邀参战阻击漩涡之魔神",
    },
    {
      from: "keqing",
      to: "beidou",
      predicate: "knows",
      label: "听闻其船队",
      note: "推断依据：刻晴听闻南十字船队可护送抢险物资，尚未正式接洽",
      pending: true,
    },
    {
      from: "xiangling",
      to: "beidou",
      predicate: "knows",
      label: "船队的老主顾",
      note: "北斗角色故事：新出师的小厨娘香菱被船队会计带上船，为船队做过饭",
    },
    {
      from: "xingqiu",
      to: "chongyun",
      predicate: "friend_of",
      label: "总角之交",
      note: "双方角色语音互提：行秋与重云是从小一起长大的挚友",
    },
    {
      from: "xiangling",
      to: "xingqiu",
      predicate: "knows",
      label: "饭局三人组",
      note: "海灯节行事记录：香菱、行秋、重云常在璃月港的同一张饭桌上出现",
    },
    {
      from: "xiangling",
      to: "chongyun",
      predicate: "knows",
      label: "饭局三人组",
      note: "海灯节行事记录：香菱、行秋、重云常在璃月港的同一张饭桌上出现",
    },
    {
      from: "hutao",
      to: "xiangling",
      predicate: "knows",
      label: "护送过的厨师",
      note: "海灯节行事记录：饭局散后胡桃顺路护送香菱一行回万民堂",
    },
    // 稻妻。
    {
      from: "raiden",
      to: "yaemiko",
      predicate: "friend_of",
      label: "五百年旧识",
      note: "角色故事：八重神子是将军数百年间少数的挚友",
    },
    {
      from: "ayato",
      to: "ayaka",
      predicate: "sibling_of",
      label: "神里家兄妹",
      note: "角色故事：绫人为兄、绫华为妹，共掌社奉行事务",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "ayato",
      to: "ayaka",
      predicate: "colleague_of",
      label: "社奉行同僚",
      note: "社奉行编制：家主绫人与大小姐绫华同掌社奉行事务",
    },
    {
      from: "yoimiya",
      to: "ayaka",
      predicate: "knows",
      label: "烟花会的委托方",
      note: "宵宫角色故事：初任店长的烟花会上，神里绫华曾代表神里家叮嘱烟花事宜",
    },
    {
      from: "yoimiya",
      to: "ayato",
      predicate: "knows",
      label: "烟花公务往来",
      note: "宵宫传说任务：与神里绫人在祭典烟花事务上有往来",
    },
    {
      from: "beidou",
      to: "kazuha",
      predicate: "manages",
      label: "船长与船员",
      note: "万叶角色资料：栖身南十字船队，是北斗船上的一名船员",
    },
    {
      from: "kazuha",
      to: "guyou",
      predicate: "friend_of",
      label: "已故的挚友",
      note: "万叶角色故事：故友在眼狩令期间向「无想的一刀」挑战身故，万叶带着他的神之眼离乡远行",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended" },
    },
    // 八重堂。
    {
      from: "yaemiko",
      to: "kuroda",
      predicate: "manages",
      label: "总编辑与编辑",
      note: "八重堂编制：宫司八重神子兼任总编辑，黑田是其麾下编辑",
    },
    {
      from: "kuroda",
      to: "xingqiu",
      predicate: "knows",
      label: "追稿的作者",
      note: "每日委托「八重堂的邀约」：编辑追访的匿名作者「枕玉」即行秋笔名",
    },
    // 教令院与须弥。
    {
      from: "cyno",
      to: "tighnari",
      predicate: "friend_of",
      label: "多年好友",
      note: "角色语音互提：赛诺常在化城郭落脚，与提纳里互相惦记",
    },
    {
      from: "cyno",
      to: "kaveh",
      predicate: "knows",
      label: "聚餐之交",
      note: "教令院行事记录：赛诺曾带卡维去化城郭聚餐，听他抱怨室友",
    },
    {
      from: "kaveh",
      to: "alhaitham",
      predicate: "roommate_of",
      label: "同住的室友",
      note: "角色故事：卡维因修缮旧宅负债，借住在艾尔海森家中",
    },
    {
      from: "kaveh",
      to: "alhaitham",
      predicate: "classmate_of",
      label: "教令院校友",
      note: "角色故事：求学期间因跨学院课题结识，卡维是艾尔海森的学长",
    },
    {
      from: "nahida",
      to: "alhaitham",
      predicate: "colleague_of",
      label: "改制后的共事",
      note: "魔神任务·须弥篇结局：艾尔海森短暂出任代理大贤者，与纳西妲共事",
    },
    {
      from: "nahida",
      to: "nilou",
      predicate: "knows",
      label: "花神诞祭的舞者",
      note: "魔神任务·须弥篇结局：祭典复办，妮露献上花之舞，纳西妲珍视这份表演",
    },
  ],
  events: [
    {
      date: "2020-09-28",
      dateEnd: "2020-10-20",
      precision: "range",
      title: "风魔龙危机",
      kind: "其它",
      place: "蒙德",
      people: ["traveler", "paimon", "venti", "jean", "diluc", "amber", "lisa", "kaeya"],
      detail: "魔神任务·序章：风魔龙被深渊之力侵蚀，温迪与旅行者协力净化，骑士团在外围策应。",
    },
    {
      date: "2020-12-23",
      title: "龙脊雪山的炼金调查",
      kind: "帮忙",
      place: "龙脊雪山",
      people: ["traveler", "paimon", "albedo"],
      detail: "「白垩与黑龙」：协助阿贝多调查雪山异常，取回实验材料。",
    },
    {
      date: "2021-02-10",
      dateText: "海灯节前夜",
      title: "璃月请仙典仪",
      kind: "其它",
      place: "璃月港玉京台",
      people: ["traveler", "paimon", "zhongli", "hutao", "ningguang", "keqing"],
      detail: "魔神任务·璃月篇：典仪生变，钟离以客卿身份为后续的送仙诸事奔走，旅行者随行。",
    },
    {
      date: "2021-03-01",
      precision: "month",
      title: "群玉阁阻击战",
      kind: "其它",
      place: "璃月港外海",
      people: ["traveler", "paimon", "ningguang", "keqing", "beidou"],
      detail: "漩涡之魔神现身港外，七星联手南十字船队将其封锁于群玉阁之下。",
    },
    {
      date: "2021-03-01",
      precision: "month",
      title: "蒙德风花节",
      kind: "聚会",
      place: "蒙德城",
      people: ["traveler", "paimon", "venti", "amber", "klee"],
      detail: "风花节期间与安柏、可莉同游，温迪在广场唱歌。",
    },
    {
      date: "2021-05-20",
      title: "万民堂试菜",
      kind: "帮忙",
      place: "万民堂",
      people: ["traveler", "paimon", "xiangling", "xingqiu", "chongyun"],
      detail: "为香菱的新菜谱试味，行秋在旁把众人反应记进他的话本素材。",
    },
    {
      date: "2021-06-12",
      title: "结伴驱邪",
      kind: "帮忙",
      place: "璃月山野",
      people: ["traveler", "paimon", "xingqiu", "chongyun"],
      detail: "随重云调查邪祟传闻，行秋半路编了个话本桥段。",
    },
    {
      date: "2021-07-21",
      title: "南十字船队渡海",
      kind: "其它",
      place: "死兆星号",
      people: ["traveler", "paimon", "beidou", "kazuha"],
      detail: "魔神任务·稻妻篇启程：搭南十字船队前往稻妻，途中听万叶讲稻妻近况。",
    },
    {
      date: "2021-08-01",
      precision: "month",
      title: "长野原烟花店的夏天",
      kind: "聚会",
      place: "稻妻城花见坂",
      people: ["traveler", "paimon", "yoimiya"],
      detail: "夏祭前夕帮宵宫分发烟花订单。",
    },
    {
      date: "2021-09-10",
      title: "眼狩令废除",
      kind: "其它",
      place: "稻妻天守阁",
      people: ["traveler", "paimon", "raiden", "yaemiko", "ayaka", "ayato", "kazuha"],
      detail: "魔神任务·稻妻篇：眼狩令废止，旅行者与将军和解，神里家开始处理神之眼的归还。",
    },
    {
      date: "2022-02-01",
      title: "海灯节灯会",
      kind: "聚会",
      place: "璃月港",
      people: ["traveler", "paimon", "zhongli", "hutao", "xiangling", "ningguang", "keqing"],
      detail: "明霄灯升空，与璃月众人在灯会夜市同游。",
    },
    {
      date: "2022-04-10",
      title: "容彩祭与五歌仙",
      kind: "聚会",
      place: "稻妻离岛",
      people: ["traveler", "paimon", "ayato", "yaemiko", "kazuha", "venti", "xingqiu"],
      detail: "容彩祭：温迪与行秋远道赴会，八重堂征文牵出五歌仙旧事。",
    },
    {
      date: "2022-08-28",
      dateEnd: "2022-09-25",
      precision: "range",
      title: "解救小吉祥草王",
      kind: "其它",
      place: "须弥",
      people: ["traveler", "paimon", "nahida", "alhaitham", "cyno", "tighnari"],
      detail: "魔神任务·须弥篇：识破虚假的花神诞祭与造神计划，众人分头行动。",
    },
    {
      date: "2022-09-30",
      title: "花神诞祭复办",
      kind: "其它",
      place: "须弥城",
      people: ["traveler", "paimon", "nahida", "nilou"],
      detail: "祭典复办，妮露在广场献上花之舞。",
    },
    {
      date: "2023-05-05",
      title: "学院夺魁赛",
      kind: "其它",
      place: "须弥城",
      people: ["traveler", "paimon", "kaveh", "alhaitham", "cyno", "tighnari", "nahida"],
      detail: "「盛典与慧业」：卡维在学院夺魁赛中夺冠，赛后众人在化城郭聚餐。",
    },
    {
      date: "2023-06-01",
      title: "派蒙的生日加餐",
      kind: "送礼",
      place: "野外营地",
      people: ["traveler", "paimon"],
      detail: "给派蒙过了个简单的生日，多点了一份她念叨很久的菜。",
    },
    {
      date: "2026-09-12",
      title: "北斗捎来的口信",
      kind: "通话",
      people: ["beidou", "traveler", "paimon"],
      detail: "（演示续写）北斗托船员捎话：十月初有北上璃月的航次，可以搭船，也能捎货。",
    },
    {
      date: "2026-09-16",
      title: "与派蒙商量灯会分工",
      kind: "其它",
      people: ["traveler", "paimon"],
      detail: "（演示续写）下次海灯节想办一场灯会：典礼流程找钟离，烟火要跨海找宵宫订。",
    },
  ],
  reminders: [
    { title: "回访派蒙提到的小吃摊", due: "2026-09-22", people: ["paimon"], kind: "custom" },
    {
      title: "为神里绫华准备生日贺礼",
      due: "2026-09-28",
      people: ["ayaka"],
      kind: "birthday",
    },
    {
      title: "把北斗引荐给刻晴",
      due: "2026-09-30",
      people: ["keqing", "beidou"],
      kind: "custom",
    },
    {
      title: "确认海灯节烟花的海运档期",
      due: "2026-10-08",
      people: ["yoimiya", "beidou"],
      kind: "custom",
    },
  ],
};
