import type { DemoPack } from "../types";

/**
 * 魔法学院（hogwarts）：世界剧场第二库，取材自《哈利·波特》系列的虚构人物。
 *
 * 视角与口径：
 * - 以哈利（egoKey: "harry"）为原点，亲密度和 relation 措辞都从他的视角出发；
 * - 事件落在 1991-1998 七个学年的公历日期上，月/区间精度用于原著只给到
 *   季节的场合；提醒走演示日历（2026-09 下旬），生日按 MM-DD 循环；
 * - 已故角色（塞德里克、小天狼星、邓布利多、穆迪、多比、斯内普、弗雷德、
 *   卢平、唐克斯）事实照录，note 用一句"已故（时间）"收束，不展开经过；
 * - 界面文案避开商标词，只用"魔法学院"与中文译名；出处标注进 note，
 *   考证记录见 doc/research/demo-packs/hogwarts.md。
 */
export const hogwartsPack: DemoPack = {
  id: "hogwarts",
  group: "world",
  name: "魔法学院",
  description: "学院、社团与师生协作网",
  example: "想学一项新咒语，该找谁请教？",
  universe: "寄宿魔法学院的七个学年（1991-1998，模拟）：师生、球队、社团与家族交织成一张协作网。",
  egoKey: "harry",
  collections: [
    {
      name: "格兰芬多学院",
      members: [
        "harry",
        "ron",
        "hermione",
        "ginny",
        "neville",
        "fred",
        "george",
        "percy",
        "wood",
        "angelina",
        "mcgonagall",
      ],
    },
    {
      name: "凤凰社",
      members: [
        "dumbledore",
        "mcgonagall",
        "snape",
        "hagrid",
        "arthur",
        "molly",
        "sirius",
        "lupin",
        "tonks",
        "moody",
      ],
    },
    {
      name: "教职员工",
      members: ["dumbledore", "mcgonagall", "snape", "hagrid", "flitwick", "lockhart", "lupin"],
    },
    { name: "同届同学", members: ["harry", "ron", "hermione", "neville", "draco"] },
    {
      name: "魁地奇与对角巷",
      members: ["harry", "ron", "fred", "george", "wood", "angelina", "ollivander"],
    },
    {
      name: "韦斯莱一家",
      members: ["arthur", "molly", "bill", "charlie", "percy", "fred", "george", "ron", "ginny"],
    },
    { name: "邻院与来宾", members: ["luna", "cho", "cedric", "fleur"] },
    { name: "马尔福家宅", members: ["lucius", "draco", "dobby"] },
  ],
  people: [
    {
      key: "harry",
      name: "哈利·波特",
      profile: {
        gender: "男",
        relation: "视角主角",
        title: "学生 / 找球手",
        org: "格兰芬多学院",
        likes: ["实用防御术教学（D.A. 任教）", "魁地奇飞行"],
        projects: ["邓布利多军（模拟）"],
        contact: "demo-harry@example.invalid",
        birthday: "07-31",
        metAt: "本库原点：1991 年入学",
        identities: [{ platform: "魁地奇队（模拟）", alias: "找球手" }],
      },
      note: "原著人物（模拟档案）：视角主角，格兰芬多找球手；第五学年牵头 D.A. 教同学实用防御术。",
      touched: true,
    },
    {
      key: "ron",
      name: "罗恩·韦斯莱",
      profile: {
        gender: "男",
        relation: "最要好的朋友",
        title: "学生 / 守门员",
        org: "格兰芬多学院",
        likes: ["巫师棋", "魁地奇战术分析"],
        contact: "demo-ron@example.invalid",
        closeness: 5,
        birthday: "03-01",
        metAt: "1991 年开学列车",
      },
      note: "原著人物（模拟档案）：哈利在开学列车上认识的第一位挚友，同宿舍七年。",
    },
    {
      key: "hermione",
      name: "赫敏·格兰杰",
      profile: {
        gender: "女",
        relation: "最要好的朋友",
        title: "学生 / 级长",
        org: "格兰芬多学院",
        likes: ["预习与笔记整理", "图书馆检索"],
        contact: "demo-hermione@example.invalid",
        closeness: 5,
        birthday: "09-19",
        metAt: "1991 年万圣节前后的巨怪事件",
      },
      note: "原著人物（模拟档案）：三人组里的资料库，D.A. 就是她牵头张罗起来的。",
      touched: true,
    },
    {
      key: "ginny",
      name: "金妮·韦斯莱",
      profile: {
        gender: "女",
        relation: "恋人",
        title: "学生 / 追球手",
        org: "格兰芬多学院",
        likes: ["蝙蝠精咒"],
        contact: "demo-ginny@example.invalid",
        closeness: 5,
        birthday: "08-11",
        metAt: "1991 年国王十字车站",
      },
      note: "原著人物（模拟档案）：罗恩的妹妹，第六学年与哈利相恋，终章成婚。",
    },
    {
      key: "neville",
      name: "纳威·隆巴顿",
      profile: {
        gender: "男",
        relation: "同宿舍同学",
        title: "学生（草药学专长）",
        org: "格兰芬多学院",
        likes: ["草药学"],
        contact: "demo-neville@example.invalid",
        closeness: 4,
        birthday: "07-30",
        metAt: "1991 年入学分进同一宿舍",
      },
      note: "原著人物（模拟档案）：同宿舍七年的同学，草药学是他的主场。",
    },
    {
      key: "luna",
      name: "卢娜·洛夫古德",
      profile: {
        gender: "女",
        relation: "低一级的邻院朋友",
        title: "学生",
        org: "拉文克劳学院",
        likes: ["巫师趣闻与异兽传说"],
        contact: "demo-luna@example.invalid",
        closeness: 4,
        birthday: "02-13",
        metAt: "1995 年经金妮介绍",
      },
      note: "原著人物（模拟档案）：D.A. 早期成员，金妮的同级好友。",
    },
    {
      key: "cho",
      name: "张秋",
      profile: {
        gender: "女",
        relation: "仰慕过的学姐",
        title: "学生 / 找球手",
        org: "拉文克劳学院",
        likes: ["魁地奇战术"],
        contact: "demo-cho@example.invalid",
        closeness: 3,
        metAt: "1994 年春的魁地奇对抗赛",
      },
      note: "原著人物（模拟档案）：拉文克劳找球手，第四学年与塞德里克相恋。",
    },
    {
      key: "cedric",
      name: "塞德里克·迪戈里",
      profile: {
        gender: "男",
        relation: "争霸赛里的学长",
        title: "学生 / 找球手兼队长",
        org: "赫奇帕奇学院",
        likes: ["魁地奇战术", "公正待人的口碑"],
        contact: undefined,
        closeness: 3,
        metAt: "1993 年秋的魁地奇对抗赛",
      },
      note: "原著人物（模拟档案）：三强争霸赛勇士，把金蛋线索告诉过哈利。已故（1995 年夏），档案保留其在世时的事实。",
    },
    {
      key: "draco",
      name: "德拉科·马尔福",
      profile: {
        gender: "男",
        relation: "同届对头",
        title: "学生 / 找球手",
        org: "斯莱特林学院",
        likes: ["魁地奇装备（多为家里赞助）"],
        contact: "demo-draco@example.invalid",
        closeness: 2,
        birthday: "06-05",
        metAt: "1991 年对角巷的长袍店",
      },
      note: "原著人物（模拟档案）：同届的斯莱特林找球手，与哈利自长袍店初见起长期交恶。",
    },
    {
      key: "fred",
      name: "弗雷德·韦斯莱",
      profile: {
        gender: "男",
        relation: "罗恩的哥哥（击球手）",
        title: "击球手 / 把戏坊掌柜",
        org: "格兰芬多学院",
        likes: ["恶作剧道具研发"],
        projects: ["韦斯莱魔法把戏坊（模拟）"],
        contact: "demo-fred@example.invalid",
        closeness: 4,
        birthday: "04-01",
        metAt: "1991 年国王十字车站帮忙搬行李",
      },
      note: "原著人物（模拟档案）：韦斯莱双生子之一，D.A. 成员，后在对角巷 93 号开店。已故（1998 年 5 月），档案保留在世时的记录。",
    },
    {
      key: "george",
      name: "乔治·韦斯莱",
      profile: {
        gender: "男",
        relation: "罗恩的哥哥（击球手）",
        title: "击球手 / 把戏坊掌柜",
        org: "格兰芬多学院",
        likes: ["恶作剧道具研发"],
        projects: ["韦斯莱魔法把戏坊（模拟）"],
        contact: "demo-george@example.invalid",
        closeness: 4,
        birthday: "04-01",
        metAt: "1991 年国王十字车站帮忙搬行李",
      },
      note: "原著人物（模拟档案）：韦斯莱双生子之一，与弗雷德合开把戏坊，启动资金来自哈利的争霸赛奖金。",
    },
    {
      key: "percy",
      name: "珀西·韦斯莱",
      profile: {
        gender: "男",
        relation: "罗恩的哥哥（前级长）",
        title: "部长助理",
        org: "魔法部",
        likes: ["规程与文书"],
        contact: "demo-percy@example.invalid",
        closeness: 2,
        metAt: "1991 年国王十字车站（当时是级长）",
      },
      note: "原著人物（模拟档案）：三哥，1995 年夏起在魔法部与家里闹翻近三年，1998 年 5 月和解。",
    },
    {
      key: "wood",
      name: "奥利弗·伍德",
      profile: {
        gender: "男",
        relation: "魁地奇队长（已毕业）",
        title: "普德米尔联队预备队守门员",
        likes: ["魁地奇训练计划"],
        contact: "demo-wood@example.invalid",
        closeness: 3,
        metAt: "1991 年秋入队第一次训练",
      },
      note: "原著人物（模拟档案）：哈利的首任队长，毕业即与普德米尔联队预备队签约。",
    },
    {
      key: "angelina",
      name: "安吉利娜·约翰逊",
      profile: {
        gender: "女",
        relation: "魁地奇队友",
        title: "毕业生（前队长）",
        org: "格兰芬多学院",
        likes: ["魁地奇训练"],
        contact: "demo-angelina@example.invalid",
        closeness: 3,
        metAt: "1991 年秋的魁地奇训练",
      },
      note: "原著人物（模拟档案）：伍德任内的追球手，1995-96 学年接任队长并选拔了罗恩。",
    },
    {
      key: "arthur",
      name: "亚瑟·韦斯莱",
      profile: {
        gender: "男",
        relation: "罗恩的父亲",
        title: "禁止滥用麻瓜物品办公室主任",
        org: "魔法部",
        likes: ["麻瓜制品拆解"],
        contact: "demo-arthur@example.invalid",
        closeness: 4,
        metAt: "1992 年夏在陋居做客",
      },
      note: "原著人物（模拟档案）：凤凰社成员，对麻瓜器物的热情和工作一样高。",
    },
    {
      key: "molly",
      name: "莫丽·韦斯莱",
      profile: {
        gender: "女",
        relation: "罗恩的母亲",
        title: "全职主妇",
        likes: ["家宴与韦斯莱毛衣"],
        contact: "demo-molly@example.invalid",
        closeness: 5,
        metAt: "1991 年国王十字车站的闸机口",
      },
      note: "原著人物（模拟档案）：把哈利当自家孩子待，每年圣诞都寄毛衣。",
    },
    {
      key: "bill",
      name: "比尔·韦斯莱",
      profile: {
        gender: "男",
        relation: "罗恩的大哥",
        title: "古灵阁解咒员",
        org: "古灵阁",
        likes: ["破除古咒"],
        contact: "demo-bill@example.invalid",
        closeness: 3,
        metAt: "1994 年夏魁地奇世界杯营地",
      },
      note: "原著人物（模拟档案）：长子，常驻埃及的解咒员，1997 年与芙蓉完婚。",
    },
    {
      key: "charlie",
      name: "查理·韦斯莱",
      profile: {
        gender: "男",
        relation: "罗恩的二哥",
        title: "火龙保护区研究员",
        likes: ["火龙照料"],
        contact: "demo-charlie@example.invalid",
        closeness: 2,
        metAt: "1994 年夏魁地奇世界杯营地",
      },
      note: "原著人物（模拟档案）：次子，在罗马尼亚研究火龙，早年帮海格安顿过小龙诺伯。",
    },
    {
      key: "fleur",
      name: "芙蓉·德拉库尔",
      profile: {
        gender: "女",
        relation: "比尔的妻子",
        title: "古灵阁职员",
        org: "古灵阁",
        likes: ["法语", "礼仪"],
        contact: "demo-fleur@example.invalid",
        closeness: 2,
        metAt: "1994 年三强争霸赛",
      },
      note: "原著人物（模拟档案）：布斯巴顿的勇士，赛后留在伦敦，1997 年嫁入韦斯莱家。",
    },
    {
      key: "dumbledore",
      name: "阿不思·邓布利多",
      profile: {
        gender: "男",
        relation: "校长",
        title: "校长",
        org: "魔法学院",
        likes: ["教务统筹", "变形术（早年任教）"],
        contact: "demo-dumbledore@example.invalid",
        closeness: 4,
        metAt: "1991 年入学宴会",
      },
      note: "原著人物（模拟档案）：凤凰社创始人，把婴儿哈利托付给姨妈家的也是他。已故（1997 年夏），档案保留在世时的记录。",
    },
    {
      key: "mcgonagall",
      name: "米勒娃·麦格",
      profile: {
        gender: "女",
        relation: "副校长兼学院院长",
        title: "副校长 / 变形术教授",
        org: "魔法学院",
        likes: ["变形术教学"],
        contact: "demo-mcgonagall@example.invalid",
        closeness: 4,
        birthday: "10-04",
        metAt: "1991 年分院仪式前领新生入礼堂",
      },
      note: "原著人物（模拟档案）：格兰芬多院长，第一次看哈利飞行就把他荐进了球队。",
    },
    {
      key: "snape",
      name: "西弗勒斯·斯内普",
      profile: {
        gender: "男",
        relation: "魔药课教授",
        title: "魔药课教授",
        org: "魔法学院",
        likes: ["魔药煎煮", "无声咒"],
        contact: "demo-snape@example.invalid",
        closeness: 2,
        birthday: "01-09",
        metAt: "1991 年第一堂魔药课",
      },
      note: "原著人物（模拟档案）：任教魔药课十五年，第三学年曾为卢平按月煎狼毒药剂。已故（1998 年 5 月），档案保留在世时的记录。",
    },
    {
      key: "hagrid",
      name: "鲁伯·海格",
      profile: {
        gender: "男",
        relation: "猎场看守（引路人）",
        title: "猎场看守 / 保护神奇生物课教师",
        org: "魔法学院",
        likes: ["危险生物饲养", "岩皮饼"],
        contact: "demo-hagrid@example.invalid",
        closeness: 5,
        birthday: "12-06",
        metAt: "1991 年生日当天敲门送入学信",
      },
      note: "原著人物（模拟档案）：把哈利领进魔法世界的人，此后一直照看他。",
    },
    {
      key: "flitwick",
      name: "菲利乌斯·弗立维",
      profile: {
        gender: "男",
        relation: "魔咒课教授",
        title: "魔咒课教授",
        org: "魔法学院",
        likes: ["魔咒课教学", "无声咒与漂浮咒"],
        contact: "demo-flitwick@example.invalid",
        closeness: 3,
        metAt: "1991 年第一堂魔咒课",
      },
      note: "原著人物（模拟档案）：想学新咒语的默认人选，第一部里当众表扬过赫敏的漂浮咒。",
    },
    {
      key: "lockhart",
      name: "吉德罗·洛哈特",
      profile: {
        gender: "男",
        relation: "黑魔法防御术教授（第二学年）",
        title: "黑魔法防御术教授（第二学年）",
        org: "魔法学院",
        likes: ["签名售书", "自传宣传"],
        contact: "demo-lockhart@example.invalid",
        closeness: 1,
        birthday: "01-26",
        metAt: "1992 年丽痕书店签售会",
      },
      note: "原著人物（模拟档案）：畅销书作家，书里的战绩多为道听途说；请教咒语时建议先核验。",
    },
    {
      key: "sirius",
      name: "小天狼星·布莱克",
      profile: {
        gender: "男",
        relation: "教父",
        likes: ["鹰头马身兽照料", "飞行摩托"],
        contact: undefined,
        closeness: 5,
        birthday: "11-03",
        metAt: "教子名分自幼年起，1993 年当面相认",
        identities: [{ platform: "活点地图（模拟）", alias: "大脚板" }],
      },
      note: "原著人物（模拟档案）：哈利的教父，学生时代是活点地图四位作者之一，地图上署名大脚板。已故（1996 年夏），档案保留在世时的记录。",
    },
    {
      key: "lupin",
      name: "莱姆斯·卢平",
      profile: {
        gender: "男",
        relation: "黑魔法防御术教授（第三学年）",
        title: "黑魔法防御术教师（第三学年）",
        org: "魔法学院",
        likes: ["黑魔法防御术", "守护神咒入门"],
        contact: "demo-lupin@example.invalid",
        closeness: 4,
        birthday: "03-10",
        metAt: "1993 年开学列车的同一包厢",
        identities: [{ platform: "活点地图（模拟）", alias: "月亮脸" }],
      },
      note: "原著人物（模拟档案）：守护神咒就是他一句句教给哈利的；活点地图作者之一，署名月亮脸。已故（1998 年 5 月），档案保留在世时的记录。",
    },
    {
      key: "tonks",
      name: "尼法朵拉·唐克斯",
      profile: {
        gender: "女",
        relation: "凤凰社成员（傲罗）",
        title: "傲罗",
        likes: ["易容马格斯式的变形"],
        contact: "demo-tonks@example.invalid",
        closeness: 3,
        metAt: "1995 年夏格里莫广场的护送",
      },
      note: "原著人物（模拟档案）：凤凰社里最年轻的傲罗，讨厌别人叫她的本名。已故（1998 年 5 月），档案保留在世时的记录。",
    },
    {
      key: "moody",
      name: "阿拉斯托·穆迪",
      profile: {
        gender: "男",
        relation: "凤凰社成员（退役傲罗）",
        title: "退役傲罗",
        likes: ["反跟踪与反诅咒", "时刻保持警惕"],
        contact: undefined,
        closeness: 3,
        metAt: "1995 年夏护送哈利转移",
        identities: [{ platform: "凤凰社（模拟）", alias: "疯眼汉" }],
      },
      note: "原著人物（模拟档案）：第一批凤凰社成员，口头禅是时刻保持警惕。已故（1997 年夏），档案保留在世时的记录。",
    },
    {
      key: "lucius",
      name: "卢修斯·马尔福",
      profile: {
        gender: "男",
        relation: "德拉科的父亲（校董）",
        title: "学院理事（后被除名）",
        likes: ["收藏与游说"],
        contact: undefined,
        closeness: 1,
        metAt: "1992 年丽痕书店的冲突",
      },
      note: "原著人物（模拟档案）：德拉科之父，曾任学院理事；多比原是他家的家养小精灵。",
    },
    {
      key: "dobby",
      name: "多比",
      profile: {
        gender: "男",
        relation: "学院厨房的小精灵",
        title: "学院厨房帮工（自由小精灵）",
        likes: ["家务与袜子收藏"],
        contact: undefined,
        closeness: 4,
        birthday: "06-28",
        metAt: "1992 年夏不请自来的卧室访客",
      },
      note: "原著人物（模拟档案）：重获自由后在学院厨房做工，把哈利当作最好的朋友。已故（1998 年春），档案保留在世时的记录。",
    },
    {
      key: "ollivander",
      name: "加里克·奥利凡德",
      profile: {
        gender: "男",
        relation: "对角巷魔杖匠人",
        title: "魔杖匠人",
        org: "对角巷奥利凡德魔杖店",
        likes: ["魔杖木材与杖芯"],
        contact: "demo-ollivander@example.invalid",
        closeness: 3,
        metAt: "1991 年生日当天配杖",
      },
      note: "原著人物（模拟档案）：记得自己卖出的每一根魔杖，哈利的冬青木凤凰羽毛杖出自他手。",
    },
  ],
  relations: [
    // 韦斯莱家谱：七子女的父母边齐全，兄弟关系由亲属投影从共同父母推导，
    // 这里只落对演示有用的四条（双生子、罗恩-金妮、比尔-查理、珀西疏远）。
    {
      from: "arthur",
      to: "molly",
      predicate: "spouse_of",
      label: "夫妻",
      note: "原著设定：韦斯莱夫妇，育有七名子女",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
    },
    {
      from: "arthur",
      to: "bill",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：长子比尔",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "molly",
      to: "bill",
      predicate: "parent_of",
      label: "母子",
      note: "原著设定：长子比尔",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "arthur",
      to: "charlie",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：次子查理",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "molly",
      to: "charlie",
      predicate: "parent_of",
      label: "母子",
      note: "原著设定：次子查理",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "arthur",
      to: "percy",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：三子珀西",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "molly",
      to: "percy",
      predicate: "parent_of",
      label: "母子",
      note: "原著设定：三子珀西",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "arthur",
      to: "fred",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：双生子弗雷德",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "molly",
      to: "fred",
      predicate: "parent_of",
      label: "母子",
      note: "原著设定：双生子弗雷德",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "arthur",
      to: "george",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：双生子乔治",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "molly",
      to: "george",
      predicate: "parent_of",
      label: "母子",
      note: "原著设定：双生子乔治",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "arthur",
      to: "ron",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：六子罗恩",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "molly",
      to: "ron",
      predicate: "parent_of",
      label: "母子",
      note: "原著设定：六子罗恩",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "arthur",
      to: "ginny",
      predicate: "parent_of",
      label: "父女",
      note: "原著设定：幼女金妮",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "molly",
      to: "ginny",
      predicate: "parent_of",
      label: "母女",
      note: "原著设定：幼女金妮",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "bill",
      to: "charlie",
      predicate: "sibling_of",
      label: "兄弟",
      note: "原著设定：长子与次子，都在海外工作",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "fred",
      to: "george",
      predicate: "sibling_of",
      label: "双生子",
      note: "原著设定：同年同月同日生的双胞胎，愚人节生日",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "ron",
      to: "ginny",
      predicate: "sibling_of",
      label: "兄妹",
      note: "原著设定：兄妹俩只差一岁",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "percy",
      to: "ron",
      predicate: "sibling_of",
      label: "疏远期间的兄弟（后和解）",
      note: "原著第五部：珀西站在魔法部一边与家里闹翻，1995 年夏搬出陋居，1998 年 5 月和解",
      qualifiers: { lineage: "blood", temporalStatus: "former" },
      validity: { status: "ended", validFrom: "1995-07", validTo: "1998-05" },
    },
    {
      from: "lucius",
      to: "draco",
      predicate: "parent_of",
      label: "父子",
      note: "原著设定：独子德拉科",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    // 魁地奇：伍德的队长任期与安吉利娜的接任，毕业后的职业去向留一条待确认。
    {
      from: "wood",
      to: "harry",
      predicate: "manages",
      label: "队长与找球手",
      note: "原著第一部至第三部：伍德任格兰芬多队长，训练哈利这位找球手",
    },
    {
      from: "wood",
      to: "fred",
      predicate: "manages",
      label: "队长与击球手",
      note: "原著第一部至第三部：伍德带队时期的击球手",
    },
    {
      from: "wood",
      to: "george",
      predicate: "manages",
      label: "队长与击球手",
      note: "原著第一部至第三部：伍德带队时期的击球手",
    },
    {
      from: "wood",
      to: "angelina",
      predicate: "manages",
      label: "队长与追球手",
      note: "原著第一部至第三部：伍德带队时期的追球手",
    },
    {
      from: "harry",
      to: "wood",
      predicate: "reports_to",
      label: "找球手听队长安排",
      note: "原著设定：训练与战术安排都听队长的",
    },
    {
      from: "angelina",
      to: "ron",
      predicate: "manages",
      label: "新队长与守门员",
      note: "原著第五部：安吉利娜接任队长，选拔罗恩做守门员",
    },
    {
      from: "hermione",
      to: "wood",
      predicate: "knows",
      label: "待确认的引荐",
      note: "听说伍德刚与普德米尔联队预备队签约，麦格提过可引荐，尚未当面确认（原著第四部营地相遇）",
      pending: true,
    },
    // 教职员工的同僚网，弗立维是「学新咒语」的默认答案。
    {
      from: "dumbledore",
      to: "mcgonagall",
      predicate: "colleague_of",
      label: "校长与副校长",
      note: "原著设定：麦格任副校长兼格兰芬多院长，两人共事数十年",
    },
    {
      from: "dumbledore",
      to: "snape",
      predicate: "colleague_of",
      label: "校长与魔药课教授",
      note: "原著设定：斯内普任教魔药课十五年",
    },
    {
      from: "dumbledore",
      to: "hagrid",
      predicate: "colleague_of",
      label: "校长与猎场看守",
      note: "原著设定：邓布利多让海格留在城堡工作",
    },
    {
      from: "mcgonagall",
      to: "flitwick",
      predicate: "colleague_of",
      label: "老同事",
      note: "原著设定：两位教授同任教职多年",
    },
    {
      from: "snape",
      to: "lockhart",
      predicate: "colleague_of",
      label: "决斗课搭档",
      note: "原著第二部：两人共同主持决斗课，斯内普在旁拆台",
    },
    {
      from: "lupin",
      to: "snape",
      predicate: "colleague_of",
      label: "同事",
      note: "原著第三部：斯内普按月为卢平煎狼毒药剂",
    },
    {
      from: "flitwick",
      to: "hermione",
      predicate: "knows",
      label: "课堂上的得意学生",
      note: "原著第一部：魔咒课上当众表扬赫敏的漂浮咒",
      confidence: 0.93,
    },
    // 三人组与友情线。
    {
      from: "harry",
      to: "ron",
      predicate: "roommate_of",
      label: "同宿舍七年",
      note: "原著设定：从入学起住同一间宿舍",
    },
    {
      from: "harry",
      to: "neville",
      predicate: "roommate_of",
      label: "同宿舍七年",
      note: "原著设定：同宿舍（还有西莫和迪安）",
    },
    {
      from: "hermione",
      to: "harry",
      predicate: "friend_of",
      label: "三人组",
      note: "原著设定：1991 年巨怪事件后成为挚友",
    },
    {
      from: "ron",
      to: "hermione",
      predicate: "friend_of",
      label: "三人组（终章成婚）",
      note: "原著设定：挚友多年，终章结为夫妻",
    },
    {
      from: "harry",
      to: "ginny",
      predicate: "friend_of",
      label: "恋人",
      note: "原著第六部：1997 年春两人相恋，终章成婚",
    },
    {
      from: "ginny",
      to: "harry",
      predicate: "has_crush_on",
      label: "少女时期的暗恋",
      note: "原著第二至四部：金妮多年暗恋哈利，第四学年逐渐放下",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validFrom: "1992-09", validTo: "1995-06" },
    },
    {
      from: "harry",
      to: "cho",
      predicate: "has_crush_on",
      label: "仰慕",
      note: "原著第四部：圣诞舞会前邀张秋跳舞被婉拒",
    },
    {
      from: "cho",
      to: "cedric",
      predicate: "friend_of",
      label: "恋人",
      note: "原著第四部：两人相恋并同赴圣诞舞会",
    },
    {
      from: "ginny",
      to: "luna",
      predicate: "friend_of",
      label: "同级好友",
      note: "原著第五部：金妮把卢娜介绍给哈利",
    },
    {
      from: "neville",
      to: "luna",
      predicate: "friend_of",
      label: "晚会同伴",
      note: "原著第六部：纳威邀卢娜同赴圣诞晚会",
    },
    // 对头与对手。
    {
      from: "harry",
      to: "draco",
      predicate: "classmate_of",
      label: "同届对头",
      note: "原著第一部：在对角巷长袍店初识，此后长期交恶",
    },
    {
      from: "cedric",
      to: "harry",
      predicate: "friend_of",
      label: "争霸赛同僚",
      note: "原著第四部：塞德里克把金蛋线索告诉哈利，互相敬重",
    },
    {
      from: "fleur",
      to: "harry",
      predicate: "knows",
      label: "争霸赛同僚",
      note: "原著第四部：布斯巴顿代表，与哈利同为勇士",
    },
    {
      from: "bill",
      to: "fleur",
      predicate: "spouse_of",
      label: "夫妻",
      note: "原著设定：1996 年订婚，1997 年 8 月 1 日在陋居完婚",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
      validity: { status: "active", validFrom: "1997-08" },
    },
    // 凤凰社与教父。
    {
      from: "sirius",
      to: "lupin",
      predicate: "colleague_of",
      label: "老战友",
      note: "原著设定：学生时代同窗（活点地图四位作者之二），后同属两批凤凰社",
    },
    {
      from: "sirius",
      to: "moody",
      predicate: "colleague_of",
      label: "第一批凤凰社成员",
      note: "原著设定：两人同属对抗神秘人的第一批成员",
    },
    {
      from: "tonks",
      to: "moody",
      predicate: "colleague_of",
      label: "凤凰社新老成员",
      note: "原著第五部：唐克斯是刚合格的傲罗，对老前辈言听计从",
    },
    {
      from: "lupin",
      to: "tonks",
      predicate: "spouse_of",
      label: "夫妻",
      note: "原著第七部：1997 年仲夏低调成婚",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
      validity: { status: "active", validFrom: "1997-07" },
    },
    {
      from: "sirius",
      to: "harry",
      predicate: "custom",
      label: "教父与教子",
      note: "原著设定：哈利教父，1993 年相认后直接照拂；1996 年夏离世，档案保留在世时记录",
    },
    {
      from: "lupin",
      to: "harry",
      predicate: "friend_of",
      label: "忘年师友",
      note: "原著第三部：卢平以守护神咒私下辅导哈利",
    },
    {
      from: "tonks",
      to: "harry",
      predicate: "knows",
      label: "护送途中认识",
      note: "原著第五部：格里莫广场的暑假里认识，还跟着凤凰社一起大扫除",
    },
    {
      from: "moody",
      to: "harry",
      predicate: "knows",
      label: "护送人",
      note: "原著第五部：亲自带队护送哈利去格里莫广场，给他看第一批凤凰社合影",
    },
    {
      from: "arthur",
      to: "harry",
      predicate: "knows",
      label: "罗恩的父亲",
      note: "原著设定：1992 年暑假哈利在陋居做客；在魔法部管理麻瓜物品事务",
    },
    {
      from: "molly",
      to: "harry",
      predicate: "knows",
      label: "罗恩的母亲",
      note: "原著设定：待哈利如自家孩子，每年圣诞寄韦斯莱毛衣",
    },
    {
      from: "bill",
      to: "harry",
      predicate: "knows",
      label: "营地相识",
      note: "原著第四部：魁地奇世界杯营地相识",
    },
    {
      from: "charlie",
      to: "harry",
      predicate: "knows",
      label: "营地相识",
      note: "原著第四部：魁地奇世界杯营地相识；此前帮海格安排过诺伯的去处",
    },
    // 校内长辈与校外熟人。
    {
      from: "dumbledore",
      to: "harry",
      predicate: "knows",
      label: "校长",
      note: "原著设定：把婴儿哈利托付给姨妈家，入学后持续关照",
    },
    {
      from: "mcgonagall",
      to: "harry",
      predicate: "knows",
      label: "学院院长",
      note: "原著第一部：第一次看哈利飞行就把他荐入魁地奇队",
    },
    {
      from: "snape",
      to: "harry",
      predicate: "knows",
      label: "魔药课教授",
      note: "原著设定：教了哈利五年魔药课，第六学年转教黑魔法防御术",
    },
    {
      from: "lockhart",
      to: "harry",
      predicate: "knows",
      label: "第二学年的教授",
      note: "原著第二部：丽痕书店执意给哈利签名并拉他合影",
    },
    {
      from: "hagrid",
      to: "harry",
      predicate: "friend_of",
      label: "引路人与老友",
      note: "原著第一部：海格把入学信亲手送到；此后一直照看哈利",
    },
    {
      from: "dobby",
      to: "harry",
      predicate: "friend_of",
      label: "小精灵朋友",
      note: "原著第二部起：多比把哈利当作最好的朋友",
    },
    {
      from: "dobby",
      to: "lucius",
      predicate: "reports_to",
      label: "家养小精灵（已获自由）",
      note: "原著第二部：多比原侍奉马尔福家，1993 年 6 月因哈利的袜子诡计获自由",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "1993-06" },
    },
    {
      from: "ollivander",
      to: "harry",
      predicate: "knows",
      label: "魔杖匠人",
      note: "原著第一部：1991 年 7 月 31 日售出冬青木凤凰羽毛杖，他记得每一根卖出的魔杖",
    },
  ],
  events: [
    {
      date: "1991-07-31",
      title: "第一次走进对角巷",
      kind: "其它",
      people: ["harry", "hagrid", "ollivander"],
      place: "对角巷",
      detail: "海格在哈利生日当天带他购物，在奥利凡德的店里配到冬青木凤凰羽毛杖。",
    },
    {
      date: "1991-09-01",
      title: "入学分院",
      kind: "其它",
      people: ["harry", "ron", "hermione", "neville", "mcgonagall", "dumbledore"],
      place: "大礼堂",
      detail: "分院帽把哈利、罗恩、赫敏和纳威分进格兰芬多。",
    },
    {
      date: "1991-11-01",
      precision: "month",
      title: "第一场魁地奇赛",
      kind: "其它",
      people: ["harry", "wood", "mcgonagall"],
      detail: "首秀抓到金色飞贼（差点吞下去）；具体日子原著只写到十一月。",
    },
    {
      date: "1992-05-01",
      precision: "month",
      title: "护送诺伯",
      kind: "帮忙",
      people: ["harry", "ron", "hermione", "hagrid"],
      detail: "帮海格把挪威脊背龙诺伯连夜送去查理那边的接头人。",
    },
    {
      date: "1993-06-01",
      precision: "month",
      title: "多比获得自由",
      kind: "帮忙",
      people: ["harry", "dobby", "lucius"],
      detail: "学期末，哈利借日记本与袜子让多比脱离马尔福家。",
    },
    {
      date: "1994-01-05",
      dateEnd: "1994-06-20",
      precision: "range",
      title: "守护神咒私教课",
      kind: "帮忙",
      people: ["harry", "lupin"],
      detail: "第三学年春，卢平多次在晚间教哈利呼神护卫。",
    },
    {
      date: "1994-08-01",
      precision: "month",
      title: "魁地奇世界杯决赛",
      kind: "聚会",
      people: [
        "harry",
        "ron",
        "hermione",
        "ginny",
        "fred",
        "george",
        "percy",
        "arthur",
        "bill",
        "charlie",
      ],
      detail: "爱尔兰对保加利亚，全家一起扎营观赛。",
    },
    {
      date: "1994-11-24",
      dateEnd: "1995-06-24",
      precision: "range",
      title: "三强争霸赛",
      kind: "其它",
      people: ["harry", "cedric", "fleur", "hermione", "ron", "dumbledore"],
      detail: "从火焰杯选出勇士到第三个项目，历时一学年。",
    },
    {
      date: "1994-12-25",
      title: "圣诞舞会",
      kind: "约会",
      people: ["harry", "ron", "hermione", "ginny", "neville", "cho", "cedric", "fleur"],
      place: "大礼堂",
      detail: "争霸赛传统舞会：纳威邀金妮同往，塞德里克与张秋是一对，罗恩为赫敏的舞伴吃醋。",
    },
    {
      date: "1995-04-01",
      precision: "month",
      dateText: "复活节假期",
      title: "复活节假期的补习",
      kind: "其它",
      people: ["harry", "ron", "hermione"],
      detail: "假期在格兰芬多塔补作业，备战第三个项目。",
    },
    {
      date: "1995-06-01",
      precision: "month",
      title: "把奖金塞给双胞胎",
      kind: "送礼",
      people: ["harry", "fred", "george"],
      detail: "哈利把一千加隆的争霸赛奖金送给弗雷德和乔治开店。",
    },
    {
      date: "1995-08-01",
      precision: "month",
      title: "格里莫广场12号的暑假",
      kind: "聚会",
      people: ["harry", "sirius", "lupin", "tonks", "moody", "arthur", "molly", "ron", "hermione"],
      place: "格里莫广场12号",
      detail: "暑假住在教父家，赶上凤凰社重聚。",
    },
    {
      date: "1995-10-01",
      precision: "month",
      title: "D.A. 成立",
      kind: "其它",
      people: ["harry", "hermione", "ron", "ginny", "neville", "luna", "cho", "fred", "george"],
      place: "猪头旅馆",
      detail: "赫敏牵头，第一次集会定下让哈利教大家实用防御术。",
    },
    {
      date: "1996-04-01",
      precision: "month",
      title: "双子离校开店",
      kind: "其它",
      people: ["fred", "george", "ron", "harry", "ginny"],
      place: "对角巷93号",
      detail: "春学期高调离校，随后在对角巷 93 号开出韦斯莱魔法把戏坊。",
    },
    {
      date: "1996-12-25",
      title: "陋居的圣诞",
      kind: "聚会",
      people: [
        "harry",
        "ron",
        "hermione",
        "ginny",
        "arthur",
        "molly",
        "fred",
        "george",
        "bill",
        "fleur",
      ],
      place: "陋居",
      detail: "在陋居过圣诞；芙蓉已住进来筹备婚礼。",
    },
    {
      date: "1997-07-01",
      precision: "month",
      title: "卢平与唐克斯成婚",
      kind: "聚会",
      people: ["lupin", "tonks"],
      detail: "仲夏低调成婚，只通知了少数亲友。",
    },
    {
      date: "1997-08-01",
      title: "比尔与芙蓉的婚礼",
      kind: "聚会",
      people: [
        "bill",
        "fleur",
        "harry",
        "ron",
        "hermione",
        "ginny",
        "arthur",
        "molly",
        "fred",
        "george",
        "lupin",
        "tonks",
      ],
      place: "陋居",
      detail: "亲友在陋居院子相聚；当天傍晚宾客提前散场，哈利按计划转移。",
    },
  ],
  reminders: [
    { title: "给赫敏准备生日礼物", due: "2026-09-19", people: ["hermione"], kind: "birthday" },
    {
      title: "托麦格确认引荐伍德的事",
      due: "2026-09-24",
      people: ["mcgonagall", "wood"],
      kind: "custom",
    },
    { title: "向弗立维请教无声咒", due: "2026-10-08", people: ["flitwick"], kind: "custom" },
    { title: "请奥利凡德给魔杖做保养", due: "2026-10-12", people: ["ollivander"], kind: "custom" },
  ],
};
