import type { DemoPack } from "../types";

/**
 * 红楼梦（世界剧场）：贾府宗族、四大家族亲眷与仆婢网络。
 *
 * 亲属结构取自原著前八十回（依据注在每条 note，逐回可查）；
 * 生日只录原著明写者（如黛玉二月十二、宝钗正月廿一），
 * 无据可考者或省略，或标为「演示设定」。原著「朝代年纪失落无考」，
 * 事件年份统一映射到 1720 年代公历，仅保证先后排序，不当作史实。
 */
export const hongloumengPack: DemoPack = {
  id: "hongloumeng",
  group: "world",
  name: "红楼梦",
  description: "贾府宗族、四大家族与称谓推导",
  example: "从贾母看清贾府三代的亲缘网络",
  universe: "清代公府贾家的族亲与仆婢网络，取材《红楼梦》前八十回，存疑处标为演示设定或待确认。",
  egoKey: "jiabaoyu",
  collections: [
    {
      name: "贾府主子",
      members: [
        "jiamu",
        "jiazheng",
        "jiashe",
        "wangfuren",
        "zhaoyiniang",
        "jiabaoyu",
        "jiayuanchun",
        "jiatanchun",
        "jiahuan",
        "jiayingchun",
        "jiaxichun",
        "jialian",
        "wangxifeng",
        "jiazhen",
        "jiarong",
        "qinkeqing",
      ],
    },
    { name: "贾府仆婢", members: ["xiren", "qingwen", "yuanyang", "zijuan", "pingr", "xiaohong"] },
    {
      name: "四大家族亲眷",
      members: ["lindaiyu", "jiamin", "linruhai", "xuebaochai", "xueyima", "xuepan", "shixiangyun"],
    },
    {
      name: "门客与外眷",
      members: ["liulaolao", "jiayun", "beijingwang", "jiangyuhan", "zhenbaoyu", "jiayucun"],
    },
  ],
  people: [
    {
      key: "jiabaoyu",
      name: "贾宝玉",
      profile: {
        gender: "男",
        relation: "荣国府衔玉而生的公子",
        title: "怡红院主人",
        org: "荣国府",
        likes: ["诗社联句", "杂学旁收"],
        contact: "demo-jiabaoyu@example.invalid",
        metAt: "祖母膝下长大",
        identities: [{ platform: "大观园诗社（模拟）", alias: "怡红公子" }],
      },
      note: "合成档案：本库视角原点，原著第六十二回过生日但未写明日期，生日留空。",
    },
    {
      key: "jiamu",
      name: "贾母",
      profile: {
        gender: "女",
        relation: "祖母",
        title: "贾府老太太",
        org: "荣国府",
        likes: ["家宴", "听戏"],
        contact: undefined,
        closeness: 5,
        birthday: "08-03",
        metAt: "家人",
      },
      note: "史侯家小姐，贾府辈分最高的长辈；生日八月初三见第七十一回，联系由鸳鸯代管。",
    },
    {
      key: "jiazheng",
      name: "贾政",
      profile: {
        gender: "男",
        relation: "父亲",
        title: "工部员外郎",
        org: "工部",
        likes: ["诗书"],
        contact: "demo-jiazheng@example.invalid",
        closeness: 4,
        metAt: "家人",
      },
    },
    {
      key: "wangfuren",
      name: "王夫人",
      profile: {
        gender: "女",
        relation: "母亲",
        title: "荣国府当家太太",
        org: "荣国府",
        likes: ["吃斋念佛"],
        contact: "demo-wangfuren@example.invalid",
        closeness: 5,
        birthday: "03-01",
        metAt: "家人",
      },
      note: "生日三月初一见原著第六十二回探春历数诸人生日。",
    },
    {
      key: "jiashe",
      name: "贾赦",
      profile: {
        gender: "男",
        relation: "大伯父",
        title: "世袭一等将军",
        org: "荣国府",
        likes: ["古玩扇子"],
        contact: "demo-jiashe@example.invalid",
        closeness: 2,
        metAt: "家人",
      },
    },
    {
      key: "zhaoyiniang",
      name: "赵姨娘",
      profile: {
        gender: "女",
        relation: "父亲的妾室",
        title: "贾政房中姨娘",
        org: "荣国府",
        contact: undefined,
        closeness: 2,
        metAt: "府中",
      },
    },
    {
      key: "jiayuanchun",
      name: "贾元春",
      profile: {
        gender: "女",
        relation: "大姐姐（贵妃）",
        title: "凤藻宫尚书，加封贤德妃",
        org: "宫中",
        contact: undefined,
        closeness: 4,
        birthday: "01-01",
        metAt: "家人，入宫后难得一见",
      },
      note: "大年初一所生故名元春（原著第二回）；身在宫闱，档案不留联系方式。",
    },
    {
      key: "jiatanchun",
      name: "贾探春",
      profile: {
        gender: "女",
        relation: "三妹妹",
        title: "秋爽斋主人",
        org: "大观园秋爽斋",
        likes: ["书法", "起诗社"],
        contact: "demo-jiatanchun@example.invalid",
        closeness: 5,
        birthday: "03-02",
        metAt: "府中",
        identities: [{ platform: "大观园诗社（模拟）", alias: "蕉下客" }],
      },
      note: "赵姨娘所出；生日三月初二见原著第六十二回、第七十回。",
    },
    {
      key: "jiahuan",
      name: "贾环",
      profile: {
        gender: "男",
        relation: "弟弟（庶出）",
        title: "贾政房中公子",
        org: "荣国府",
        contact: undefined,
        closeness: 2,
        metAt: "府中",
      },
    },
    {
      key: "jiayingchun",
      name: "贾迎春",
      profile: {
        gender: "女",
        relation: "二姐姐",
        title: "紫菱洲主人",
        org: "大观园紫菱洲",
        likes: ["围棋"],
        contact: "demo-jiayingchun@example.invalid",
        closeness: 3,
        birthday: "02-08",
        metAt: "府中",
      },
      note: "贾赦庶出之女，生母为贾赦之妾、早亡（第七十三回邢夫人语；第二回各本异文）。生日原著无考，为演示设定。",
    },
    {
      key: "jiaxichun",
      name: "贾惜春",
      profile: {
        gender: "女",
        relation: "四妹妹",
        title: "藕榭",
        org: "大观园藕香榭",
        likes: ["绘画"],
        contact: "demo-jiaxichun@example.invalid",
        closeness: 3,
        birthday: "10-10",
        metAt: "宁府，自幼在贾母这边长大",
      },
      note: "宁府贾珍胞妹（原著第二回）；生日原著无考，为演示设定。",
    },
    {
      key: "jialian",
      name: "贾琏",
      profile: {
        gender: "男",
        relation: "琏二哥哥",
        title: "同知",
        org: "荣国府",
        likes: ["外差应酬"],
        contact: "demo-jialian@example.invalid",
        closeness: 3,
        birthday: "03-09",
        metAt: "府中",
      },
      note: "贾赦之子；生日三月初九见原著第六十二回。",
    },
    {
      key: "wangxifeng",
      name: "王熙凤",
      profile: {
        gender: "女",
        relation: "琏二嫂子，也是舅表姐",
        title: "荣国府管家奶奶",
        org: "荣国府",
        likes: ["管家理事", "说笑凑趣"],
        contact: "demo-wangxifeng@example.invalid",
        closeness: 4,
        birthday: "09-02",
        metAt: "府中",
      },
      note: "王夫人内侄女（原著第二回）；生日九月初二见第四十三回攒金庆寿。",
    },
    {
      key: "pingr",
      name: "平儿",
      profile: {
        gender: "女",
        relation: "琏二嫂子的通房丫头",
        title: "凤姐的陪嫁丫头",
        org: "荣国府",
        contact: undefined,
        closeness: 3,
        metAt: "随凤姐陪嫁进府",
      },
      note: "原著第六十二回写她与宝玉同日生辰，未写具体日期，生日留空。",
    },
    {
      key: "jiazhen",
      name: "贾珍",
      profile: {
        gender: "男",
        relation: "宁府珍大哥",
        title: "世袭三品爵威烈将军",
        org: "宁国府",
        likes: ["排场宴席"],
        contact: "demo-jiazhen@example.invalid",
        closeness: 2,
        metAt: "两府往来",
      },
    },
    {
      key: "jiarong",
      name: "贾蓉",
      profile: {
        gender: "男",
        relation: "宁府的蓉哥儿",
        title: "监生",
        org: "宁国府",
        contact: "demo-jiarong@example.invalid",
        closeness: 2,
        metAt: "两府往来",
      },
    },
    {
      key: "qinkeqing",
      name: "秦可卿",
      profile: {
        gender: "女",
        relation: "宁府的蓉大奶奶",
        title: "宁国府长房长孙媳",
        org: "宁国府",
        contact: undefined,
        closeness: 2,
        metAt: "两府往来",
      },
      note: "贾蓉之妻，原著第十三回病逝；档案保留以维系宁府一系的亲属链。",
    },
    {
      key: "lindaiyu",
      name: "林黛玉",
      profile: {
        gender: "女",
        relation: "林妹妹（姑表妹）",
        title: "潇湘馆主人",
        org: "大观园潇湘馆",
        likes: ["读书写诗"],
        contact: "demo-lindaiyu@example.invalid",
        closeness: 5,
        birthday: "02-12",
        metAt: "母亲去世后进贾府相依外祖母",
        identities: [{ platform: "大观园诗社（模拟）", alias: "潇湘妃子" }],
      },
    },
    {
      key: "jiamin",
      name: "贾敏",
      profile: {
        gender: "女",
        relation: "姑母",
        title: "林府夫人",
        org: "姑苏林府",
        contact: undefined,
        metAt: "家人",
      },
      note: "贾母之女、黛玉之母，故事开始前已故（原著第二回），只保留亲属链不录亲密度。",
    },
    {
      key: "linruhai",
      name: "林如海",
      profile: {
        gender: "男",
        relation: "姑父",
        title: "兰台寺大夫、钦差巡盐御史",
        org: "两淮盐政",
        contact: "demo-linruhai@example.invalid",
        closeness: 2,
        metAt: "家人",
      },
      note: "黛玉之父，原著第十四回病故，此前曾聘贾雨村为西宾。",
    },
    {
      key: "xuebaochai",
      name: "薛宝钗",
      profile: {
        gender: "女",
        relation: "宝姐姐（姨表姐）",
        title: "蘅芜苑主人",
        org: "大观园蘅芜苑",
        likes: ["作诗", "女红"],
        contact: "demo-xuebaochai@example.invalid",
        closeness: 5,
        birthday: "01-21",
        metAt: "随母亲、兄长进京寄居贾府",
        identities: [{ platform: "大观园诗社（模拟）", alias: "蘅芜君" }],
      },
    },
    {
      key: "xueyima",
      name: "薛姨妈",
      profile: {
        gender: "女",
        relation: "姨妈",
        title: "薛家当家太太",
        org: "薛家",
        contact: "demo-xueyima@example.invalid",
        closeness: 4,
        metAt: "进京后常来贾府走动",
      },
    },
    {
      key: "xuepan",
      name: "薛蟠",
      profile: {
        gender: "男",
        relation: "薛大哥（姨表兄）",
        title: "皇商",
        org: "薛家",
        likes: ["宴饮"],
        contact: "demo-xuepan@example.invalid",
        closeness: 2,
        birthday: "05-03",
        metAt: "随母亲进京",
      },
      note: "生日五月初三见原著第二十六回自述。",
    },
    {
      key: "shixiangyun",
      name: "史湘云",
      profile: {
        gender: "女",
        relation: "史大妹妹（隔代表亲）",
        title: "史侯家小姐",
        org: "史侯家",
        likes: ["诗社联句"],
        contact: "demo-shixiangyun@example.invalid",
        closeness: 5,
        birthday: "05-20",
        metAt: "自幼常被贾母接来住",
        identities: [{ platform: "大观园诗社（模拟）", alias: "枕霞旧友" }],
      },
      note: "贾母娘家的侄孙女；生日原著无考，为演示设定。",
    },
    {
      key: "xiren",
      name: "袭人",
      profile: {
        gender: "女",
        relation: "房里的大丫头",
        title: "怡红院首席大丫头",
        org: "荣国府",
        likes: ["针线"],
        contact: undefined,
        closeness: 4,
        metAt: "贾母房里拨来伏侍宝玉",
      },
    },
    {
      key: "qingwen",
      name: "晴雯",
      profile: {
        gender: "女",
        relation: "房里的丫头",
        title: "怡红院丫头",
        org: "荣国府",
        likes: ["针线"],
        contact: undefined,
        closeness: 4,
        metAt: "贾母房里拨来伏侍宝玉",
      },
      note: "原著第七十七回病中被逐、第七十八回宝玉作《芙蓉女儿诔》致祭。",
    },
    {
      key: "yuanyang",
      name: "鸳鸯",
      profile: {
        gender: "女",
        relation: "祖母的大丫头",
        title: "贾母房中首席大丫头",
        org: "荣国府",
        contact: undefined,
        closeness: 3,
        metAt: "贾母房中",
      },
      note: "第四十六回贾赦讨妾，她剪发明志；贾母的联系与日程由她代管。",
    },
    {
      key: "zijuan",
      name: "紫鹃",
      profile: {
        gender: "女",
        relation: "林妹妹的丫头",
        title: "潇湘馆丫头",
        org: "荣国府",
        contact: undefined,
        closeness: 3,
        birthday: "03-15",
        metAt: "贾母房中二等丫头，拨给黛玉",
      },
      note: "生日原著无考，为演示设定；第五十七回曾以「回苏州」试宝玉心意。",
    },
    {
      key: "liulaolao",
      name: "刘姥姥",
      profile: {
        gender: "女",
        relation: "王家连宗的乡下老人家",
        title: "乡间老妪",
        org: "女婿狗儿家",
        contact: undefined,
        closeness: 2,
        metAt: "秋尽冬初进城打抽丰",
      },
      note: "与王夫人娘家连宗（原著第六回），两进荣国府。",
    },
    {
      key: "jiayun",
      name: "贾芸",
      profile: {
        gender: "男",
        relation: "贾氏远房子弟",
        title: "府里种树差事的领班",
        org: "贾府西廊下",
        contact: "demo-jiayun@example.invalid",
        closeness: 2,
        birthday: "07-09",
        metAt: "进府谋差事",
      },
      note: "西廊下五嫂子之子（原著第二十四回）；生日原著无考，为演示设定。",
    },
    {
      key: "xiaohong",
      name: "小红",
      profile: {
        gender: "女",
        relation: "怡红院旧丫头，现随琏二嫂子",
        title: "凤姐房中管事丫头",
        org: "荣国府",
        contact: undefined,
        closeness: 2,
        birthday: "06-16",
        metAt: "怡红院当差",
      },
      note: "本名林红玉，林之孝之女；生日原著无考，为演示设定。",
    },
    {
      key: "beijingwang",
      name: "北静王",
      profile: {
        gender: "男",
        relation: "相与甚厚的北静王爷",
        title: "北静郡王（水溶）",
        org: "北静王府",
        likes: ["海内名士"],
        contact: "demo-beijingwang@example.invalid",
        closeness: 3,
        birthday: "11-11",
        metAt: "可卿之丧路祭初见",
      },
      note: "年未弱冠、容貌秀美（原著第十五回），曾邀宝玉常往王府；生日原著无考，为演示设定。",
    },
    {
      key: "jiangyuhan",
      name: "蒋玉菡",
      profile: {
        gender: "男",
        relation: "忠顺王府的琪官",
        title: "小旦琪官",
        org: "忠顺王府戏班",
        contact: "demo-jiangyuhan@example.invalid",
        closeness: 2,
        birthday: "08-08",
        metAt: "冯紫英家宴",
      },
      note: "第二十八回与宝玉互赠汗巾；生日原著无考，为演示设定。",
    },
    {
      key: "zhenbaoyu",
      name: "甄宝玉",
      profile: {
        gender: "男",
        relation: "金陵甄家的同名公子",
        title: "甄家公子",
        org: "金陵甄家",
        contact: undefined,
        closeness: 1,
        birthday: "04-26",
        metAt: "只在梦里见过（第五十六回）",
      },
      note: "与贾宝玉同名同貌，金陵甄家派人进京请安时彼此闻名；生日原著无考，为演示设定。",
    },
    {
      key: "jiayucun",
      name: "贾雨村",
      profile: {
        gender: "男",
        relation: "投帖认宗的贾雨村",
        title: "应天府尹",
        org: "应天府",
        contact: "demo-jiayucun@example.invalid",
        closeness: 1,
        birthday: "12-08",
        metAt: "经姑父林如海荐于贾政",
      },
      note: "曾做黛玉塾师，复职靠贾政相助（原著第二、三回）；生日原著无考，为演示设定。",
    },
  ],
  relations: [
    // 贾母一系：三代祖孙与史家亲眷。
    {
      from: "jiamu",
      to: "jiazheng",
      predicate: "parent_of",
      label: "母子",
      note: "贾母是贾政之母（第二回冷子兴演说）",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "jiamu",
      to: "jiashe",
      predicate: "parent_of",
      label: "母子",
      note: "贾母是贾赦之母（第二回）",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "jiamu",
      to: "jiamin",
      predicate: "parent_of",
      label: "母女",
      note: "贾母之女名贾敏，即黛玉之母（第二回）",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "jiamu",
      to: "jiabaoyu",
      predicate: "grandparent_of",
      label: "祖母与孙",
      note: "宝玉最得祖母疼爱（第三回）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "jiamu",
      to: "lindaiyu",
      predicate: "grandparent_of",
      label: "外祖母与外孙女",
      note: "黛玉进府即投外祖母（第三回）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "jiamu",
      to: "shixiangyun",
      predicate: "knows",
      label: "姑祖母与侄孙女",
      note: "湘云是贾母娘家的侄孙女，自幼常被接来贾府小住（第三十一回、第三十二回）",
      qualifiers: { lineage: "blood" },
    },
    // 贾政一房：父母、元配与妾室。
    {
      from: "jiazheng",
      to: "jiabaoyu",
      predicate: "parent_of",
      label: "父子",
      note: "衔玉而生的次子（第二回）",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "jiazheng",
      to: "jiayuanchun",
      predicate: "parent_of",
      label: "父女",
      note: "元春自幼由贾母教养，后入宫（第二回）",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "jiazheng",
      to: "jiatanchun",
      predicate: "parent_of",
      label: "父女",
      note: "探春为庶出，赵姨娘所生（第二回）",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "jiazheng",
      to: "jiahuan",
      predicate: "parent_of",
      label: "父子",
      note: "贾环为庶出，赵姨娘所生（第二回）",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "jiazheng",
      to: "wangfuren",
      predicate: "spouse_of",
      label: "夫妻",
      note: "王氏是贾政元配（第二回）",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
    },
    {
      from: "zhaoyiniang",
      to: "jiazheng",
      predicate: "spouse_of",
      label: "姨娘",
      note: "赵姨娘是贾政之妾，生探春、贾环（第二回、第五十五回）",
      qualifiers: { partnerRole: "concubine", lineage: "marriage" },
    },
    {
      from: "wangfuren",
      to: "jiabaoyu",
      predicate: "parent_of",
      label: "母子",
      note: "王夫人头胎所生即元春，晚年得宝玉（第二回）",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "wangfuren",
      to: "jiayuanchun",
      predicate: "parent_of",
      label: "母女",
      note: "元春为王夫人所出（第二回）",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "wangfuren",
      to: "xueyima",
      predicate: "sibling_of",
      label: "姐妹",
      note: "薛姨妈是王夫人一母胞妹（第四回护官符注）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "wangfuren",
      to: "wangxifeng",
      predicate: "uncle_aunt_of",
      label: "姑妈与侄女",
      note: "凤姐是王夫人内侄女（第二回），如今又嫁作贾家儿媳",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "jiabaoyu",
      to: "jiayuanchun",
      predicate: "sibling_of",
      label: "同母姐弟",
      note: "同为王夫人所出，元春长宝玉十余岁（第二回、第十八回）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "jiabaoyu",
      to: "jiatanchun",
      predicate: "half_sibling_of",
      label: "同父异母兄妹",
      note: "探春呼宝玉「二哥哥」（第二回、第五十五回）",
      qualifiers: { sharedParentRole: "father", lineage: "blood" },
    },
    {
      from: "jiabaoyu",
      to: "jiahuan",
      predicate: "half_sibling_of",
      label: "同父异母兄弟",
      note: "贾环与宝玉同父异母（第二回）",
      qualifiers: { sharedParentRole: "father", lineage: "blood" },
    },
    // 贾赦一房与琏凤夫妻。
    {
      from: "jiashe",
      to: "jialian",
      predicate: "parent_of",
      label: "父子",
      note: "贾琏是贾赦之子（第二回）",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "jiashe",
      to: "jiayingchun",
      predicate: "parent_of",
      label: "父女",
      note: "迎春是贾赦庶出之女，生母早亡（第七十三回邢夫人语；第二回各本异文）",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "jiashe",
      to: "jiazheng",
      predicate: "sibling_of",
      label: "兄弟",
      note: "赦为长房承袭，政居次（第二回）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "wangxifeng",
      to: "jialian",
      predicate: "spouse_of",
      label: "夫妻",
      note: "凤姐嫁贾琏，协理荣府（第二回、第三回）",
      qualifiers: { partnerRole: "wife", lineage: "marriage" },
    },
    {
      from: "pingr",
      to: "jialian",
      predicate: "spouse_of",
      label: "通房丫头",
      note: "平儿是凤姐陪嫁、贾琏之妾（第六十五回兴儿语）",
      qualifiers: { partnerRole: "concubine", lineage: "marriage" },
    },
    {
      from: "jialian",
      to: "jiabaoyu",
      predicate: "cousin_of",
      label: "堂兄弟",
      note: "赦、政两房之子，同祖兄弟（第二回）",
      qualifiers: {
        cousinBranch: "paternal_uncle",
        inverseCousinBranch: "paternal_uncle",
        lineage: "blood",
      },
    },
    {
      from: "jiabaoyu",
      to: "jiayingchun",
      predicate: "cousin_of",
      label: "堂姐弟",
      note: "迎春是宝玉大伯父贾赦之女，府中行二故称二姐姐（第二回）",
      qualifiers: {
        cousinBranch: "paternal_uncle",
        inverseCousinBranch: "paternal_uncle",
        lineage: "blood",
      },
    },
    // 王薛两家的表亲网。
    {
      from: "jiabaoyu",
      to: "xuebaochai",
      predicate: "cousin_of",
      label: "姨表姐弟",
      note: "宝钗之母是王夫人胞妹（第四回）",
      qualifiers: {
        cousinBranch: "maternal_aunt",
        inverseCousinBranch: "maternal_aunt",
        lineage: "blood",
      },
    },
    {
      from: "jiabaoyu",
      to: "xuepan",
      predicate: "cousin_of",
      label: "姨表兄弟",
      note: "薛蟠是薛姨妈之子（第四回）",
      qualifiers: {
        cousinBranch: "maternal_aunt",
        inverseCousinBranch: "maternal_aunt",
        lineage: "blood",
      },
    },
    {
      from: "jiabaoyu",
      to: "wangxifeng",
      predicate: "cousin_of",
      label: "姑舅表姐弟",
      note: "凤姐之父是王夫人之兄，自幼一处顽笑（第二回、第三回）",
      qualifiers: {
        cousinBranch: "maternal_uncle",
        inverseCousinBranch: "paternal_aunt",
        lineage: "blood",
      },
    },
    {
      from: "xueyima",
      to: "xuebaochai",
      predicate: "parent_of",
      label: "母女",
      note: "薛姨妈之女（第四回）",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "xueyima",
      to: "xuepan",
      predicate: "parent_of",
      label: "母子",
      note: "薛蟠幼年丧父，寡母教养（第四回）",
      qualifiers: { parentRole: "mother", childRole: "son", lineage: "blood" },
    },
    {
      from: "xuebaochai",
      to: "xuepan",
      predicate: "sibling_of",
      label: "兄妹",
      note: "宝钗比薛蟠小两岁（第四回）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "jiabaoyu",
      to: "shixiangyun",
      predicate: "cousin_of",
      label: "表兄妹",
      note: "湘云是贾母侄孙女，与宝玉隔一代的表亲，府中兄妹相称（第二十回、第三十一回）",
      qualifiers: {
        cousinBranch: "unspecified",
        inverseCousinBranch: "unspecified",
        lineage: "blood",
      },
    },
    // 林家一系：姑表亲的完整链。
    {
      from: "jiamin",
      to: "lindaiyu",
      predicate: "parent_of",
      label: "母女",
      note: "贾敏是黛玉之母，教女读书识字（第二回）",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "linruhai",
      to: "lindaiyu",
      predicate: "parent_of",
      label: "父女",
      note: "林如海膝下唯此一女，爱如珍宝（第二回）",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
    },
    {
      from: "jiamin",
      to: "linruhai",
      predicate: "spouse_of",
      label: "夫妻",
      note: "贾敏嫁林如海为妻（第二回）",
      qualifiers: { partnerRole: "wife", lineage: "marriage" },
    },
    {
      from: "jiabaoyu",
      to: "lindaiyu",
      predicate: "cousin_of",
      label: "姑表兄妹",
      note: "黛玉之母贾敏是宝玉之父贾政的妹妹（第二回、第三回）",
      qualifiers: {
        cousinBranch: "paternal_aunt",
        inverseCousinBranch: "maternal_uncle",
        lineage: "blood",
      },
    },
    {
      from: "lindaiyu",
      to: "xuebaochai",
      predicate: "friend_of",
      label: "金兰之友",
      note: "第四十五回「金兰契互剖金兰语」，两人并无血缘，情分胜似姐妹",
    },
    // 宁国府与宗族。
    {
      from: "jiazhen",
      to: "jiarong",
      predicate: "parent_of",
      label: "父子",
      note: "贾珍、贾蓉父子执掌宁府（第二回）",
      qualifiers: { parentRole: "father", childRole: "son", lineage: "blood" },
    },
    {
      from: "jiazhen",
      to: "jiaxichun",
      predicate: "sibling_of",
      label: "兄妹",
      note: "惜春是宁府珍爷胞妹，自幼随贾母一处（第二回）",
      qualifiers: { lineage: "blood" },
    },
    {
      from: "qinkeqing",
      to: "jiarong",
      predicate: "spouse_of",
      label: "亡妻",
      note: "可卿是贾蓉之妻，婚后数年病逝（第十三回），这段婚姻随她早逝而止",
      qualifiers: { partnerRole: "wife", lineage: "marriage" },
      validity: { status: "ended", validTo: "1726-12" },
    },
    {
      from: "jiazhen",
      to: "jiabaoyu",
      predicate: "clan_of",
      label: "同宗",
      note: "宁荣两府同出一祖，玉字辈排行（第二回）",
      qualifiers: { lineage: "clan" },
    },
    {
      from: "jiayun",
      to: "jiabaoyu",
      predicate: "clan_of",
      label: "族亲",
      note: "贾芸是贾府西廊下远房子孙，二十四回曾戏认宝玉为父辈",
      qualifiers: { lineage: "clan" },
    },
    {
      from: "jiayun",
      to: "wangxifeng",
      predicate: "collaborates_with",
      label: "差事上的往来",
      note: "贾芸备冰片麝香送礼，领下种树工程（第二十四回）",
    },
    // 仆婢：职分与同僚，不套亲属谓词。
    {
      from: "xiren",
      to: "jiabaoyu",
      predicate: "reports_to",
      label: "伏侍宝玉",
      note: "贾母拨来的大丫头，怡红院首席（第三回、第六回）",
    },
    {
      from: "qingwen",
      to: "jiabaoyu",
      predicate: "reports_to",
      label: "伏侍宝玉",
      note: "贾母拨来的丫头，针线居园中之首（第七十七回）",
    },
    {
      from: "xiren",
      to: "qingwen",
      predicate: "colleague_of",
      label: "怡红院同僚",
      note: "同在怡红院当差",
    },
    {
      from: "yuanyang",
      to: "jiamu",
      predicate: "reports_to",
      label: "伏侍贾母",
      note: "贾母一刻离不得她（第四十六回）",
    },
    {
      from: "zijuan",
      to: "lindaiyu",
      predicate: "reports_to",
      label: "伏侍黛玉",
      note: "贾母处拨去潇湘馆的丫头（第五十七回）",
    },
    {
      from: "pingr",
      to: "wangxifeng",
      predicate: "reports_to",
      label: "陪嫁帮办",
      note: "平儿是凤姐的陪嫁丫头，替她周全两边（第三十九回）",
    },
    {
      from: "xiaohong",
      to: "wangxifeng",
      predicate: "reports_to",
      label: "凤姐房中当差",
      note: "原在怡红院不得出头，被凤姐要去（第二十七回）",
    },
    {
      from: "xiaohong",
      to: "xiren",
      predicate: "colleague_of",
      label: "怡红院旧同僚",
      note: "小红原是怡红院三等丫头（第二十四回）",
    },
    {
      from: "xiaohong",
      to: "jiayun",
      predicate: "knows",
      label: "未言明的情愫",
      note: "第二十六、二十七回坠儿传帕，两人各留对方手帕，心事未挑明",
      pending: true,
    },
    {
      from: "jiayun",
      to: "xiaohong",
      predicate: "has_crush_on",
      label: "有心于小红",
      note: "贾芸拾得小红手帕，托坠儿传话（第二十六回）",
    },
    // 外围一跳：撑起引荐路径。
    {
      from: "liulaolao",
      to: "wangxifeng",
      predicate: "knows",
      label: "打抽丰的远客",
      note: "一进荣国府由周瑞家的引见凤姐（第六回）",
    },
    {
      from: "liulaolao",
      to: "jiamu",
      predicate: "knows",
      label: "府里的老亲家",
      note: "二进时贾母留她游大观园，称「老亲家」（第三十九回）",
    },
    {
      from: "beijingwang",
      to: "jiabaoyu",
      predicate: "knows",
      label: "忘年之交",
      note: "路祭初见即赞宝玉，赠鹡鸰香念珠，邀常往王府（第十五回）",
    },
    {
      from: "jiangyuhan",
      to: "jiabaoyu",
      predicate: "knows",
      label: "互赠汗巾之友",
      note: "冯紫英家宴初见，互赠汗巾（第二十八回）",
    },
    {
      from: "zhenbaoyu",
      to: "jiabaoyu",
      predicate: "knows",
      label: "同名同貌之缘",
      note: "江南甄家公子，与宝玉同名同貌，曾在梦中相会（第二回、第五十六回）",
    },
    {
      from: "jiayucun",
      to: "linruhai",
      predicate: "knows",
      label: "西宾旧谊",
      note: "林如海聘贾雨村为黛玉塾师，又修书荐于贾政（第二回、第三回）",
    },
    {
      from: "jiayucun",
      to: "jiazheng",
      predicate: "knows",
      label: "投帖认宗",
      note: "雨村以宗侄名帖投贾政，得其周旋协谋补授应天府（第三回）",
    },
  ],
  events: [
    {
      date: "1726-11-01",
      precision: "month",
      dateText: "秋尽冬初",
      title: "刘姥姥一进荣国府",
      kind: "帮忙",
      people: ["liulaolao", "wangxifeng"],
      place: "荣国府",
      detail: "王家连宗的刘姥姥进城求助，凤姐接济二十两银子并一串钱（第六回）。",
    },
    {
      date: "1726-12-01",
      precision: "month",
      dateText: "冬月出殡",
      title: "秦可卿之丧，路祭初会北静王",
      kind: "其它",
      people: ["jiarong", "jiazhen", "jiabaoyu", "beijingwang"],
      place: "城外官道",
      detail: "北静王水溶设路祭，与宝玉初见，赠鹡鸰香念珠一串（第十五回）。",
    },
    {
      date: "1727-02-04",
      dateEnd: "1727-02-05",
      precision: "range",
      dateText: "正月十五上元夜",
      title: "元妃省亲",
      kind: "聚会",
      people: ["jiayuanchun", "jiamu", "jiazheng", "wangfuren", "jiabaoyu"],
      place: "大观园省亲别墅",
      detail: "元妃回府省亲，游幸大观园，命宝玉与诸妹题咏（第十七至十八回）。",
    },
    {
      date: "1727-02-10",
      dateText: "正月廿一",
      title: "贾母为宝钗过十五岁生日",
      kind: "聚会",
      people: ["jiamu", "xuebaochai", "jiabaoyu", "wangfuren"],
      place: "贾府内院",
      detail: "贾母蠲资二十两为宝钗作生日，席间点戏，凤姐凑趣（第二十二回）。",
    },
    {
      date: "1727-04-01",
      precision: "month",
      dateText: "三月中浣",
      title: "共读西厢",
      kind: "约会",
      people: ["jiabaoyu", "lindaiyu"],
      place: "沁芳闸桥边桃花树下",
      detail: "宝玉携《会真记》在桃花下细读，与黛玉同看，落红成阵（第二十三回）。",
    },
    {
      date: "1727-04-01",
      precision: "month",
      dateText: "暮春",
      title: "贾芸谋差领种树工程",
      kind: "帮忙",
      people: ["jiayun", "wangxifeng", "jiabaoyu"],
      place: "荣国府",
      detail: "贾芸备冰片麝香走凤姐门路，领下种树的差事；宝玉曾戏言他像自己的儿子（第二十四回）。",
    },
    {
      date: "1727-05-01",
      precision: "month",
      dateText: "初夏家宴",
      title: "冯紫英家宴，互赠汗巾",
      kind: "送礼",
      people: ["jiabaoyu", "jiangyuhan", "xuepan"],
      place: "冯紫英府",
      detail: "席上蒋玉菡解茜香罗汗巾赠宝玉，宝玉以松花汗巾相回（第二十八回）。",
    },
    {
      date: "1728-07-01",
      precision: "month",
      dateText: "端午后盛暑",
      title: "宝玉挨打",
      kind: "其它",
      people: ["jiabaoyu", "jiazheng", "jiahuan", "wangfuren"],
      place: "荣国府外书房",
      detail: "忠顺府上门索人、贾环进谗，贾政盛怒笞挞宝玉，王夫人闻讯赶来（第三十三回）。",
    },
    {
      date: "1728-09-01",
      precision: "month",
      dateText: "八月",
      title: "海棠诗社成立",
      kind: "聚会",
      people: ["jiatanchun", "lindaiyu", "xuebaochai", "shixiangyun", "jiabaoyu"],
      place: "秋爽斋",
      detail: "探春发帖起社，众人各取别号，首咏白海棠（第三十七回）。",
    },
    {
      date: "1728-10-01",
      precision: "month",
      dateText: "秋深，紧随诗社之后",
      title: "刘姥姥游大观园",
      kind: "聚会",
      people: ["liulaolao", "jiamu", "wangxifeng", "jiabaoyu"],
      place: "大观园",
      detail: "贾母两宴大观园，刘姥姥乘船游园、醉卧怡红院（第三十九至四十一回）。",
    },
    {
      date: "1728-11-01",
      precision: "month",
      dateText: "深秋",
      title: "鸳鸯剪发明志",
      kind: "其它",
      people: ["yuanyang", "jiamu", "jiashe"],
      place: "贾母上房",
      detail: "贾赦欲讨鸳鸯为妾，鸳鸯在贾母面前铰发立誓（第四十六回）。",
    },
    {
      date: "1729-02-01",
      precision: "month",
      dateText: "冬末午睡",
      title: "宝玉梦甄宝玉",
      kind: "其它",
      people: ["jiabaoyu", "zhenbaoyu"],
      place: "怡红院",
      detail: "宝玉午梦见江南甄家有位同名同貌的甄宝玉，醒来心中疑惑（第五十六回）。",
    },
    {
      date: "1729-03-01",
      precision: "month",
      dateText: "初春",
      title: "紫鹃试玉",
      kind: "其它",
      people: ["zijuan", "jiabaoyu", "lindaiyu"],
      place: "潇湘馆、怡红院",
      detail: "紫鹃以「黛玉要回苏州」试宝玉心意，宝玉痰迷心窍大病一场（第五十七回）。",
    },
    {
      date: "1729-09-01",
      precision: "month",
      dateText: "中秋前夕",
      title: "抄检大观园",
      kind: "其它",
      people: ["wangxifeng", "jiatanchun", "qingwen", "xiren", "jiabaoyu"],
      place: "大观园各处",
      detail: "绣春囊事发，凤姐奉命夜抄各房：探春秉烛开门而待，晴雯挽着头发倒箧（第七十四回）。",
    },
    {
      date: "1729-10-01",
      precision: "month",
      dateText: "八月末",
      title: "诔祭晴雯",
      kind: "其它",
      people: ["jiabaoyu", "qingwen"],
      place: "园中芙蓉花前",
      detail: "晴雯病逝后，宝玉作《芙蓉女儿诔》，夜读致祭（第七十七至七十八回）。",
    },
  ],
  reminders: [
    { title: "回帖北静王", due: "2026-09-22", people: ["beijingwang"], kind: "custom" },
    { title: "陪贾母过中秋", due: "2026-09-25", people: ["jiamu", "jiabaoyu"], kind: "festival" },
    { title: "给林妹妹送时新果品", due: "2026-09-28", people: ["lindaiyu"], kind: "gift" },
    {
      title: "海棠社下次社课备题",
      due: "2026-10-08",
      people: ["xuebaochai", "lindaiyu", "jiatanchun", "shixiangyun", "jiabaoyu"],
      kind: "custom",
    },
  ],
};
