import type { DemoPack } from "../types";

/**
 * 世界剧场·黑暗森林：取材自《三体》三部曲的世纪尺度协作网。
 *
 * 本库的灵魂是时间跨度：事件从 1971 年红岸发射一路排到掩体纪元，
 * 几乎全部用 year/range 精度 + 原著纪年原文（dateText），是「时间精度」
 * 特性的最佳演示。公历年份只负责排序，映射口径见 doc/research/demo-packs/santi.md。
 * 生日均为合成填充，原著无设定。
 */
export const santiPack: DemoPack = {
  id: "santi",
  group: "world",
  name: "黑暗森林",
  description: "跨越世纪的协作与抉择",
  example: "末日之战前，该找谁了解敌人？",
  universe: "半人马座三星无规则起落，四光年外的舰队驶向太阳系，人类有四个世纪做准备。",
  egoKey: "luoji",
  collections: [
    {
      name: "面壁计划",
      members: ["luoji", "tayler", "leidiyazi", "xiensi", "shanshanhuizi"],
    },
    { name: "行星防御理事会", members: ["sayi", "jiaer-ning", "changweiwei", "shiqiang"] },
    { name: "舰队国际", members: ["zhangbeihai", "dongfangyanxu", "dingyi", "guanyifan"] },
    { name: "红岸基地", members: ["yewenjie", "yangweining", "leizhicheng"] },
    { name: "黄金时代亲属圈", members: ["yewenjie", "yangweining", "yangdong"] },
    { name: "黄金时代旧识", members: ["wangmiao", "dingyi", "shenyufei", "bairong"] },
    { name: "阶梯计划", members: ["yuntianming", "chengxin", "weide", "sayi"] },
    { name: "威慑纪元·星环", members: ["chengxin", "aa", "weide", "guanyifan"] },
    { name: "罗辑的小家庭", members: ["luoji", "zhuangyan"] },
  ],
  people: [
    {
      key: "luoji",
      name: "罗辑",
      profile: {
        gender: "男",
        relation: "面壁者，后来的执剑人（本库主角）",
        title: "大学社会学教师（受任面壁者前）",
        org: "面壁计划",
        likes: ["湖畔小住", "雪景"],
        projects: ["雪地工程（模拟）", "黑暗森林威慑（模拟）"],
        contact: "demo-luoji@example.invalid",
        closeness: 5,
        birthday: "06-12",
        metAt: "本人",
        identities: [
          {
            platform: "面壁计划（模拟）",
            alias: "面壁者",
            validFrom: "危机纪元 3 年",
            validTo: "危机纪元 208 年",
          },
          {
            platform: "黑暗森林威慑（模拟）",
            alias: "执剑人",
            validFrom: "威慑纪元元年",
            validTo: "威慑纪元 62 年",
          },
        ],
      },
      note: "原著第二、三部人物：由散漫学者受任面壁者，最终建立并守护黑暗森林威慑五十四年。",
      touched: true,
    },
    {
      key: "shiqiang",
      name: "史强",
      profile: {
        gender: "男",
        relation: "老史：危机年代护送罗辑的警察",
        title: "刑警出身的安全联络官",
        org: "行星防御理事会",
        likes: ["雪茄", "家常菜"],
        contact: "demo-shiqiang@example.invalid",
        closeness: 5,
        birthday: "01-28",
        metAt: "危机爆发时的护送任务",
      },
      note: "原著第一部至第二部，史强先后护送汪淼与罗辑，并在近两个世纪后与罗辑重逢。",
    },
    {
      key: "yewenjie",
      name: "叶文洁",
      profile: {
        gender: "女",
        relation: "杨冬的母亲，红岸基地技术骨干",
        title: "天体物理学家（退休）",
        org: "红岸基地",
        likes: ["射电天文"],
        closeness: 2,
        metAt: "杨冬墓前的一席话",
      },
      note: "原著第一部核心人物：1971 年自红岸基地向太阳发射信息，八年后收到警告并作出回应；危机纪元初去世。红岸时期档案不全，未留联系方式与生日。",
    },
    {
      key: "yangdong",
      name: "杨冬",
      profile: {
        gender: "女",
        relation: "叶文洁之女，理论物理学家",
        title: "理论物理学家",
        likes: ["理论物理"],
        closeness: 1,
        birthday: "03-08",
        metAt: "档案追溯",
      },
      note: "原著第一部，杨冬因实验规律失效离世；她墓前的一场谈话，成为罗辑日后破局的起点。",
    },
    {
      key: "yangweining",
      name: "杨卫宁",
      profile: {
        gender: "男",
        relation: "杨冬之父，红岸基地工程师",
        title: "红岸基地工程师",
        org: "红岸基地",
        closeness: 1,
        metAt: "档案追溯",
      },
      note: "原著第一部，杨卫宁与叶文洁在红岸基地共事成婚；1979 年前后在基地崖体事故中身亡，女儿杨冬幼年丧父。早期档案不全，未留生日。",
    },
    {
      key: "leizhicheng",
      name: "雷志成",
      profile: {
        gender: "男",
        relation: "红岸基地政委（历史人物）",
        title: "红岸基地政委",
        org: "红岸基地",
        closeness: 1,
        metAt: "档案追溯",
      },
      note: "原著第一部，雷志成主持红岸基地日常运行，与叶文洁、杨卫宁共事；1979 年前后在崖体事故中身亡。早期档案不全，未留生日。",
    },
    {
      key: "wangmiao",
      name: "汪淼",
      profile: {
        gender: "男",
        relation: "纳米材料学家，与罗辑时代相近的学者",
        title: "纳米材料学家",
        likes: ["纳米材料"],
        contact: "demo-wangmiao@example.invalid",
        closeness: 1,
        birthday: "09-03",
        metAt: "经叶文洁与史强间接相连",
      },
      note: "原著第一部主角之一：从倒计时与宇宙闪烁入手揭开危机，参与古筝行动；与罗辑本人交往很浅。",
    },
    {
      key: "dingyi",
      name: "丁仪",
      profile: {
        gender: "男",
        relation: "杨冬的恋人，理论物理学家",
        title: "大学物理教授",
        likes: ["台球"],
        closeness: 1,
        birthday: "11-21",
        metAt: "档案追溯",
      },
      note: "原著第一部与第二部人物：与杨冬相恋；冬眠至危机纪元 205 年，在末日之战中随舰队罹难。",
    },
    {
      key: "changweiwei",
      name: "常伟思",
      profile: {
        gender: "男",
        relation: "作战中心与太空军的首长",
        title: "将军，太空军早期主官",
        org: "行星防御理事会",
        contact: "demo-changweiwei@example.invalid",
        closeness: 2,
        birthday: "08-15",
        metAt: "PDC 场合",
      },
      note: "原著第一部与第二部，常伟思主持作战中心，后主持太空军创建；章北海与史强都曾在其麾下。",
    },
    {
      key: "shenyufei",
      name: "申玉菲",
      profile: {
        gender: "女",
        relation: "「科学边界」的联系人",
        title: "「科学边界」成员",
        contact: "demo-shenyufei@example.invalid",
        closeness: 1,
        birthday: "04-27",
        metAt: "档案追溯",
      },
      note: "原著第一部，「科学边界」成员，与汪淼在聚会及其后的风波中数度往来。",
    },
    {
      key: "bairong",
      name: "白蓉",
      profile: {
        gender: "女",
        relation: "罗辑早年的恋人",
        title: "青年小说作者",
        closeness: 2,
        metAt: "危机前的恋爱",
      },
      note: "原著第二部，白蓉让罗辑构想「完美的女孩」，这段往事埋下了他后来遇见庄颜的伏笔。档案未留联系方式与生日。",
    },
    {
      key: "zhuangyan",
      name: "庄颜",
      profile: {
        gender: "女",
        relation: "罗辑的妻子",
        title: "美术学院学生（相识时）",
        likes: ["油画", "素描"],
        contact: "demo-zhuangyan@example.invalid",
        closeness: 5,
        birthday: "05-16",
        metAt: "史强的寻访",
      },
      note: "原著第二部，史强依罗辑的描述寻访到庄颜，两人结为夫妻并育有一女；后与女儿一同冬眠，与罗辑在新世纪重逢。",
    },
    {
      key: "zhangbeihai",
      name: "章北海",
      profile: {
        gender: "男",
        relation: "太空军军人，「自然选择」号上的关键人物",
        title: "太空军军官",
        org: "舰队国际",
        likes: ["星际航行"],
        closeness: 3,
        birthday: "07-09",
        metAt: "PDC 场合",
      },
      note: "原著第二部人物：以自己的方式为人类留存星际火种，危机纪元 205 年在「黑暗战役」中随舰罹难。",
    },
    {
      key: "dongfangyanxu",
      name: "东方延绪",
      profile: {
        gender: "女",
        relation: "「自然选择」号舰长，章北海在舰上的老师",
        title: "「自然选择」号舰长",
        org: "舰队国际",
        closeness: 1,
        birthday: "02-23",
        metAt: "档案追溯",
      },
      note: "原著第二部，东方延绪向随舰学习的章北海讲授舰船系统；舰只出走后与追击编队一同陷入「黑暗战役」。",
    },
    {
      key: "tayler",
      name: "泰勒",
      profile: {
        gender: "男",
        relation: "同批面壁者",
        title: "面壁者（前国防事务官员）",
        org: "面壁计划",
        closeness: 2,
        metAt: "面壁计划受任式",
      },
      note: "原著第二部，泰勒是四位面壁者之一，其计划被破壁人识破后离世。档案未留联系方式与生日。",
    },
    {
      key: "leidiyazi",
      name: "雷迪亚兹",
      profile: {
        gender: "男",
        relation: "同批面壁者",
        title: "面壁者（恒星型氢弹计划提出者）",
        org: "面壁计划",
        closeness: 2,
        metAt: "面壁计划受任式",
      },
      note: "原著第二部，雷迪亚兹的面壁计划围绕巨型氢弹展开；计划终止后回国，遇袭身亡。档案未留联系方式与生日。",
    },
    {
      key: "xiensi",
      name: "希恩斯",
      profile: {
        gender: "男",
        relation: "同批面壁者，脑科学研究者",
        title: "面壁者（神经科学家）",
        org: "面壁计划",
        likes: ["脑科学"],
        contact: "demo-xiensi@example.invalid",
        closeness: 2,
        birthday: "10-02",
        metAt: "面壁计划受任式",
      },
      note: "原著第二部，希恩斯研究大脑思维与「思想钢印」，他的破壁人正是妻子山杉惠子。",
    },
    {
      key: "shanshanhuizi",
      name: "山杉惠子",
      profile: {
        gender: "女",
        relation: "希恩斯的妻子，也是他的破壁人",
        title: "神经科学家",
        org: "面壁计划",
        contact: "demo-shanshanhuizi@example.invalid",
        closeness: 1,
        birthday: "12-06",
        metAt: "随希恩斯出现在联合国",
      },
      note: "原著第二部，山杉惠子与希恩斯既是配偶，又是面壁计划里指给他的破壁人，双重身份在计划终结时公开。",
    },
    {
      key: "sayi",
      name: "萨伊",
      profile: {
        gender: "女",
        relation: "危机初期的联合国秘书长",
        title: "联合国秘书长（危机初期）",
        contact: "demo-sayi@example.invalid",
        closeness: 2,
        birthday: "03-19",
        metAt: "面壁计划说明会",
      },
      note: "原著第一部至第二部，萨伊主持危机初期的联合国事务；面壁计划与群星计划都由她宣布。",
    },
    {
      key: "jiaer-ning",
      name: "伽尔宁",
      profile: {
        gender: "男",
        relation: "PDC 轮值主席",
        title: "行星防御理事会轮值主席",
        contact: "demo-jiaer-ning@example.invalid",
        closeness: 2,
        birthday: "09-30",
        metAt: "面壁计划听证",
      },
      note: "原著第二部，伽尔宁主持面壁计划的听证与资源调配，对罗辑的种种要求几乎照单全收。",
    },
    {
      key: "chengxin",
      name: "程心",
      profile: {
        gender: "女",
        relation: "阶梯计划与星环集团的关键人物，末任执剑人",
        title: "航天发动机博士",
        org: "星环集团",
        likes: ["航天工程"],
        projects: ["阶梯计划（模拟）", "星环集团光速飞船（模拟）"],
        contact: "demo-chengxin@example.invalid",
        closeness: 2,
        birthday: "01-07",
        metAt: "执剑人交接",
      },
      note: "原著第三部主角：送别云天明、接过执剑人身份，又两次在关键抉择中退让。",
      touched: true,
    },
    {
      key: "yuntianming",
      name: "云天明",
      profile: {
        gender: "男",
        relation: "程心的大学同学",
        title: "工程师（患病离职前）",
        closeness: 1,
        birthday: "08-11",
        metAt: "档案追溯",
        identities: [{ platform: "阶梯计划（模拟）", alias: "礼物", validFrom: "危机纪元 8 年" }],
      },
      note: "原著第三部，云天明在生命末段匿名买下恒星 DX3906 赠予程心，随后作为阶梯计划的乘员离开太阳系；此后只能借会面传话。",
    },
    {
      key: "aa",
      name: "艾AA",
      profile: {
        gender: "女",
        relation: "程心最信任的同伴",
        title: "程心的助理，后为星环集团同事",
        org: "星环集团",
        contact: "demo-aa@example.invalid",
        closeness: 1,
        birthday: "04-01",
        metAt: "档案追溯",
      },
      note: "原著第三部，艾AA陪伴程心两次冬眠，太阳系二维化时与她同乘「星环」号离开。",
    },
    {
      key: "weide",
      name: "维德",
      profile: {
        gender: "男",
        relation: "星环集团的掌舵人，程心的上级",
        title: "情报机构局长，后执掌星环集团",
        org: "星环集团",
        likes: ["古董手枪"],
        contact: "demo-weide@example.invalid",
        closeness: 2,
        birthday: "10-31",
        metAt: "档案追溯",
      },
      note: "原著第三部，维德先后主持阶梯计划与星环集团，为推进光速飞船不惜代价；掩体纪元 11 年遵守对程心的承诺放弃抵抗。",
    },
    {
      key: "guanyifan",
      name: "关一帆",
      profile: {
        gender: "男",
        relation: "程心最后的同伴",
        title: "「万有引力」号船员，宇宙学家",
        org: "舰队国际",
        likes: ["宇宙学"],
        contact: "demo-guanyifan@example.invalid",
        closeness: 1,
        birthday: "06-25",
        metAt: "档案追溯",
      },
      note: "原著第三部，关一帆随「万有引力」号辗转至 DX3906 星系，在蓝星与程心相遇。",
    },
  ],
  relations: [
    {
      from: "yewenjie",
      to: "yangdong",
      predicate: "parent_of",
      label: "母女",
      note: "原著第一部，叶文洁是杨冬的母亲；杨冬于危机纪元初去世，此条亲缘记录保留。",
      qualifiers: { parentRole: "mother", childRole: "daughter", lineage: "blood" },
      validity: { status: "ended", validTo: "危机纪元元年" },
    },
    {
      from: "yangweining",
      to: "yangdong",
      predicate: "parent_of",
      label: "父女",
      note: "原著第一部，杨卫宁是杨冬的父亲，杨冬幼年丧父。",
      qualifiers: { parentRole: "father", childRole: "daughter", lineage: "blood" },
      validity: { status: "ended", validTo: "1979" },
    },
    {
      from: "yangweining",
      to: "yewenjie",
      predicate: "spouse_of",
      label: "夫妻",
      note: "原著第一部，两人在红岸基地共事期间成婚；1979 年前后杨卫宁在崖体事故中身亡。",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
      validity: { status: "ended", validFrom: "1970 年代", validTo: "1979" },
    },
    {
      from: "leizhicheng",
      to: "yewenjie",
      predicate: "colleague_of",
      label: "红岸同事",
      note: "原著第一部，雷志成主持基地运行，叶文洁是其麾下技术骨干。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "1979" },
    },
    {
      from: "leizhicheng",
      to: "yangweining",
      predicate: "colleague_of",
      label: "红岸同事",
      note: "原著第一部，两人在红岸基地共事多年。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "1979" },
    },
    {
      from: "wangmiao",
      to: "yewenjie",
      predicate: "knows",
      label: "求教过的前辈",
      note: "原著第一部，汪淼就「科学边界」与倒计时之谜上门求教，叶文洁向他讲述红岸往事。",
    },
    {
      from: "shenyufei",
      to: "wangmiao",
      predicate: "knows",
      label: "「科学边界」的熟人",
      note: "原著第一部，两人在「科学边界」的聚会上相识。",
    },
    {
      from: "dingyi",
      to: "wangmiao",
      predicate: "friend_of",
      label: "球友",
      note: "原著第一部开篇，两人常在一起打台球谈物理。",
    },
    {
      from: "dingyi",
      to: "yangdong",
      predicate: "custom",
      label: "恋人",
      note: "原著提及丁仪与杨冬相恋并已论及婚嫁；杨冬于危机纪元初去世。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "危机纪元元年" },
    },
    {
      from: "dingyi",
      to: "yewenjie",
      predicate: "knows",
      label: "经由杨冬相识",
      note: "原著第一部，丁仪经恋人杨冬与叶文洁相识。",
    },
    {
      from: "luoji",
      to: "zhuangyan",
      predicate: "spouse_of",
      label: "夫妻",
      note: "原著第二部，两人结为夫妻并育有一女；罗辑就任执剑人后长期分离。",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
    },
    {
      from: "luoji",
      to: "bairong",
      predicate: "custom",
      label: "前女友",
      note: "原著第二部，白蓉与罗辑在危机前相恋；她让他构想「完美女孩」的那次写作，间接引出了后来的庄颜。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "危机纪元前" },
    },
    {
      from: "zhuangyan",
      to: "shiqiang",
      predicate: "knows",
      label: "寻访之谊",
      note: "原著第二部，史强依罗辑的描述找到在美术学院就读的庄颜。",
    },
    {
      from: "luoji",
      to: "yewenjie",
      predicate: "knows",
      label: "一席话的前辈",
      note: "原著第二部开篇追述：危机纪元初，叶文洁在杨冬墓前向罗辑提出宇宙社会学的两条公理，成为他日后建立威慑的种子。",
    },
    {
      from: "luoji",
      to: "shiqiang",
      predicate: "collaborates_with",
      label: "老搭档",
      note: "原著第二部，危机爆发时史强护送罗辑撤离，近两个世纪后又陪他重新适应世界。",
    },
    {
      from: "shiqiang",
      to: "wangmiao",
      predicate: "collaborates_with",
      label: "并肩的搭档",
      note: "原著第一部，史强担任汪淼的安保联络人，两人一同经历倒计时风波与古筝行动。",
    },
    {
      from: "shiqiang",
      to: "changweiwei",
      predicate: "reports_to",
      label: "老上级",
      note: "原著第一部，史强在常伟思主持的作战中心参与危机应对；冬眠后隶属关系结束。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended" },
    },
    {
      from: "luoji",
      to: "zhangbeihai",
      predicate: "knows",
      label: "PDC 场合的相识",
      note: "原著第二部，两人在行星防御理事会的场合相识。",
    },
    {
      from: "zhangbeihai",
      to: "changweiwei",
      predicate: "reports_to",
      label: "器重的部下",
      note: "原著第二部，章北海在常伟思麾下加入太空军；他的冬眠请求（「增援未来」）获得批准。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended" },
    },
    {
      from: "zhangbeihai",
      to: "changweiwei",
      predicate: "knows",
      label: "立场存疑（待确认）",
      note: "原著中常伟思始终未能完全确认章北海的真实立场，档案按原著保留这一存疑。",
      pending: true,
    },
    {
      from: "zhangbeihai",
      to: "dongfangyanxu",
      predicate: "colleague_of",
      label: "舰上师生",
      note: "原著第二部，东方延绪是「自然选择」号舰长，也是随舰学习的章北海的老师；「黑暗战役」中两人一同罹难。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "危机纪元 205 年" },
    },
    {
      from: "luoji",
      to: "tayler",
      predicate: "knows",
      label: "面壁同僚",
      note: "原著第二部，泰勒与罗辑同批受任面壁者，其计划被破壁人识破后离世。",
    },
    {
      from: "luoji",
      to: "leidiyazi",
      predicate: "knows",
      label: "面壁同僚",
      note: "原著第二部，雷迪亚兹与罗辑同批受任面壁者，主张以巨型氢弹威慑对手。",
    },
    {
      from: "luoji",
      to: "xiensi",
      predicate: "knows",
      label: "面壁同僚",
      note: "原著第二部，希恩斯与罗辑同批受任面壁者，研究方向是大脑与思维。",
    },
    {
      from: "xiensi",
      to: "shanshanhuizi",
      predicate: "spouse_of",
      label: "夫妻",
      note: "原著第二部，山杉惠子是希恩斯的妻子，也是他的破壁人，双重身份在计划终结时公开。",
      qualifiers: { partnerRole: "husband", lineage: "marriage" },
    },
    {
      from: "sayi",
      to: "luoji",
      predicate: "knows",
      label: "宣布任命的秘书长",
      note: "原著第二部，时任联合国秘书长萨伊向罗辑说明面壁计划的规则；罗辑的推辞被她视作计划的一部分。",
    },
    {
      from: "jiaer-ning",
      to: "luoji",
      predicate: "knows",
      label: "PDC 的老主席",
      note: "原著第二部，PDC 轮值主席伽尔宁主持面壁计划事务，罗辑的要求他大多照办。",
    },
    {
      from: "sayi",
      to: "jiaer-ning",
      predicate: "colleague_of",
      label: "PDC 同僚",
      note: "原著第二部，危机初期两人在联合国与行星防御理事会体系内共事。",
    },
    {
      from: "yuntianming",
      to: "chengxin",
      predicate: "has_crush_on",
      label: "暗恋",
      note: "原著第三部，云天明在大学时即暗恋程心；生命末段通过群星计划匿名买下恒星 DX3906 赠予她。",
    },
    {
      from: "yuntianming",
      to: "chengxin",
      predicate: "classmate_of",
      label: "大学同学",
      note: "原著第三部，两人是大学同学，程心当时并未留意这位沉默的同学。",
      qualifiers: { temporalStatus: "former" },
    },
    {
      from: "chengxin",
      to: "weide",
      predicate: "reports_to",
      label: "两度共事的上级",
      note: "原著第三部，危机纪元程心在阶梯计划团队向维德汇报，掩体纪元星环集团任内再次成为其下属。",
      qualifiers: { temporalStatus: "former" },
      validity: { status: "ended", validTo: "掩体纪元 11 年" },
    },
    {
      from: "chengxin",
      to: "aa",
      predicate: "friend_of",
      label: "最信任的同伴",
      note: "原著第三部，艾AA长期任程心助理，两次冬眠后仍与她同行。",
    },
    {
      from: "chengxin",
      to: "guanyifan",
      predicate: "spouse_of",
      label: "伴侣",
      note: "原著第三部结尾，两人在 DX3906 星系的蓝星相遇，此后共同生活。",
      qualifiers: { partnerRole: "partner" },
    },
    {
      from: "luoji",
      to: "chengxin",
      predicate: "knows",
      label: "交接人",
      note: "原著第三部，威慑纪元 62 年，罗辑将威慑遥控装置移交给程心。",
    },
    {
      from: "changweiwei",
      to: "wangmiao",
      predicate: "knows",
      label: "作战中心的将军与顾问",
      note: "原著第一部，汪淼以学者身份参与常伟思主持的危机通报会议。",
    },
    {
      from: "tayler",
      to: "xiensi",
      predicate: "knows",
      label: "面壁同僚",
      note: "原著第二部，四位面壁者在联合国受任时相识，计划要求他们彼此保持距离。",
    },
    {
      from: "aa",
      to: "guanyifan",
      predicate: "knows",
      label: "蓝星初见",
      note: "原著第三部，艾AA与关一帆在蓝星相识。",
    },
  ],
  events: [
    {
      date: "1971-09-01",
      precision: "year",
      dateText: "1971 年秋",
      title: "红岸基地首次向太阳发射",
      kind: "其它",
      place: "红岸基地",
      people: ["yewenjie", "leizhicheng"],
      detail: "叶文洁借雷达检修之机验证太阳能量镜面猜想，把一条电波经太阳放大后发向深空。",
    },
    {
      date: "1979-10-01",
      precision: "year",
      dateText: "1979 年秋",
      title: "收到「不要回答」的警告",
      kind: "其它",
      people: ["yewenjie"],
      detail: "来自半人马座三星的监听员发来警告；叶文洁按下发射键作出回应，坐标由此暴露。",
    },
    {
      date: "1979-11-01",
      precision: "year",
      dateText: "1979 年深秋",
      title: "红岸崖体事故",
      kind: "其它",
      place: "红岸基地崖壁",
      people: ["yewenjie", "yangweining", "leizhicheng"],
      detail: "杨卫宁与雷志成在崖体事故中坠亡，回信的秘密由叶文洁独自保守。",
    },
    {
      date: "2007-06-01",
      precision: "year",
      dateText: "危机纪元前夜",
      title: "宇宙背景辐射整体闪烁",
      kind: "其它",
      people: ["wangmiao"],
      detail:
        "汪淼透过 3K 眼镜目睹整片宇宙的「闪烁」，随之而来的是实验规律失效与物理学界的连串变故。",
    },
    {
      date: "2008-05-01",
      precision: "year",
      dateText: "危机纪元 2 年",
      title: "古筝行动：「审判日」号被截停",
      kind: "其它",
      place: "巴拿马运河",
      people: ["wangmiao", "shiqiang", "changweiwei"],
      detail: "纳米丝在运河上割开「审判日」号，行动回收了对方组织与地球往来的信息。",
    },
    {
      date: "2009-03-01",
      dateEnd: "2009-06-01",
      precision: "range",
      dateText: "危机纪元 3 年",
      title: "面壁计划启动",
      kind: "其它",
      place: "联合国",
      people: ["luoji", "tayler", "leidiyazi", "xiensi", "sayi", "jiaer-ning"],
      detail:
        "行星防御理事会宣布面壁计划，四位面壁者受任并获几乎不受限制的资源；罗辑始终不知道自己为何入选。",
    },
    {
      date: "2010-04-01",
      precision: "year",
      dateText: "危机纪元 4 年",
      title: "史强把庄颜带到罗辑面前",
      kind: "帮忙",
      place: "湖畔庄园",
      people: ["luoji", "zhuangyan", "shiqiang"],
      detail: "史强依罗辑的描述在美术学院寻访到庄颜，把她带到了罗辑面前。",
    },
    {
      date: "2013-12-01",
      precision: "year",
      dateText: "危机纪元 7 年",
      title: "DX3906 的赠与",
      kind: "送礼",
      people: ["yuntianming", "chengxin"],
      detail:
        "云天明在病中通过群星计划匿名买下恒星 DX3906 的所有权送给程心，程心当时对此并不知情。",
    },
    {
      date: "2014-07-01",
      precision: "year",
      dateText: "危机纪元 8 年",
      title: "阶梯计划发射送别",
      kind: "帮忙",
      people: ["yuntianming", "chengxin", "weide"],
      detail: "载有云天明大脑的探测器由核弹阵列逐级加速启程；程心曾到病房探望并动员他加入计划。",
    },
    {
      date: "2211-06-01",
      precision: "year",
      dateText: "危机纪元 205 年",
      title: "罗辑与史强在新世纪重逢",
      kind: "聚会",
      people: ["luoji", "shiqiang"],
      detail: "罗辑结束近两个世纪的冬眠，史强同期苏醒，两人在面目全非的世界里重新搭档。",
    },
    {
      date: "2211-08-01",
      precision: "year",
      dateText: "危机纪元 205 年",
      title: "「自然选择」号出走",
      kind: "其它",
      people: ["zhangbeihai", "dongfangyanxu"],
      detail:
        "末日之战前夕，章北海取得舰只操控权，率「自然选择」号驶离编队，舰长东方延绪随舰同行。",
    },
    {
      date: "2211-10-01",
      precision: "year",
      dateText: "危机纪元 205 年",
      title: "末日之战",
      kind: "其它",
      people: ["dingyi"],
      detail: "探测器「水滴」在近距离接触中摧毁人类联合舰队，登舰考察的丁仪等人罹难。",
    },
    {
      date: "2211-12-01",
      precision: "year",
      dateText: "危机纪元 205 年",
      title: "黑暗战役",
      kind: "其它",
      people: ["zhangbeihai", "dongfangyanxu"],
      detail:
        "逃亡的战舰为燃料与配件彼此攻击，「自然选择」号全员罹难；章北海留下的最后一句话是「没关系的，都一样」。",
    },
    {
      date: "2214-06-01",
      precision: "year",
      dateText: "危机纪元 208 年",
      title: "黑暗森林威慑建立",
      kind: "其它",
      place: "雪地工程阵列",
      people: ["luoji"],
      detail: "罗辑以雪地工程的核弹阵列与对手摊牌，进攻停止，地球与对方进入威慑对峙。",
    },
    {
      date: "2276-11-18",
      precision: "day",
      dateText: "威慑纪元 62 年 11 月 18 日",
      title: "执剑人交接",
      kind: "其它",
      people: ["luoji", "chengxin"],
      detail: "罗辑在任五十四年后把威慑遥控装置移交程心；数分钟后水滴攻击开始，威慑时代结束。",
    },
    {
      date: "2284-05-01",
      precision: "year",
      dateText: "广播纪元 7 年",
      title: "与云天明的会面",
      kind: "通话",
      people: ["chengxin", "yuntianming"],
      detail: "借智子营造的会面环境，云天明向程心讲了三个童话，把关键情报藏在故事里。",
    },
    {
      date: "2343-09-01",
      precision: "year",
      dateText: "掩体纪元 11 年",
      title: "星环城事件",
      kind: "其它",
      people: ["chengxin", "weide", "aa"],
      detail: "程心被唤醒调停星环城独立风波，维德遵守对她的承诺放弃抵抗，光速飞船研究中辍。",
    },
    {
      date: "2398-07-01",
      precision: "year",
      dateText: "掩体纪元 66 年",
      title: "太阳系二维化",
      kind: "其它",
      people: ["chengxin", "aa"],
      detail: "降维打击开始，太阳系跌向二维平面；程心与艾AA乘曲率驱动的「星环」号离开。",
    },
    {
      date: "2398-07-05",
      precision: "day",
      dateText: "掩体纪元 66 年（航程五十二小时）",
      title: "蓝星重逢",
      kind: "聚会",
      people: ["chengxin", "aa", "guanyifan"],
      detail: "抵达 DX3906 星系的蓝星，与「万有引力」号来客关一帆相遇。",
    },
  ],
  reminders: [
    {
      title: "复核雪地工程阵列巡检报告",
      due: "2026-09-22",
      people: ["luoji"],
      kind: "custom",
    },
    {
      title: "回复 PDC 听证会的质询函",
      due: "2026-09-28",
      people: ["luoji", "jiaer-ning"],
      kind: "custom",
    },
    {
      title: "和史强补一顿涮羊肉",
      due: "2026-10-08",
      people: ["luoji", "shiqiang"],
      kind: "custom",
    },
    {
      title: "为庄颜寻一册新画册",
      due: "2026-10-12",
      people: ["luoji", "zhuangyan"],
      kind: "gift",
    },
  ],
};
